`1902` Update Signers UX for Multisig
decentdao/decent-interface pull request #1921
Opened 2024-05-24 20:58 UTC by Da-Colon

Fixes #1902 

![image](https://github.com/decentdao/decent-interface/assets/38386583/db384bc6-12cf-400d-b561-ada86170aadb)

## Dev notes
- I move the modal opening `useFractalModal` into the `Signer` Component passing the needed props through. Because of how the modal consumes the address, I was able to use the current state setup in this way, so removed that. 
- I use `Button` component with a `Icon` inside as the size property. `icon-sm` and `icon-lg` for IconButton didn't fit with figma design of `20x20` for Icon.

2024-05-25 05:42 UTC, tomstuart123 approved these changes
Nice, to the design and approved

Note - @decentdao/design  - I missed the figma so sorry for the late discussion topic. Can I understand the red warning a bit? My usual impression in our app is warnings are yellow in the app and red is errors ?

Devs - this is just an open question for my knowledge, don't let it stop pushing to production

2024-05-25 16:50 UTC, adamgall approved these changes
Approved, nice job. Also agree with Tom's question when removing a singer. Should that message be in red? or yellow. I'd suggest changing it to yellow.

2024-05-28 12:51 UTC, adamgall commented
@xraystyle1980 if red is intentional, I don't want to cause friction here. After @tomstuart123 raised it, my gut also went to "red == error" (which isn't the case here).

2024-05-28 12:57 UTC, xraystyle1980 commented
> @xraystyle1980 if red is intentional, I don't want to cause friction here. My thinking was that after @tomstuart123 raised it, my gut also went to "red == error" (which isn't the case here).

Good to hear. As it stand, we don't currently have a pattern for making the input yellow. Can we adjust the input to not appear red? See example:
![image](https://github.com/decentdao/decent-interface/assets/18615633/9f3f7feb-a0d3-4a69-8840-9a03b0721c6a)

2024-05-28 12:58 UTC, xraystyle1980 requested changes
Update the input with the address being removed to not be red
![image](https://github.com/decentdao/decent-interface/assets/18615633/a32fe914-8cb4-40ff-8f20-3ddd06f36b8e)

2024-05-28 13:43 UTC, DarksightKellar approved these changes

2024-05-28 17:12 UTC, Da-Colon commented
@xraystyle1980 replaced setup with the disabled input 🫡 

![image](https://github.com/decentdao/decent-interface/assets/38386583/382b68b3-be9c-4793-8f8d-048fecb387db)

2024-05-28 20:52 UTC, xraystyle1980 approved these changes
Looks good. :shipit:

2024-05-28 20:56 UTC, merged