`1932`  adds fallback compatibility for older and mobile browsers
decentdao/decent-interface pull request #1933
Opened 2024-05-28 18:39 UTC by Da-Colon

Fixes #1932 

See: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

2024-05-28 20:02 UTC, adamgall requested changes

2024-05-28 20:02 UTC, adamgall commented on src/hooks/utils/useCopyText.ts
> +      toast(t('toastClipboardCopyError'), { autoClose: 1000 });
Where da strings at

2024-05-28 20:04 UTC, adamgall commented
The implementation works for me tho

2024-05-28 20:13 UTC, Da-Colon commented on src/hooks/utils/useCopyText.ts
> +      toast(t('toastClipboardCopyError'), { autoClose: 1000 });
Yep forgot to add the copy. I'll circle back in a bit

2024-05-28 23:33 UTC, Da-Colon commented on src/hooks/utils/useCopyText.ts
> +      toast(t('toastClipboardCopyError'), { autoClose: 1000 });
would this change be acceptable, log the error for sentry and use the general error copy? As this would be an unexpected error if it were to occur.
```
logError(error);
toast(t('errorGeneral'), { autoClose: 1000 });
```

2024-05-29 12:24 UTC, adamgall commented on src/hooks/utils/useCopyText.ts
> +      toast(t('toastClipboardCopyError'), { autoClose: 1000 });
@Da-Colon I think it's appropriate to use a specific error string here, because we're capturing this specific error. Let's just add a new error string to the localization.

I'll do it and push a commit.

2024-05-29 12:28 UTC, adamgall approved these changes

2024-05-29 15:17 UTC, merged