Formik-ify more send asset modal form fields
decentdao/decent-interface pull request #1948
Opened 2024-05-29 17:35 UTC by DarksightKellar

Closes #1945 

See also: https://github.com/decentdao/decent-interface/pull/1928#discussion_r1619245208

I have chosen not to formik-ify the custom nonce input as it's got its own validation and wouldn't make sense to force that back outside to be handled by Formik/Yup

2024-05-29 17:49 UTC, adamgall commented on src/components/ui/forms/BigIntInput.tsx
> +
Oof, I get anxious when I see changes in `BigIntInput`.

Why are these changes needed?

2024-05-29 17:49 UTC, adamgall commented on src/components/ui/modals/SendAssetsModal.tsx
> +          console.log(values);
Please remove console.log

2024-05-29 17:49 UTC, adamgall commented on src/components/ui/modals/SendAssetsModal.tsx
> +          logoUri: Yup.string().required(),
Does this `logoUri` need to be here? AFAIK we don't ever take a "logo" as input from the user...

2024-05-30 11:30 UTC, DarksightKellar commented on src/components/ui/forms/BigIntInput.tsx
> +
@adamgall 
FWIW, the new optional `currentValue` is currently only set by the `SendAssetsModal`, so any regression can quickly be traced to it.

Now... for the reasoning behind this update (hopefully I don't do a crap job of explaining):

The `value` prop of `BigIntInput`'s wrapped `Input` is a string strictly for display purposes.

The `value` that Formik controls (and passes into `BigIntInput` via `{ ...field }` is instead a `BigIntValuePair`, which holds the true input data. This itself is swallowed pretty early on to set an initial `inputValue` state, never to be used again, it appears (I'm realising a potential bug here, which I'll address later).

This introduces a disconnect, as the underlying Formik `value` is never really reflected in the underlying `Input`'s `value` wrapped by `BigIntInput`. So, Formik value was getting updated just fine, but `inputValue` wasn't.

Then I noticed that `processValue` did the brunt of the work of making sure that the proper string is put into `processValue` each time the underlying `Input` triggers its `onChange`, which itself triggers the `onChange` prop passed into `BigIntInput`, which in the case of SendAssetsModal, calls formik's `setFieldValue` to update it's localised `value` state. So when the update happened because they user _typed_ into the field, all was good.

The only thing missing was if the formik `value` state is dynamically updated _outside_ the `BigIntInput`, a la `setFieldValue('inputAmount', { value: '0', bigintValue: 0n });` when selected asset changes. In this case `BigIntInput` is completely unaware that it needs to update itself. That's what this update does.

With the new `currentValue={values.inputAmount}`, whenever Formik's `values.inputAmount` is updated, _and_ the update wasn't from within `BigIntInput` (`inputValue !== currentValue?.value`), the useEffect hook is triggered. I've taken it a step further to only directly call `setInputValue` when the external update was intended to clear the input field (I experimented with calling `processValue` but concluded it was too risky).


Oh and the potential bug -- `value` prop of `BigIntInput` is a `bigint`, not `BigIntValuePair`, which is what Formik would pass into `BigIntInput`. Funny this didn't show up as a bug in my tests. I think I'll update to: 
```
{ ...field }, 
value={(field.value as BigIntValuePair)?.bigintValue}
```

2024-05-30 13:32 UTC, adamgall commented on src/components/ui/modals/SendAssetsModal.tsx
> +                          value={(field.value as BigIntValuePair)?.bigintValue}
Up above on line 140, can this be typed properly, not `FieldAttributes<any>`? I don't like the `any`.

2024-05-30 13:45 UTC, adamgall commented on src/components/ui/forms/BigIntInput.tsx
> +
Ok, I think i mostly followed that, thanks for the explanation.

I'm gonna say "ok" here and run with it.

Something on my mind though, is taking a look at these `Input` components again, and maybe cleaning them up.

I've written some pretty clean components like this for other projects, which AFAIK do the same functionality but in much simpler ways.

Checkout this `Input` component, which is made for entering "token amounts"
https://github.com/decent-labs/decent-token-vesting/blob/master/src/components/ui/Input.tsx#L43

It's used right here
https://github.com/decent-labs/decent-token-vesting/blob/master/src/components/TokenVests/New.tsx#L208

Then you can see that whenever the user changes the input of it, it results in this `BigNumber` being updated via a simple `useAmount` hook
https://github.com/decent-labs/decent-token-vesting/blob/master/src/components/TokenVests/New.tsx#L50

@decentdao/engineering does it make sense to look at how we've built these Inputs and maybe simplify them?

2024-05-30 14:06 UTC, adamgall submitted a review, later dismissed

2024-05-30 19:43 UTC, Da-Colon requested changes
I'm getting an error when I navigate to Treasury Page.

- Multisig Safe
- Treasury has `0.04 sepEther`

![image](https://github.com/decentdao/decent-interface/assets/38386583/4f8d0770-e89a-4585-8d13-1029d130390f)

2024-05-31 14:28 UTC, Da-Colon approved these changes
It loading now just fine 🤷

2024-05-31 16:18 UTC, DarksightKellar commented on src/components/ui/modals/SendAssetsModal.tsx
>    const sendAssetsValidationSchema = Yup.object().shape({
@mudrila Yeah actually you're right. You mind creating a maintenance issue for this cleanup/optimisation point?

2024-05-31 17:19 UTC, merged