`1931` Part 1: Local storage updates
decentdao/decent-interface pull request #1973
Opened 2024-06-03 14:31 UTC by Da-Colon

Works on #1931 

Makes updates Throughout app. This is for updating from the long string format for the storage key. to an "Object" key. While this is ultimately still a `string` this will allow for much better readability and adds versioning to each key (asides from having to update a few types

This is a series of 3 and I think the best way to do this is have as a draft root and then merge in as one:
- This one updates the current system to the new system. Doesn't change any values or migrate information from old keys
- Next PR: Will update favorites workflow to handle different networks
- Final PR: Will add the migration hook.

2024-06-03 20:11 UTC, Da-Colon commented on src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
> +import { getValue, setValue } from '../../../utils/cache/useLocalStorage';
Getting rid of `useLocalStorage` as it currently is. No real reason it needs to be a hook anymore

2024-06-03 20:13 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
>  }
Old types needed for Migration Hook in final PR of this series.

2024-06-03 20:13 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
>    MULTISIG_METADATA_PREFIX = 'm_m_',
Did not touch any `indexDB` implementations so left those CacheKeys in

2024-06-03 20:16 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const CURRENT_CACHE_VERSION = 1;
Hardcoded Cache Version

2024-06-03 20:16 UTC, Da-Colon commented on src/hooks/utils/cache/useLocalStorage.ts
> -};
deleted.

2024-06-04 02:20 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const CURRENT_CACHE_VERSION = 1;
At what scope is this? Is the whole cache busted at once, or can we bust the cache on individual rows in the localstorage database?

2024-06-04 03:42 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const CURRENT_CACHE_VERSION = 1;
This effects what the `setValue` and `getValue` functions.

`setValue` automatically sets to whatever this constant is set to.

`getValue` has it as a property defaulted to this constant but can be overridden (if needed).

2024-06-05 02:38 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const CURRENT_CACHE_VERSION = 1;
ok I think I get it.

so what happens when you try to `getValue` with a version greater than what lives in storage? I'll go look in the code...

2024-06-05 02:44 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const CURRENT_CACHE_VERSION = 1;
I looked in the code, I assume `getValue` in `useLocalStorage` is who I'm looking for.

There's that `version` passed in, which defaults to `CURRENT_CACHE_VERSION` like you said.

And if nothing is found for that given `version`, `return null`.

Is that the behavior we're looking for? What about the `CacheExpiry` value in the `e` field of the parsed response, how does that affect this new caching and versioning system?

2024-06-05 02:55 UTC, adamgall requested changes
Super clean implementation, I love it!

Just a couple of questions and small changes requested

2024-06-05 02:55 UTC, adamgall commented on src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
> +          contractAddress: _azoriusContract.address as Address,
use `getAddress` here please

2024-06-05 02:55 UTC, adamgall commented on src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
> +        }) as AzoriusProposal;
Might be out of scope for this PR, but can we find another way to do this? I don't like this casting.

Can we store the fact that it's an `azorius` proposal in the data itself? Then, when we `getValue` it, we confirm it has the `azorius` property and _then_ cast it somehow into an `AzoriusProposal`?

I just want to see some more validation that we have what we expect.

2024-06-05 02:55 UTC, adamgall commented on src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
> +              contractAddress: _azoriusContract.address as Address,
`getAddress` here please

2024-06-05 02:55 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +  PROPOSAL_ARCHIVE = 'Proposal',
Are these strings allowed to be formatted like this? lol

2024-06-05 02:55 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +  AVERAGE_BLOCK_TIME = 'averageBlockTime',
plz keep with convention in this enum and use `snake_case`

2024-06-05 02:55 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +  contractAddress: Address;
Are these typings enforced when doing `get/setValue`? That'd be dope.

2024-06-05 02:55 UTC, adamgall commented on src/hooks/utils/useMasterCopy.ts
> +        proxyAddress,
From my previous comment, is the typing enforced here?

2024-06-05 02:58 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const CURRENT_CACHE_VERSION = 1;
Ok so, reading through all of the code and understanding it better, it does seem like the cache is busted at the global scope, for _everything_, whenever that cache version is incremented.

What I'm getting at is: would it be beneficial to have a `version` "scoped" for each key?

So that way, when we're making changes to how Favorites work (again), we can bust the cache of _just `favorites`_, and not affect any of the other cache stores.

If there's a reason against that that you've already considered, plz share

2024-06-05 03:04 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +  contractAddress: Address;
Yep sure is.

2024-06-05 03:04 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +  AVERAGE_BLOCK_TIME = 'averageBlockTime',
🫡

2024-06-05 03:05 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +  PROPOSAL_ARCHIVE = 'Proposal',
Yep?

2024-06-05 03:19 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +  AVERAGE_BLOCK_TIME = 'averageBlockTime',
O this is part of the old keys, this is what it was original saved as. These ENUMs will be used with the migration hook I'm going to write (though I may only transfer favorites and delete everything else)

2024-06-05 03:20 UTC, Da-Colon commented on src/hooks/utils/useMasterCopy.ts
> +        proxyAddress,
Yup. Basically based on the `cacheName` property the other values will for that particular key will then be required

2024-06-05 03:21 UTC, Da-Colon commented on src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
> +        }) as AzoriusProposal;
Its more about the `getValue` func But I think I can add some typing. I'll give it a look.

2024-06-05 03:26 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const CURRENT_CACHE_VERSION = 1;
Migration to a new version shouldn't be too hard with a global value but would require some extra code for sure. But you are raising a good point, I'll think about this more.

2024-06-05 03:43 UTC, Da-Colon commented on src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
> +        }) as AzoriusProposal;
Figured it out (with a little help from the AI friend to get it right). I'll comment on the new type

2024-06-05 03:54 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +  : CacheValue;
This crazy typing right here.

Basically a conditional type. Where T extends U. if `cacheName` is in the mapping it returns that type otherwise it returns any*

*I know we hate any but not sure what else would make sense here. should never hit here

2024-06-05 04:07 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +  : CacheValue;
Could it return type `unknown`?

2024-06-05 04:12 UTC, adamgall requested changes

2024-06-05 04:12 UTC, adamgall commented on src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
> +              contractAddress: _azoriusContract.address as Address,
Wait this one too please!

2024-06-05 04:12 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +
Oh this is where the `any` is. Yeah can this be `unknown` here? Maybe that's more appropriate.

2024-06-05 04:32 UTC, adamgall approved these changes

2024-06-07 02:51 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const CURRENT_CACHE_VERSION = 1;
Ok for sure, the migration code will be fun to write.

"Favorites" are the only things we're storing "for the user", right? Everything else is a cache "for optimization" which doesn't matter if lost?

2024-06-07 02:54 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const CURRENT_CACHE_VERSION = 1;
And then finally, let's make a (potential) new PR for the (potential) code for moving the cache version down a level, from global to "per scope" of things, that we can group as we want. Don't want to include that change in the migration code, for review purposes.

2024-06-07 13:26 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const CURRENT_CACHE_VERSION = 1;
> "Favorites" are the only things we're storing "for the user", right? Everything else is a cache "for optimization" which doesn't matter if lost?

You said it better, thats correct

> And then finally, let's make a (potential) new PR for the (potential) code for moving the cache version down a level, from global to "per scope" of things, that we can group as we want.

Don't want to include that change in the migration code, for review purposes.

heard.

2024-06-10 15:16 UTC, DarksightKellar approved these changes
Lookin' good

2024-06-10 15:16 UTC, DarksightKellar commented on src/hooks/utils/cache/cacheDefaults.ts
> +  : unknown;
Wowsers

2024-06-10 15:16 UTC, DarksightKellar commented on src/hooks/utils/cache/useLocalStorage.ts
> +      JSON.stringify({ ...key, version: CURRENT_CACHE_VERSION }),
Ah I see!

2024-06-17 18:19 UTC, adamgall reviewed
In theory, has all of the code in this branch been properly reviewed?

Or, did this `issue/1931-local-storage-updates` branch have some commits before things started being merged into it?

edit: it does look like i gave this an approval already, so at some point i was happy with all of the changes in this PR already. Then, more (approved) PRs were merged into it. So yeah i guess this is good to merge then (pending design / product signoff)!

2024-06-17 18:21 UTC, Da-Colon commented
@decentdao/design @decentdao/product Ready for review. See PR description for testing todos. Let me know if anything needs to be clarified. I don't believe yall need to test the migration itself so skip that one if you want to focus in on the UI and functional updates made to favorites being cross-network

2024-06-17 18:24 UTC, Da-Colon commented
> In theory, has all of the code in this branch been properly reviewed?
> 
> Or, did this `issue/1931-local-storage-updates` branch have some commits before things started being merged into it?
> 
> edit: it does look like i gave this an approval already, so at some point i was happy with all of the changes in this PR already. Then, more (approved) PRs were merged into it. So yeah i guess this is good to merge then!

Yessir, it was all reviewed prior. Q/A on the functionality put together for Design/Product is all that is needed. (or if anyone else wants to test the migration so that it works properly.

2024-06-17 20:21 UTC, nicolaus-sherrill approved these changes
That was a delight to review after @Da-Colon's support.

2024-06-17 21:47 UTC, merged