Fix inconsistent menu hover styling
decentdao/decent-interface pull request #1974
Opened 2024-06-03 15:13 UTC by DarksightKellar

Closes #1889 

<img width="127" alt="Screenshot 2024-06-03 at 16 12 41" src="https://github.com/decentdao/decent-interface/assets/7101382/24df7736-942f-4b26-910b-fa63c1ad83ce">
<img width="310" alt="Screenshot 2024-06-03 at 16 12 49" src="https://github.com/decentdao/decent-interface/assets/7101382/445503ac-11e6-46b9-86ab-9d702f6dba3c">
<img width="289" alt="Screenshot 2024-06-03 at 16 13 01" src="https://github.com/decentdao/decent-interface/assets/7101382/c791a33f-3ad3-4dfe-8f39-4d0da6e0d7ef">
<img width="221" alt="Screenshot 2024-06-03 at 16 13 09" src="https://github.com/decentdao/decent-interface/assets/7101382/5db7472e-bb38-486e-bb06-95e409df3bdf">

2024-06-03 20:08 UTC, Da-Colon requested changes
The Favorites List, Sort Dropdown, Proposals Filter:
- MenuItems aren't picking up the text color change on hover.

2024-06-03 20:29 UTC, xraystyle1980 approved these changes

2024-06-03 20:30 UTC, xraystyle1980 commented
> The favorites list, sort dropdown, proposals filter and settings dropdown:
> 
> * MenuItems aren't picking up the text color change on hover.

*Text color does not change on menu item hover
[In Figma](https://www.figma.com/design/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?m=auto&node-id=2168-20014&t=1U7DVbWOBQZCmhow-1)

2024-06-03 20:50 UTC, Da-Colon approved these changes
My Mistake, It looks great ha!

2024-06-04 02:01 UTC, adamgall approved these changes
Approved but please see question in this review

2024-06-04 02:01 UTC, adamgall commented on src/components/ui/menus/OptionMenu/index.tsx
> +      borderRadius="0.58rem"
Is this "0.58rem" value accurate? Seems oddly unique.

2024-06-04 09:22 UTC, tomstuart123 approved these changes
looks good

2024-06-04 09:56 UTC, DarksightKellar commented on src/components/ui/menus/OptionMenu/index.tsx
> +      borderRadius="0.58rem"
Ah yes, you're right in that it's uncomfortably unique. I'd meant to comment on this with screenshots. Unfortunately I'm not at my desk today so I'll try to describe with words:

I've noticed in general that when there's a box-within-border setup, both require a border radius, otherwise the inside box non-rounded corners overflow the rounded border edges. Buut simply using the same border radius value causes the inner container corner to "pull away" from the border corner, leaving visible gaps on all rounded corners.

(I think it's just a limitation of the math of circles and the fact that technically there're different radii involved.)

There's been one other instance I've encountered this problem, but it was only barely noticeable when zoomed in. So I was fine leaving as-is.

In this case though, it was too ugly to leave alone, so I've forced the inner container curve to "stretch" out to touch the outer border curve.

2024-06-04 09:57 UTC, merged

2024-06-05 03:27 UTC, adamgall commented on src/components/ui/menus/OptionMenu/index.tsx
> +      borderRadius="0.58rem"
I understand what you're saying, but I'm still stuck on it... I know this code is merged already but I wonder if there's something weird about the HTML structure.