[DRAFT] `1710` Part 2: Cross network favorites
decentdao/decent-interface pull request #1975
Opened 2024-06-03 16:05 UTC by Da-Colon

Fixes #1710

Kinda a weird one to fit in the middle but wanted this work to be done prior to the Local Storage migration actually is done so that the typing is setup.

This PR handles adding the network prefix to the cached favorite string. It also adds some helper functions to get the network prefix and chain id via the network prefix to allow for the UI around the favorites.

2024-06-03 20:19 UTC, Da-Colon commented on src/utils/url.ts
> +};
This is the main part of this update. Added helper functions to help get/retrieve the prefix and icons for given chainId. If there is more scaleable way to do this by using the information in `NetworkConfig` files, I'm open to suggestions.

2024-06-04 02:15 UTC, adamgall commented on src/utils/url.ts
> +};
We do already store the network prefix strings and network icons in the `NetworkConfig` files, so we need to find a way to reuse those, not duplicate them here. It will be no bueno if we'll be required to remember to come update this file when a new network is added.

2024-06-04 04:02 UTC, Da-Colon commented on src/utils/url.ts
> +};
Yeah I didn't feel good about it. I'll take another look.

2024-06-04 05:10 UTC, Da-Colon commented on src/utils/url.ts
> +};
oof should have done this to begin with. throws when network isn't found (it shouldn't ever throw)

2024-06-05 03:09 UTC, Da-Colon commented
Found a much better solution. (kinda a duh. moment). 

Soo. one thing is missing here. pulling the DAO's name on a different network. I have it almost setup but the last thing is targeting the right registry contract. I tried to find a way to make this work but ultimately I started rubbing up against the updates @adamgall is making in the typechain rework. I need those updates ha! then this will be a piece of cake.

2024-06-05 03:11 UTC, Da-Colon commented on src/hooks/utils/useDisplayName.ts
> +const useDisplayName = (account?: string | null, truncate?: boolean, chainId?: number) => {
I would prefer these args be an object but didn't want to fill up this review with this change to all the other files

2024-06-05 03:22 UTC, adamgall requested changes
Nice work here, I have a couple of questions n comments

2024-06-05 03:22 UTC, adamgall commented on src/components/ui/icons/FavoriteIcon.tsx
> +    [favoritesList, safeAddress, addressPrefix],
This line is stumping me, but probably just because it's the first thing I'm looking at and have no context yet.

But it's stumping me because this doesn't look like cross-network-friendly code. Looks like it'll only truthy `isFavorite` if the given address is a favorite _on the current network_.

2024-06-05 03:22 UTC, adamgall commented on src/components/ui/menus/SafesMenu/SafeMenuItem.tsx
> +    }
Okkkkk I see u

2024-06-05 03:22 UTC, adamgall commented on src/components/ui/menus/SafesMenu/SafesList.tsx
> +                address={favorite.split(':')[1]}
We need to do some validation on this _user input_ before attempting to use it like this. Otherwise it'll throw when someone ruins a favorite in localstorage and Sentry will yell at us

2024-06-05 03:22 UTC, adamgall commented on src/components/ui/menus/SafesMenu/SafeMenuItem.tsx
> +    undefined,
Just say `false` here plz

2024-06-05 03:22 UTC, adamgall commented on src/pages/home/SafeDisplayRow.tsx
> +    undefined,
Just say `false` here plz

2024-06-05 03:22 UTC, adamgall commented on src/components/ui/menus/SafesMenu/SafesList.tsx
> +                address={favorite.split(':')[1]}
Ooh better yet, can we get a dedicated set of functions to "encode" and "decode" an object `{ network: "eth", address: "0x123 }` into a string of format `eth:0x123`

And those functions do our validation

2024-06-05 03:22 UTC, adamgall commented on src/pages/home/AllSafesDrawer.tsx
> +              network={favorite.split(':')[0]}
This would be another place where some validation would be good.

2024-06-05 03:22 UTC, adamgall commented on src/pages/home/MySafes.tsx
> +                network={favorite.split(':')[0]}
And here

2024-06-05 03:22 UTC, adamgall commented on src/pages/home/SafeDisplayRow.tsx
> +    chainId: getChainIdFromPrefix(network),
If this throws, do we want to catch it in here?

2024-06-05 03:22 UTC, adamgall commented on src/pages/home/SafeDisplayRow.tsx
> +    getChainIdFromPrefix(network),
If this throws, do we want to catch it in here?

2024-06-05 03:22 UTC, adamgall commented on src/pages/home/SafeDisplayRow.tsx
> +          <Text>{getChainName(network)}</Text>
What happens when these throw?

2024-06-05 03:22 UTC, adamgall commented on src/utils/url.ts
> +  return `${network?.addressPrefix}:${address}`;
Do you need the `?` on this `network`?

2024-06-05 03:22 UTC, adamgall commented on src/utils/url.ts
> +  return network?.nativeTokenIcon;
Do you need the `?`?

2024-06-05 03:22 UTC, adamgall commented on src/utils/url.ts
> +    throw new Error(`No network found for chainId ${_networkPrefix}`);
This error should say `No chain found for network blah`

2024-06-05 03:22 UTC, adamgall commented on src/utils/url.ts
> +    throw new Error(`No network found for chainId ${_networkPrefix}`);
`No chainId found for network prefix blah`

2024-06-05 04:18 UTC, Da-Colon commented on src/components/ui/icons/FavoriteIcon.tsx
> +    [favoritesList, safeAddress, addressPrefix],
The `FavoriteIcon` component is now only being used on the DAO Dashboard and Organization Pages which are network specific. I've removed this from the Favorites menu (with Design's permission)

2024-06-05 04:18 UTC, Da-Colon commented on src/components/ui/menus/SafesMenu/SafesList.tsx
> +                address={favorite.split(':')[1]}
Woot I did it. I'll point out the two function

2024-06-05 04:20 UTC, Da-Colon commented on src/utils/address.ts
> +};
This what you mean? @adamgall

2024-06-05 04:20 UTC, Da-Colon commented on src/pages/home/AllSafesDrawer.tsx
> +              {...decodePrefixedAddress(favorite)}
Do you have a preference about doing it like this?

2024-06-05 04:20 UTC, adamgall requested changes

2024-06-05 04:20 UTC, adamgall commented on src/utils/address.ts
> +};
Ok yes! This is a great start, but I also wanted to see some validation in here.

Like, `addressWithoutPrefix` will be `undefined` if `address` doesn't contain a "`:`".

2024-06-05 04:20 UTC, adamgall commented on src/pages/home/AllSafesDrawer.tsx
> +              {...decodePrefixedAddress(favorite)}
I'm cool with this

2024-06-05 04:21 UTC, adamgall commented on src/utils/address.ts
> +};
Yes it's the start of what I meant!

2024-06-05 04:21 UTC, Da-Colon commented
As far as the throw errors. I don't believe it will EVER hit here. Unsupported networks are caught way up the food chain. I did this more or less so I didn't have to type our a `null` or `undefined`. Since these settings come from hardcoded settings it shouldn't ever throw

2024-06-05 04:22 UTC, adamgall commented on src/components/ui/icons/FavoriteIcon.tsx
> +    [favoritesList, safeAddress, addressPrefix],
Ooo ok that makes sense

2024-06-05 04:23 UTC, Da-Colon commented on src/utils/address.ts
> +};
ah I see. wanted a clean return instead of `undefined` but I can do that.

2024-06-05 04:30 UTC, adamgall commented on src/utils/address.ts
> +};
I think if you `throw` it doesn't add `undefined` to the return type

2024-06-05 04:31 UTC, adamgall commented
> As far as the throw errors. I don't believe it will EVER hit here. Unsupported networks are caught way up the food chain. I did this more or less so I didn't have to type our a `null` or `undefined`. Since these settings come from hardcoded settings it shouldn't ever throw

Which comment was this in reference to?

2024-06-05 04:34 UTC, Da-Colon commented
> > As far as the throw errors. I don't believe it will EVER hit here. Unsupported networks are caught way up the food chain. I did this more or less so I didn't have to type our a `null` or `undefined`. Since these settings come from hardcoded settings it shouldn't ever throw
> 
> Which comment was this in reference to?

![image](https://github.com/decentdao/decent-interface/assets/38386583/c3891caf-9c66-49ce-9c62-c24f6c62fe9a)


these comments

2024-06-10 18:58 UTC, DarksightKellar requested changes
Looking good here too! Had a couple thoughts in the review, if you could check 'em out

2024-06-10 18:58 UTC, DarksightKellar commented on src/pages/home/SafeDisplayRow.tsx
> +          <Text>{getChainName(network)}</Text>
I feel like these (and `getChainIdFromPrefix` usage above) could be wrapped a `useMemo`, where we could gracefully handle exceptions and return some acceptable default/error data.

2024-06-10 20:55 UTC, Da-Colon commented on src/utils/address.ts
> +    address: addressWithoutPrefix,
hmm. Might be overhead for this PR. as the address it returns goes through `getAddress` function where its used else where. so would doubling up

2024-06-10 21:00 UTC, Da-Colon commented
> I feel like these (and getChainIdFromPrefix usage above) could be wrapped a useMemo, where we could gracefully handle exceptions and return some acceptable default/error data.

So similar to my answer to @adamgall is this should never throw here. As the app won't let you connect to a network that isn't supported and since we are directly using the same configuration files.

So IMO, its not needed. But if yall (@adamgall had similar thoughts) are not satisfied with my answer and can figure out the changes needed to make this happen, Though hard to test since the app itself won't let you switch to an unsupported network. 

![image](https://github.com/decentdao/decent-interface/assets/38386583/69f84fa5-d054-4e95-9efe-646c1c806722)

2024-06-10 21:12 UTC, adamgall commented
> > I feel like these (and getChainIdFromPrefix usage above) could be wrapped a useMemo, where we could gracefully handle exceptions and return some acceptable default/error data.
> 
> 
> 
> So similar to my answer to @adamgall is this should never throw here. As the app won't let you connect to a network that isn't supported and since we are directly using the same configuration files.
> 
> 
> 
> So IMO, its not needed. But if yall (@adamgall had similar thoughts) are not satisfied with my answe, then I can figure out the changes needed to make this happen, Though hard to test since the app itself won't let you switch to an unsupported network. 
> 
> 
> 
> ![image](https://github.com/decentdao/decent-interface/assets/38386583/69f84fa5-d054-4e95-9efe-646c1c806722)
> 
>  

Try/catching errors like this (ones that we know "should never happen") are precisely the point.

I'd like us to get into the habit of building more bulletproof code.

If there's a possibility for a line of code to throw (when evaluating it without any extra context) (and there is in this instance) let's catch it and bubble it up.

2024-06-11 19:57 UTC, adamgall commented
@Da-Colon j/w, do you plan on doing anything more with this PR? https://decentdao.slack.com/archives/C06QZ68L5SA/p1718121588983869

2024-06-11 20:34 UTC, Da-Colon commented
> @adamgall Yessir. I'm creating a
> 
> Placing an error Boundary with a Fallback UI, around Where this might fail.
> 
> ![localhost_3005_(Desktop)](https://private-user-images.githubusercontent.com/38386583/338735800-2a0f0c22-97f4-4799-8083-bc7d63426c81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzc4OTAsIm5iZiI6MTcxODEzNzU5MCwicGF0aCI6Ii8zODM4NjU4My8zMzg3MzU4MDAtMmEwZjBjMjItOTdmNC00Nzk5LTgwODMtYmM3ZDYzNDI2YzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDIwMjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZjM1YWEzYjVjMjYwNTBmODk4MmQ3ZDZiNDNhZDBlZjNmOTVmYzllZmFjNjU3ZGVlYzdhMjEyMGY2ZmE4MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CrPoFYOi0RQ2S_aeHgjhXn4FCZ1Uys_hariK8Hm8WbY)

@decentdao/product @decentdao/design Yall good with the look and copy?

2024-06-11 20:35 UTC, Da-Colon commented
@DarksightKellar I didn't add the `useMemo` as suggested with the error boundary this handles this error as is

2024-06-12 10:50 UTC, DarksightKellar approved these changes
> @DarksightKellar I didn't add the `useMemo` as suggested with the error boundary this handles this error as is, wdyt?
 

@Da-Colon Yhup, me likey.

2024-06-12 13:36 UTC, adamgall approved these changes

2024-06-12 14:44 UTC, merged