`1930` local storage version control
decentdao/decent-interface pull request #1984
Opened 2024-06-08 20:01 UTC by Da-Colon

Noticed that I missed the Average Block Time so added that here.

2024-06-08 20:02 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +};
Is this kinda what you are thinking?  @adamgall

2024-06-10 13:27 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +      return MASTER_CACHE_VERSION;
Good call

2024-06-10 13:28 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> + * @todo: The CACHE_DEFAULTs seem to be used for indexDB, But favorites is localstorage. We will need to revisit this.
Yeah 100% Another series can take a look at cleaning up indexDB in the future

2024-06-10 13:28 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +    case CacheKeys.PROPOSAL_ARCHIVE:
updated.

2024-06-10 15:25 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const AVERAGE_BLOCK_TIME_CACHE_VERSION = 1;
Do these need to be exported?

2024-06-10 15:43 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +export const AVERAGE_BLOCK_TIME_CACHE_VERSION = 1;
fair

2024-06-10 19:29 UTC, DarksightKellar requested changes

2024-06-10 19:29 UTC, DarksightKellar commented on src/hooks/utils/cache/cacheDefaults.ts
> +};
Could you combine above into sth like a constant `mapCacheNameToVersion`?

2024-06-10 19:29 UTC, DarksightKellar commented on src/hooks/utils/cache/cacheDefaults.ts
> + * @todo: The CACHE_DEFAULTs seem to be used for indexDB, But favorites is localstorage. We will need to revisit this.
Seconded. Uh, thirded?

2024-06-11 20:03 UTC, adamgall commented on src/hooks/utils/cache/cacheDefaults.ts
> +};
@DarksightKellar I don't follow what you're suggesting here...

2024-06-11 20:07 UTC, adamgall requested changes
`export enum CacheKeysV0 { ...` looks unused, can remove?

2024-06-11 21:57 UTC, Da-Colon commented
> `export enum CacheKeysV0 { ...` looks unused, can remove?

I was going keeping this around for the next PR's migration. But I don't think I really need it since I'm only going to migrate the Favorites. I'll remove this in the next PR.

2024-06-12 05:25 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +};
You mean like this? (Taking a guess)
```js
const CACHE_VERSIONS: { [key: string]: number } = {
  [CacheKeys.FAVORITES]: 1,
  [CacheKeys.MASTER_COPY]: 1,
  [CacheKeys.PROPOSAL_CACHE]: 1,
  [CacheKeys.AVERAGE_BLOCK_TIME]: 1,
};

export const getCacheVersion = (cacheName: CacheKeys): number => {
  const version = CACHE_VERSIONS[cacheName];
  if (version === undefined) {
    throw new Error('Invalid cache name');
  }
  return version;
};
```

(In lastest commit)

2024-06-12 11:47 UTC, DarksightKellar commented on src/hooks/utils/cache/cacheDefaults.ts
> +};
I was thinking more like:

```
export const CACHE_VERSIONS = {
  [CacheKeys.FAVORITES]: 1,
  [CacheKeys.MASTER_COPY]: 1,
  [CacheKeys.PROPOSAL_CACHE]: 1,
  [CacheKeys.AVERAGE_BLOCK_TIME]: 1,
};


// elsewhere:
const favsCacheVersion = CACHE_VERSIONS[CacheKeys.FAVORITES]
```

So we can get rid of `getCacheVersion` and not have to do dynamic error checking, as inferred typing will prevent `CACHE_VERSIONS['invalidKey']` in the first place.

2024-06-12 13:12 UTC, Da-Colon commented on src/hooks/utils/cache/cacheDefaults.ts
> +};
I was sooo close ha. Coolio updated and pushed sir.

2024-06-12 13:20 UTC, DarksightKellar approved these changes
Noice!

2024-06-12 13:20 UTC, adamgall approved these changes

2024-06-12 15:42 UTC, merged