Fix token import supply allowing alphanumeric input
decentdao/decent-interface pull request #1988
Opened 2024-06-11 09:09 UTC by DarksightKellar

Closes #1981

2024-06-11 20:36 UTC, adamgall approved these changes

2024-06-12 05:10 UTC, Da-Colon approved these changes

2024-06-12 13:36 UTC, tomstuart123 commented
No need to wait for my review here as the original comment seems very dev/code focused.

2024-06-12 15:37 UTC, adamgall commented
@tomstuart123 , if you do have time, would be good to have Product signoff on this.

When creating DAO, importing existing token:
- on develop right now, can input alpha characters
- on this PR, should only be able to input numeric characters

2024-06-14 15:31 UTC, tomstuart123 commented
Nice, token supply # is now non-editable. Thanks @DarksightKellar .

One design thought: 
--> If it can't be edited, shouldn't it be greyed out for the user? 
![Screenshot 2024-06-14 at 16 31 10](https://github.com/decentdao/decent-interface/assets/31554133/4a5e9738-328b-444b-b57f-a37809879646)

--> E.g. similar to when we modify governance of a safe and the user can't change a safeName
![Screenshot 2024-06-14 at 16 29 14](https://github.com/decentdao/decent-interface/assets/31554133/1f05b696-9372-4638-b069-54992123beac)

2024-06-14 16:00 UTC, adamgall requested changes

2024-06-14 16:00 UTC, adamgall commented on src/components/DaoCreator/formComponents/VotesTokenImport.tsx
> +          readOnly
Agree with @tomstuart123 that this should make the input _look_ disabled

2024-06-14 18:44 UTC, adamgall approved these changes
i'll give this a quick approval from the code-review pov.

i haven't opened the app about it yet though so @tomstuart123 can you do that side?

2024-06-14 19:12 UTC, tomstuart123 commented
Looks good to me, thanks @DarksightKellar 

<img width="639" alt="Screenshot 2024-06-14 at 20 10 59" src="https://github.com/decentdao/decent-interface/assets/31554133/d88324b2-119e-4305-af78-8f27306ba232">

2024-06-14 19:13 UTC, tomstuart123 approved these changes

2024-06-14 19:16 UTC, merged