1558-execution-button-delay
decentdao/decent-interface pull request #1990
Opened 2024-06-11 18:12 UTC by DarksightKellar

Closes #1558

This PR patches up the time delay between when the app indicates a proposal timelock and/or execute transaction has been successfully ran and when the data actually indicates as much.

We have achieved this by simply keeping the execute button disabled after the success toast. If the user chooses to stay on the screen, eventually the node data will be updated, and the button will disappear.

In the case of timelock, the button will re-enable itself after timelock when the proposal becomes executable.

I expect, if the user refreshes the page in that small window where the node hasn't reflected the updated proposal state, the button will then be clickable -- not much we can do in that case beyond localstorage caching, which we _have_ discussed. Problem is multisig safe proposals are currently not cached as they're loaded all at once every time, and choosing to selectively cache them will take a bit more thought. 

There's a separate task for this caching [here](https://github.com/orgs/decentdao/projects/32/views/3?pane=issue&itemId=65769569), if we end up deciding it's something worth doing.

2024-06-11 20:38 UTC, adamgall commented
My take is that trying to handle that small timeframe window of a user potentially refreshing the page, using some local storage caching, is way overkill.

2024-06-11 20:55 UTC, adamgall requested changes
@DarksightKellar can you please follow this up with a PR to address the various `@todo`s you created for the names of various types/interfaces/properties?

2024-06-11 20:55 UTC, adamgall commented on src/components/Proposals/MultisigProposalDetails/TxActions.tsx
> +  let wasTimelocked = useRef(
`const`, no?

2024-06-11 20:55 UTC, adamgall commented on src/components/Proposals/MultisigProposalDetails/TxActions.tsx
> +          setIsSubmitDisabled(true);
Do we maybe want to set this property when the user initially clicks the "execute" button? or does it need to be in this `successCallback` for a specific reason?

2024-06-11 20:55 UTC, adamgall commented on src/components/Proposals/MultisigProposalDetails/TxActions.tsx
> +          loadSafeMultisigProposals();
Doesn't this call to `loadSafeMultisigProposals` need to be `async`?

2024-06-11 20:55 UTC, adamgall commented on src/hooks/DAO/loaders/useLoadDAOProposals.ts
>        setMethodOnInterval(loadSafeMultisigProposals);
Doesn't this call to `loadSafeMultisigProposals` need to be `async`?

2024-06-12 09:27 UTC, DarksightKellar commented on src/components/Proposals/MultisigProposalDetails/TxActions.tsx
> +  let wasTimelocked = useRef(
`const`, yep

2024-06-12 09:33 UTC, DarksightKellar commented on src/components/Proposals/MultisigProposalDetails/TxActions.tsx
> +          setIsSubmitDisabled(true);
This was to account for potential errors (after which the button would need to be "re-enabled"). This way only successful executes would actually disable the button.

2024-06-12 09:54 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useLoadDAOProposals.ts
>        setMethodOnInterval(loadSafeMultisigProposals);
Eh I didn't think so at first, but I suppose in `setMethodOnInterval`'s first-time ran line `returnValue = await Promise.resolve(getMethod());`, awaiting the call will actually wait for `loadSafeMultisigProposals` to complete?

2024-06-12 13:34 UTC, tomstuart123 commented
Nice @DarksightKellar / @adamgall .

I tested this with the same childSafe [here ](https://deploy-preview-1990.app.dev.decentdao.org/home?dao=sep:0x773eC5B85aebAa323e700E9bbAA7Cb2eFeAdf56F)where I was originally having issues. The timelock and execute button remained greyed out during the process after click/tx.


Approved

2024-06-12 13:34 UTC, tomstuart123 approved these changes

2024-06-12 13:44 UTC, adamgall commented
@DarksightKellar i fixed the merge conflict and pushed, fyi

2024-06-12 13:45 UTC, adamgall approved these changes

2024-06-12 14:05 UTC, adamgall commented
@DarksightKellar does this PR address #1511 also?

2024-06-12 14:19 UTC, Da-Colon commented
> @DarksightKellar does this PR address #1511 also?

It helps it for sure but doesn't 'fix' it. With this fix relies on the user not refreshing, right? The button would reappear at that point able to be pushed?

2024-06-12 14:30 UTC, DarksightKellar commented
> > @DarksightKellar does this PR address #1511 also?
> 
> It helps it for sure but doesn't 'fix' it. With this fix relies on the user not refreshing, right? The button would reappear at that point able to be pushed?

@Da-Colon I had the same observation. See my comment on this: 
> I expect, if the user refreshes the page in that small window where the node hasn't reflected the updated proposal state, the button will then be clickable -- not much we can do in that case beyond localstorage caching, which we have discussed. Problem is multisig safe proposals are currently not cached as they're loaded all at once every time, and choosing to selectively cache them will take a bit more thought.
> There's a separate task for this caching [here](https://github.com/orgs/decentdao/projects/32/views/3?pane=issue&itemId=65769569), if we end up deciding it's something worth doing.

And @adamgall's take:
> My take is that trying to handle that small timeframe window of a user potentially refreshing the page, using some local storage caching, is way overkill, and not something we need to try to solve for.

which I'm inclined to agree with. It's such a uniquely specific, yet non-breaking flow, that solving for it specifically using caching feels overkill. If we agree that caching multisig safe proposals _is_ worth doing though (I can't argue for it atp), then this will sort itself out as a side effect.

2024-06-12 14:39 UTC, Da-Colon commented
> @Da-Colon @DarksightKellar so is #1511 related to the button re-appearing only after immediately refreshing after it was executed the first time?
> 
> If so, I'd say we can close #1511 as a wontfix

Coolio I agree with that

2024-06-12 18:57 UTC, merged