`1931` local storage migration
decentdao/decent-interface pull request #1996
Opened 2024-06-13 02:49 UTC by Da-Colon

Fixes #1931 

End of Series.

This adds the hook `useMigrateLocalStorageV1` Which is placed inside the `Providers` component (at top of tree).

This hook is called when keys that include `fract_` for V1 are found. filters for Favorites and combines the networks into a single favorites cache adding the network prefix for network of the favorite.

It then removes all old `fract_` keys from local storage clearing out the old cache. 

## Thoughts
I thought about adding a `V1_MIGRATION`: true to local storage then use that to make sure this didn't run after running. but felt the search for `fract_` should handle this. Thoughts?

2024-06-13 02:51 UTC, Da-Colon commented
@decentdao/engineering Since this is kinda hard to test (I guess you can add a old favorite cache manually in the deploy preview), I added a test and some test cases for it to make sure this works as expected

2024-06-13 14:50 UTC, adamgall reviewed
Two pieces of feedback, which seem in line with your thoughts too:

1. Yes, let's set up the structure now for multiple migrations. I do think adding a "migration version" to local storage is a good idea at this point.
2. Just a bit more abstraction please:
   - `useMigrate` hook
   - the `useMigrate` hook checks for existence of "migration version" value
     - if no value exists
       - run the `v1` migration
       - set "migration version" to `1`
     - if it does exist and is >= `1`, don't run the `v1` migration

2024-06-13 21:58 UTC, Da-Colon commented
> Two pieces of feedback, which seem in line with your thoughts too:
> 
> 1. Yes, let's set up the structure now for multiple migrations. I do think adding a "migration version" to local storage is a good idea at this point.
> 2. Just a bit more abstraction please:
>    
>    * rename the hook used in `Providers` to `useMigrate`
>    * the `useMigrate` hook checks for existence of "migration version" value
>      
>      * if no value exists
>        
>        * run the `v1` migration
>        * set "migration version" to `1`
>      * if it does exist and is >= `1`, don't run the `v1` migration

Great ideas, I'll get on it.

2024-06-14 14:43 UTC, DarksightKellar approved these changes

2024-06-14 14:59 UTC, adamgall requested changes

2024-06-14 14:59 UTC, adamgall commented on src/hooks/utils/cache/useMigrate.ts
>  export function migrateCacheToV1(): boolean {
Does this need to be `export`ed to be accessible to the test?

2024-06-14 14:59 UTC, adamgall commented on src/hooks/utils/cache/useMigrate.ts
> +  if (cacheVersion && cacheVersion === CACHE_VERSIONS[CacheKeys.MIGRATION]) {
I think this should be `>=` (or `>==`?), not `===`. Think about the second migration

2024-06-14 14:59 UTC, adamgall commented on src/hooks/utils/cache/useMigrate.ts
> +  }
Also, I think this code here should be _outside_ of the specific `v1 migration` function. Let the layer above this one decide which migration functions to call.

2024-06-14 14:59 UTC, adamgall commented on src/hooks/utils/cache/useMigrate.ts
> +    setValue({ cacheName: CacheKeys.MIGRATION }, CACHE_VERSIONS[CacheKeys.MIGRATION]);
Same idea as previous comment: let the layer above this function decide which migration version to set into local storage.

2024-06-14 14:59 UTC, adamgall commented on src/hooks/utils/cache/useMigrate.ts
> +  setValue({ cacheName: CacheKeys.MIGRATION }, CACHE_VERSIONS[CacheKeys.MIGRATION]);
ditto

2024-06-14 15:33 UTC, Da-Colon commented on src/hooks/utils/cache/useMigrate.ts
>  export function migrateCacheToV1(): boolean {
correct

2024-06-14 15:35 UTC, Da-Colon commented on src/hooks/utils/cache/useMigrate.ts
> +    setValue({ cacheName: CacheKeys.MIGRATION }, CACHE_VERSIONS[CacheKeys.MIGRATION]);
I think I need to push back a little on this. 

two part. I never imagined that this migration would stay in the codebase forever. I was thinking after a month or two (or longer) this migration is removed. 

The other part, if we did want to leave it in. I agree I can move this conditional outside, but the `setValue` should be in the V1 function

2024-06-14 16:01 UTC, adamgall commented on src/hooks/utils/cache/useMigrate.ts
> +    setValue({ cacheName: CacheKeys.MIGRATION }, CACHE_VERSIONS[CacheKeys.MIGRATION]);
oh snap, yeah, i imagined that these migrations would live here forever.

why should the `setValue` live in this `v1` function rather than the "controller" above it?

2024-06-14 17:25 UTC, adamgall requested changes

2024-06-14 17:25 UTC, adamgall commented on src/hooks/utils/cache/useMigrate.ts
> +        logError(e)
Let's put `const migration = require(`./migrations/${i}`);` into this try/catch too, and write a test for it (malformed / missing filenames).

2024-06-14 17:25 UTC, adamgall commented on test/migrateCacheToV1.test.ts
I don't see it here yet, but I'd like to see separate tests for testing the `runMigrations` function specifically.

2024-06-14 23:27 UTC, Da-Colon commented on test/runMigration.test.ts
> +  });
Do you want to see anything else in these tests? I don't believe there is much else to test here unless I change to be able to pass in the version as a param (defaulted to latest) that would allow me to play with the current version. @adamgall

2024-06-14 23:32 UTC, adamgall commented
@Da-Colon now that we have a directory full of standard-ly named files, do we even need that "current migration variable"? Can't we just assume it's whatever the largest migration file is?

2024-06-15 00:44 UTC, Da-Colon commented
> @Da-Colon now that we have a directory full of standard-ly named files, do we even need that "current migration variable"? Can't we just assume it's whatever the largest migration file is?

hmmm now thats a thought, I'll give it a go

2024-06-15 05:24 UTC, adamgall requested changes

2024-06-15 05:24 UTC, adamgall commented on src/hooks/utils/cache/useMigrate.ts
> +    const migration = await import(`./migrations/${i}`);
Move this line into the `try`, please. Then, I'd like to see a test that had malformed migration filenames and/or gaps in the numbers

2024-06-16 04:35 UTC, Da-Colon commented
@adamgall Phew. Okay. I realized that I was attempting to use the filesystem (`fs`) which won't be available in the frontend environment. I considered using a `migrations/index` to get the file count but didn't like that extra overhead. After some soul searching I discovered `import.meta.glob` which allows you to dynamically import multiple modules based on glob patterns. This gets us the count we need.

The next problem is that this isn't `mockable` and since its compiled at runtime can't override it. So added a param for migrationCount that is defaulted to the globs key length, this allows me to now only mock the files in the test but pass in the count for the loop. 

tests have been added.

2024-06-17 02:00 UTC, adamgall requested changes
Love the tests. Have one question about a small thing, but otherwise looks great

2024-06-17 05:15 UTC, Da-Colon commented on src/hooks/utils/cache/useMigrate.ts
> +      setValue({ cacheName: CacheKeys.MIGRATION }, migrationCount);
That is correct. left in a change during testing. Updated that. I also went ahead and removed the localStorage update from the loop. I'd rather do that once on a success or failure. 

I also went ahead and added another test for the `runMigration` button for a successful run (only had error states tested).

2024-06-17 14:29 UTC, adamgall requested changes
Found a bug or two.

---

And then I have yet other idea about the migration code. should it perform some self-tests?

// dev: as i wrote out the below, proper implementation became more unrealistic with each line. keeping for posterity, but these are just the ramblings of a dreamer for now

For example, consider each migration file was split into 4 distinct steps.

1. gather all relevant source data
2. use the source data to CREATE NEW keys only. NEVER modify existing localstorage keys or values in this step.
3. run tests... make sure new data looks like it should look like, considering the source data.
  a. if the tests don't pass then throw an error or something. DON'T DELETE source data or the invalid new data.
  b. if they do pass, update migration

2024-06-17 14:29 UTC, adamgall commented on src/hooks/utils/cache/migrations/1.ts
> +    setValue({ cacheName: CacheKeys.FAVORITES }, newFavorites);
This puts an expiration of 1 week on the new favorites. OOPSIE

2024-06-17 14:29 UTC, adamgall commented on src/hooks/utils/cache/migrations/1.ts
> +    setValue({ cacheName: CacheKeys.FAVORITES }, newFavorites);
We have both:

"user preferences" and "temporary disposable cache data"

being shoehorned into the same constructs, which I've been pointing out.

This is an example of an unexpected bug (consumer being _unaware_ of a very "cache-specific" optional default parameter value to `setValue`) arising due to that shoehorning of two separate things into one system.

I'm just saying this to say it at this point, we don't need to do anything about the content of this message, in this PR.

other than adding `expire: NEVER` to this `setValue` call....and the `MIGRATION setValue` too!

2024-06-17 14:48 UTC, adamgall requested changes

2024-06-17 14:48 UTC, adamgall commented on src/hooks/utils/cache/useMigrate.ts
> +};
So, considering that this will be code that executes every time in its entirety each time the app loads in a browser, I think we should early exit as soon as possible, and not perform that `setValue` at the end.

We just want that last `setValue` line to be executed one time per-browser-per-migration.

2024-06-17 14:48 UTC, adamgall commented on src/hooks/utils/cache/migrations/1.ts
> +  }
Can safely remove this early exit if you'd like.

I think the migration one-time-use code looks nicer without that early exit tbh.

2024-06-17 14:48 UTC, adamgall commented on test/migrations.test.ts
> +    }
can delete

2024-06-17 14:48 UTC, adamgall commented on test/migrations.test.ts
> +    }
can delete

2024-06-17 14:48 UTC, adamgall commented on test/migrations.test.ts
> +    }
can delete

2024-06-17 14:48 UTC, adamgall commented on test/migrations.test.ts
> +    }
can delete

2024-06-17 14:48 UTC, adamgall commented on test/migrations.test.ts
> +    }
can delete

2024-06-17 14:49 UTC, adamgall requested changes

2024-06-17 14:49 UTC, adamgall commented on test/migrations.test.ts
> +  });
```ts
  it('should successfully migrate to the latest version', async () => {
    const migrationCacheBefore = getValue({ cacheName: CacheKeys.MIGRATION });
    expect(migrationCacheBefore).toBe(null);

    await runMigrations(3);

    const migrationCacheAfter = getValue({ cacheName: CacheKeys.MIGRATION });
    expect(migrationCacheAfter).toBe(3);
  });
```

2024-06-17 15:08 UTC, adamgall commented
@Da-Colon i'm pushing one commit. then i'm good with merging 👍

2024-06-17 15:20 UTC, adamgall requested changes
It doesn't seem to work any longer

<img width="1432" alt="Screenshot 2024-06-17 at 11 19 54 AM" src="https://github.com/decentdao/decent-interface/assets/706929/a800bcb7-9b70-47de-86fa-32feac03abf6">

2024-06-17 18:16 UTC, merged