Add indicator for pending proposal
decentdao/decent-interface pull request #1998
Opened 2024-06-13 17:39 UTC by DarksightKellar

This PR temporarily caches recently created proposal data (transaction hash and metadata). The application can then read this cache and indicate to the user that there are pending proposals waiting to be shown on the UI when ready.

The cached proposal is removed when proposals are loaded and any of them has a transaction hash that matches its transaction hash.

Pending toast:
<img width="1306" alt="Screenshot 2024-06-13 at 18 01 24" src="https://github.com/decentdao/decent-interface/assets/7101382/80f6c8e0-ca5c-41d9-b6cd-ce2cb27a8c8e">

Toast dismissed when proposal shows up:
<img width="1295" alt="Screenshot 2024-06-13 at 18 01 43" src="https://github.com/decentdao/decent-interface/assets/7101382/0f40d9f9-0189-41d2-9416-c0e65a89efda">

Note: the toast is a temporary workaround while waiting on @decentdao/design to finalise the actual look for pending proposal(s) UI.

closes #1983

2024-06-13 18:42 UTC, nicolaus-sherrill commented
@DarksightKellar are you thinking that this would be a new card added to the top of the list that communicates "this is temporary until your actual proposal is visible"?

2024-06-13 18:48 UTC, DarksightKellar commented
> @DarksightKellar are you thinking that this would be a new card added to the top of the list that communicates "this is temporary until your actual proposal is visible"?

@nicolaus-sherrill Yep, I had 2 options in mind:

- a single new card that communicates that one or more proposals are pending

- a new _list_ that shows basic data for each pending proposal. These won't be clickable, of course

This PR's set up for both, so that won't be an issue, just need to decide which is better UX

2024-06-14 12:19 UTC, Da-Colon requested changes
a few minor comments

2024-06-14 12:19 UTC, Da-Colon commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +          });
I don't think this should be inside this conditional? whether a `successCallback` func is passed in doesn't matter to the success of the creation of the proposal, right?

2024-06-14 12:19 UTC, Da-Colon commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +          successCallback(addressPrefix, safeAddress);
same question about being inside the successCallback conditional.

2024-06-14 12:55 UTC, DarksightKellar commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +          });
Yeahhh, you're right

2024-06-14 14:27 UTC, adamgall commented on src/components/Proposals/ProposalsList.tsx
> +  const { t } = useTranslation(['proposal', 'common']);
Is the addition of `common` here needed?

2024-06-14 14:29 UTC, adamgall commented on src/hooks/DAO/loaders/useLoadDAOProposals.ts
> +    return (getValue(CacheKeys.TEMP_PROPOSALS, chain.id) || []) as TempProposalData[];
@Da-Colon are your changes to local storage going to add type safety to `getValue` calls like this, so we don't need to do unsafe `as` casting?

2024-06-14 14:30 UTC, adamgall commented on src/hooks/DAO/proposal/useProposals.ts
> +      const toastId = toast.info(`Waiting for confirmation on ${tempProposals.length} proposals`, {
This string should go into a translation file please

2024-06-14 14:31 UTC, adamgall commented on src/hooks/DAO/proposal/useProposals.ts
> +        removeTemporaryProposal(proposal.transactionHash!);
Hmm, at first glance it feels weird to have this state-changing code within a `filter`....

2024-06-14 14:33 UTC, adamgall commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +        []) as TempProposalData[];
another callout, that it would nice to have proper generics typing on `getValue`

2024-06-14 14:35 UTC, adamgall commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +      setValue(CacheKeys.TEMP_PROPOSALS, updatedProposals, CacheExpiry.ONE_DAY);
Hmm, but actually, how was the decision made to store these "temporary pending" proposals in local storage?

I understand that these will persist through a refresh, but do we really need that?

imo seems a bit overkill to utilize localstorage for this functionality.

2024-06-14 14:38 UTC, adamgall commented on src/hooks/utils/useSafeTransactions.ts
> +              (transaction as SafeMultisigTransactionWithTransfersResponse).safeTxHash,
Is this needed? The code builds for me without this change.

Logically, I suppose the reason why it would needed is if `transactionHash` is the empty string (Typescript says it's type is simply `string`).

empty string is `falsey`, so `safeTxHash` will be used in the `||` conditional.

Smells to me like maybe this is an opportunity to tighten up some typing.

Do you follow where my head's at? and if so do you agree? If so, Please add a `TODO` comment here for someone searching the codebase later for things to do.

2024-06-14 14:51 UTC, adamgall commented on src/utils/azorius.ts
> +    transactionHash = createdEvent.transactionHash;
Can you please add some more explicit code here?

```ts
// src/types/fractal.ts

export interface ActivityBase {
  eventDate: Date;
  eventType: ActivityEventType;
  transaction?: ActivityTransactionType;
  transactionHash: string;
}
```

```ts
  // src/utils/azorius.ts

  let transactionHash: string;
  if (state === FractalProposalState.EXECUTED) {
    const executedEvent = (await executedEvents)?.find(
      event => BigInt(event.args[0]) === proposalId,
    );
    if (!executedEvent) {
      throw new Error('proposal state is executed, but no event found');
    }
    transactionHash = executedEvent.transactionHash;
  } else {
    transactionHash = createdEvent.transactionHash;
  }
```

2024-06-14 14:52 UTC, adamgall commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +      setValue(CacheKeys.TEMP_PROPOSALS, updatedProposals, CacheExpiry.ONE_DAY);
@DarksightKellar this is probably my biggest-picture question about this PR

2024-06-14 15:39 UTC, tomstuart123 commented
@DarksightKellar - I maybe missing something but I couldn't replicate this and get the toaster to show up.

I tried 4 proposals here - https://deploy-preview-1998.app.dev.decentdao.org/proposals?dao=sep:0x40C6E5eFCE3b1f101bFB59e876F14aa5455D3E19

Video here - https://decentdao.slack.com/archives/C06QZTUTKRC/p1718379588738149?thread_ts=1718379569.781799&cid=C06QZTUTKRC

2024-06-14 19:29 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useLoadDAOProposals.ts
> +  const { getValue } = useLocalStorage();
@Da-Colon I've actually reverted the update i did wrt to this comment. It broke the cache -- used a weird key that couldn't be read back. Instead of spending more time fixing, I'd rather wait for your merge to break this(these) line(s), and update accordingly, when I know keys are uniform app-wide.

2024-06-14 19:29 UTC, DarksightKellar commented on src/components/Proposals/ProposalsList.tsx
> +  const { t } = useTranslation(['proposal', 'common']);
Nope, updated

2024-06-14 19:29 UTC, DarksightKellar commented on src/hooks/DAO/proposal/useProposals.ts
> +      const toastId = toast.info(`Waiting for confirmation on ${tempProposals.length} proposals`, {
Done-zo

2024-06-14 19:33 UTC, DarksightKellar commented on src/hooks/DAO/proposal/useProposals.ts
> +        removeTemporaryProposal(proposal.transactionHash!);
Yeahhh I was trying to avoid having run yet _another_ loop over the proposals just to remove potentially 1 (if ever) pending proposal. Besides `filter` is just a fancy way of doing `map` plus manually adding to a pre-declared array based on the `predicate`. I'm totally fine with it in this case.

2024-06-14 19:36 UTC, DarksightKellar commented on src/hooks/utils/useSafeTransactions.ts
> +              (transaction as SafeMultisigTransactionWithTransfersResponse).safeTxHash,
It _is_ needed, yep. The typing in that case is misleading, and `multiSigTransaction.transactionHash` turns out to always be an empty string (or was it `undefined`?). I chose not to replace the line with `transactionHash: (transaction as SafeMultisigTransactionWithTransfersResponse).safeTxHash` in case there's some legacy reasoning behind the choice in the first place.

I'll add the `todo` for the team to revisit this.

2024-06-14 19:38 UTC, DarksightKellar commented on src/utils/azorius.ts
> +    transactionHash = createdEvent.transactionHash;
Oh right, I see

2024-06-14 19:50 UTC, DarksightKellar commented
> @DarksightKellar - I maybe missing something but I couldn't replicate this and get the toaster to show up.
> 
> I tried 4 proposals here - https://deploy-preview-1998.app.dev.decentdao.org/proposals?dao=sep:0x40C6E5eFCE3b1f101bFB59e876F14aa5455D3E19
> 
> Video here - https://decentdao.slack.com/archives/C06QZTUTKRC/p1718379588738149?thread_ts=1718379569.781799&cid=C06QZTUTKRC

@tomstuart123 Yikes, one of the newer cleanup commits broke the cache. I've reverted -- should be working now

2024-06-14 19:58 UTC, DarksightKellar commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +      setValue(CacheKeys.TEMP_PROPOSALS, updatedProposals, CacheExpiry.ONE_DAY);
Hmm I suppose this could all be implemented with "simpler" app state. But I've tested (and tasted) the ability to refresh and still seeing that persistent pending toast. I like it and don't wanna go back.

Besides, won't the logic largely be the same? The only real difference feels like it'd be _where_ the temp data is coming from (+ the tiny extra ms needed to read/write to storage).

2024-06-14 19:59 UTC, DarksightKellar commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +        []) as TempProposalData[];
I expect these will need update after David's work is merged in, and I think we'll get type safety, yeah

2024-06-16 05:29 UTC, Da-Colon commented on src/hooks/DAO/loaders/useLoadDAOProposals.ts
> +    return (getValue(CacheKeys.TEMP_PROPOSALS, chain.id) || []) as TempProposalData[];
Yes thats correct, I've updated so that each cache's getValue is inferred from the cacheName key

2024-06-16 17:22 UTC, Da-Colon commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +      setValue(CacheKeys.TEMP_PROPOSALS, updatedProposals, CacheExpiry.ONE_DAY);
We could go crazy and make it slightly more 'complex' and use netlify/function and the store? though probably not worth the lift to show all viewers of pending proposals.

2024-06-17 02:57 UTC, adamgall commented on src/utils/azorius.ts
>    }
And then I guess I do have an outstanding question at the moment... what is going on here with finding a new use for this `transactionHash` property with a brand new `createdEvent` object?

2024-06-17 03:00 UTC, adamgall commented on src/components/pages/DaoDashboard/Activities/index.tsx
> +  useProposals({ sortBy, filters: [] });
What does calling this here do?

2024-06-17 03:04 UTC, adamgall commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +      setValue(CacheKeys.TEMP_PROPOSALS, updatedProposals, CacheExpiry.ONE_DAY);
It wouldn't make sense to show anyone other than the creator of the proposal, anything about that proposal before their RPC node picked up the block and added it to the official in-memory list.

2024-06-17 03:07 UTC, adamgall commented on src/hooks/DAO/proposal/useSubmitProposal.ts
> +      setValue(CacheKeys.TEMP_PROPOSALS, updatedProposals, CacheExpiry.ONE_DAY);
I do still think localstorage is a bit excessive for this implementation, but that's on me for not being clearer on upfront on what I was expecting.

I'll need to go look at the code again that manages adding/removing from this "pending transaction" datastore in localstorage...

2024-06-17 03:12 UTC, adamgall commented on src/hooks/DAO/proposal/useProposals.ts
> +    if (pendingProposalsToastIdRef.current) return;
Why this funny ref code? Is using the `toastId` and dismissing it in the effect's return not enough?

2024-06-17 03:19 UTC, adamgall commented on src/hooks/DAO/proposal/useProposals.ts
> +        removeTemporaryProposal(proposal.transactionHash!);
I just don't think this code belongs here. We're way to far up at the presentation layer to be fucking around with _cleaning up our localstorage state_.

Could this go into the the reducer actions for when saving actual proposals into state?

2024-06-17 03:24 UTC, adamgall requested changes
Looks good, just a few comments and questions

2024-06-17 12:05 UTC, tomstuart123 commented
Awesome, this works so smoothly for 'Create Proposal'. Thanks @DarksightKellar 

Last question, pre approval --> which other types of proposals should this work with? I tried it with SendAssets and it worked but not when I tried a change Safename proposal

2024-06-17 13:50 UTC, adamgall commented
> Awesome, this works so smoothly for 'Create Proposal'. Thanks @DarksightKellar
> 
> Last question, pre approval --> which other types of proposals should this work with? I tried it with SendAssets and it worked but not when I tried a change Safename proposal



> Awesome, this works so smoothly for 'Create Proposal'. Thanks @DarksightKellar
> 
> Last question, pre approval --> which other types of proposals should this work with? I tried it with SendAssets and it worked but not when I tried a change Safename proposal

This is a great question and makes me question whether `useSubmitProposal` is the appropriate place to trigger adding a temp proposal record... 

where else in the codebase can it go to capture _all_ proposal creation, or does that place not exist (yet)?

2024-06-17 19:15 UTC, adamgall commented on src/hooks/DAO/proposal/useProposals.ts
> +    if (pendingProposalsToastIdRef.current) return;
This is fixed

2024-06-17 20:03 UTC, adamgall commented on src/components/pages/DaoDashboard/Activities/index.tsx
> +  useProposals({ sortBy, filters: [] });
Removed

2024-06-17 22:54 UTC, adamgall submitted a review, later dismissed

2024-06-17 22:57 UTC, adamgall commented
ok @decentdao/engineering and @decentdao/product, this is ready for a full code re-review and UX re-test

2024-06-18 01:45 UTC, adamgall approved these changes

2024-06-18 15:46 UTC, tomstuart123 commented
Nice, this works for all of the below:

- Create child safe
- Create proposal
- send assets
- change name
- change snapshot space

Approved. Great work

2024-06-18 15:46 UTC, tomstuart123 approved these changes

2024-06-18 16:50 UTC, Da-Colon approved these changes

2024-06-18 16:54 UTC, merged