Roles 0.1.1/desktop and other updates
decentdao/decent-interface pull request #2081
Opened 2024-07-05 20:37 UTC by Da-Colon

2024-07-06 20:36 UTC, Da-Colon commented on src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
This basically just moves @mudrila work into its own file to make the `details/index` easier to follow with the two different drawers

2024-07-06 20:36 UTC, Da-Colon commented on src/constants/routes.ts
>    `${getDaoQueryParam(addressPrefix, daoAddress)}&hatIndex=${hatIndex}`;
For Editing, We use the HatIndex. This will allow for navigation from Role Details straight to Role Editing the proper Role

For Role Viewing, We use the HatId.

2024-07-08 13:12 UTC, adamgall commented on src/constants/routes.ts
>    `${getDaoQueryParam(addressPrefix, daoAddress)}&hatIndex=${hatIndex}`;
Why not use HatIndex for both cases?

2024-07-08 13:41 UTC, tomstuart123 approved these changes
As mentioned at standup, approving this for now based on this thread https://decentdao.slack.com/archives/C06QZTUTKRC/p1720351954501429

Will get do another round of testing on this once merged into root.

2024-07-08 14:26 UTC, adamgall requested changes

2024-07-08 14:26 UTC, adamgall commented on src/components/pages/Roles/RolesDetailsDrawer.tsx
> +    address: getAddress(roleHat.wearer || zeroAddress),
`|| zeroAddress` can be removed after change above.

2024-07-08 14:26 UTC, adamgall commented on src/components/pages/Roles/RolesDetailsDrawer.tsx
> +    chainId: getChainIdFromPrefix(addressPrefix),
nit: pull the `chain.id` directly out of `useNetworkConfig`, and don't use `getChainIdFromPrefix()`

2024-07-08 14:26 UTC, adamgall commented on src/components/pages/Roles/RolesDetailsDrawer.tsx
> +  const avatarURL = useAvatar(roleHat.wearer || zeroAddress);
Can remove `|| zeroAddress` after type change above

2024-07-08 14:26 UTC, adamgall commented on src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
> +    | RoleValue;
Change this type to the same one from `RolesDetailDrawer`

2024-07-08 14:26 UTC, adamgall commented on src/components/pages/Roles/RolesTable.tsx
> +  }
Ooh I like this

2024-07-08 14:26 UTC, adamgall commented on src/components/pages/Roles/RolesTable.tsx
> +      )}
Nit: plz DRY this table and the one from the Edit component into a function that receives the body rows (view, or edit), and returns the full table. I just want this dried up a bit

2024-07-08 14:26 UTC, adamgall commented on src/constants/routes.ts
>    `${getDaoQueryParam(addressPrefix, daoAddress)}&hatIndex=${hatIndex}`;
No sorry, I mean, it sounds like using Index is safer bet. So, why are we still using the HatId for Role Viewing?

2024-07-08 14:26 UTC, adamgall commented on src/pages/daos/[daoAddress]/roles/edit/index.tsx
> +    return [addedHatsText, updatedHatsText, removedHatsText].filter(Boolean).join('. ');
wat is `.filter(Boolean)`

2024-07-08 15:22 UTC, Da-Colon commented on src/pages/daos/[daoAddress]/roles/edit/index.tsx
> +    return [addedHatsText, updatedHatsText, removedHatsText].filter(Boolean).join('. ');
it part filters out any falsy values from the array

2024-07-08 15:23 UTC, Da-Colon commented on src/pages/daos/[daoAddress]/roles/edit/details/index.tsx
> +                        as={X}
I don't know, I think I just had got done create a `Icon` component and used `as` ha. I'll updated it

2024-07-08 15:49 UTC, nicolaus-sherrill commented
Can’t scroll on mobile browser.

I-phone 12
Aloha browser & Safari
<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/details?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD&hatIndex=0
Browser:   Safari 17.5.1 on iOS 17.5.1
Viewport:  390 x 671 @3x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2081.app.dev.decentdao.org%2Froles%2Fedit%2Fdetails%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD%26hatIndex%3D0&os=iOS&os_version=17.5&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2081.app.dev.decentdao.org/roles/edit/details?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD&hatIndex=0) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=668b30cffc4a0d0008ff3a94&commentID=668c0a9986b4e95a46541dad&resolution=resolved)

2024-07-08 16:21 UTC, nicolaus-sherrill commented
Missing "New/Updated" UI chip for affected roles in the Edit Roles view.

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY4YjMwY2ZmYzRhMGQwMDA4ZmYzYTk0IiwiaWQiOiI2OThiMWMxZC00YzIxLTQyYTQtOThlOC0wNGY5ZWRmMmJmY2QifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /roles/edit?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD
Browser:   Firefox 127.0 on Mac OS 10.15
Viewport:  1680 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2081.app.dev.decentdao.org%2Froles%2Fedit%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=127.0&resolution=1680x912&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2081.app.dev.decentdao.org/roles/edit?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=668b30cffc4a0d0008ff3a94&commentID=668c120427123c64ec6a5265&resolution=resolved)

2024-07-08 16:24 UTC, nicolaus-sherrill commented
Proposal creation is failing when trying to add a new role.

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY4YjMwY2ZmYzRhMGQwMDA4ZmYzYTk0IiwiaWQiOiJiMzZlNTRhYi0zNzA4LTQwODItOWQ1ZC0yMTZkNmU1M2FiNWUifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/summary?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD
Browser:   Firefox 127.0 on Mac OS 10.15
Viewport:  1680 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2081.app.dev.decentdao.org%2Froles%2Fedit%2Fsummary%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=127.0&resolution=1680x912&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2081.app.dev.decentdao.org/roles/edit/summary?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=668b30cffc4a0d0008ff3a94&commentID=668c12b3f646e316bc0f1a6d&resolution=resolved)

2024-07-08 16:28 UTC, nicolaus-sherrill commented
Dynamic copy overrides any previous manual text input when user clicks away from the proposal editor.

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY4YjMwY2ZmYzRhMGQwMDA4ZmYzYTk0IiwiaWQiOiJmZDBkZjMzZS01N2VmLTQ1ZTgtYWUwMC1lZGFiZDhjOTM5YzUifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/summary?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD
Browser:   Firefox 127.0 on Mac OS 10.15
Viewport:  1680 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2081.app.dev.decentdao.org%2Froles%2Fedit%2Fsummary%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=127.0&resolution=1680x912&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2081.app.dev.decentdao.org/roles/edit/summary?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=668b30cffc4a0d0008ff3a94&commentID=668c139fd4752666624f5fee&resolution=resolved)

2024-07-08 16:29 UTC, nicolaus-sherrill commented
No warning modal to stop the user from losing their draft changes.

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY4YjMwY2ZmYzRhMGQwMDA4ZmYzYTk0IiwiaWQiOiJhNmZmM2ZlYy1lNDQ3LTQ0M2UtOGUxMC0xNTQ3YzUwMTc1NGQifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /roles?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD
Browser:   Firefox 127.0 on Mac OS 10.15
Viewport:  1680 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2081.app.dev.decentdao.org%2Froles%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=127.0&resolution=1680x912&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2081.app.dev.decentdao.org/roles?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=668b30cffc4a0d0008ff3a94&commentID=668c13e53bde7d6bcfeafa35&resolution=resolved)

2024-07-09 13:30 UTC, adamgall approved these changes

2024-07-09 14:37 UTC, merged