Hot fixes
decentdao/decent-interface pull request #2111
Opened 2024-07-09 18:58 UTC by DarksightKellar

2024-07-09 21:47 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useHatsTree.ts
> +  const getHatsTree = useCallback(async () => {
Exporting `getHatTree` from this hook to naively re-query the entire tree whenever any of the hats contract events fire

2024-07-09 21:47 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useHatsTree.ts
> +    getHatsTree,
This is the only functional change in this hook (plus moving `getHatsTree` out of the `useEffect`. The rest are whitespace diffs

2024-07-09 21:47 UTC, DarksightKellar commented on src/pages/daos/[daoAddress]/roles/edit/summary/index.tsx
> +            position="absolute"
The fix for the role create proposal screen scroll issue

2024-07-10 02:46 UTC, adamgall requested changes
2 of the 3 issues in this PR are good to go. I'm going to push some new code to this branch to undo the implementation of the issue that i don't think is ready, then we can merge this and keep working in a new PR for that third issue.

2024-07-10 02:46 UTC, adamgall commented on src/hooks/DAO/loaders/useHatsTree.ts
> +  }, [chain.id, hatsSubgraphClient, hatsTreeId, setHatsTree, ipfsClient, getHatsTree]);
Probably don't need all of these dependencies here?

2024-07-10 02:46 UTC, adamgall commented on src/pages/daos/[daoAddress]/roles/edit/index.tsx
> +  useHatsListeners();
This needs to be instantiated somewhere higher, so that it stays mounted and in-memory throughout the context of a loaded DAO in our app. Right now it'll only be listening if the user is in the RolesEdit page here.

2024-07-10 02:46 UTC, adamgall commented on src/hooks/DAO/useHatsListeners.ts
> +    if (!hatsContract) return;
`hatsContract` won't be null or undefined, don't need this check.

2024-07-10 02:46 UTC, adamgall commented on src/hooks/DAO/useHatsListeners.ts
> +    hatsContract.watchEvent.HatCreated({
For all of these followingn lines:

1. These event watchers return functions, which need to be called when it's time to cleanly destroy the listener streams. Specifically, that needs to happen when the `useEffect` re-runs, because we'll be creating a new event listener, so we gotta close the first one.
    ```ts
    useEffect(() => {
      const unwatch = contract.watchEvent.Foo({ onLogs: logs => console.log(logs) })
      return () => {
        unwatch()
      }
    }, [])
   
   ```
2. Right now all of these event listeners are scoped only to the global Hats protocol contract. These listener callbacks are being fired for _every single_ time these events get fired, regardless of the Hat Tree. Can we scope these to just our (currently loaded) Hat Tree?

2024-07-10 02:48 UTC, adamgall approved these changes
This looks good now, for the two issues.

2024-07-10 02:48 UTC, merged