Issue/various role create form bugs
decentdao/decent-interface pull request #2145
Opened 2024-07-12 21:15 UTC by Da-Colon

Fixes #2143

This is fixed by fixing the schema to work properly preventing clicking Save button when its a invalid address

Fixes #2144 
There was a problem with the structure of the schema. 

`.default(undefined)`: Adding this stopped Yup from changing the intial value from `undefined` to `{}` which was causing the `is` conditional to be true when it should be undfined

`.nullable()`: allows for the `setFieldValue(undefined)` that we are using to actually clear the field.

I also noticed that there was some left over 'remove' code that no longer is needed and causing a bug.

2024-07-13 02:20 UTC, adamgall requested changes
#2143 is still occurring

#2144 seems good though ✅

2024-07-13 09:13 UTC, Da-Colon commented
> #2143 is still occurring
> 
> #2144 seems good though ✅

O I see. It was properly invalidating when it was a new role, but existing roles it was failing as the test was failing with an uncaught promise. adding a try/catch in the Yup validation test fixes it.

2024-07-14 01:37 UTC, adamgall approved these changes
Lookin good!

2024-07-14 15:42 UTC, adamgall commented
good points @mudrila

2024-07-15 10:10 UTC, tomstuart123 approved these changes
Both work for me now

2024-07-15 11:28 UTC, DarksightKellar approved these changes

2024-07-15 11:37 UTC, DarksightKellar commented
Pushed a commit to address Kyrill's comments on translation -- merging.

2024-07-15 11:37 UTC, merged