Roles 0.2.0/flush out the stream on wearer change
decentdao/decent-interface pull request #2165
Opened 2024-07-20 08:22 UTC by mudrila

This PR introduces following changes/functionality:

- Fetch and Display Payroll and Vesting information for the given Hat Account
- Rinse out payroll/vesting stream to the current wearer when changing hat wearer
- Rinse out payroll/vesting stream to the current wearer and cancel stream, which automatically returns remaining asset balance to the Safe, when deleting hat

Testing:
1. If you were creating payroll before - make sure it appears in the Roles list.
2. Try changing the wearer on the hat with active payroll (aka start date and first tranche already passed). Expected result - funds that weren't claimed are transferred to the "current wearer" and then wearer is changed to the new wearer
3. Try deleting the hat with active payroll. Expected result - funds that weren't claimed are transferred to the "current wearer", remaining funds from the stream are transferred back to the Safe, stream is cancelled, and then hat is "deleted"

2024-07-22 13:54 UTC, tomstuart123 commented
@mudrila - great question. I don't think enough thought has been put into this. 

**Before I choose,**
1) I think regardless of the option, both options should have more user feedback during creation to make sure its clear.

I.e. if we want the user to input '1000 tokens' + '10 months', we should dynamically generate some copy saying 'That'll be 100 per month'. OR if we go the other path, if we want the user to input '100 tokens' over '10 months', we should generate some copy saying 'That'll remove 1000 tokens from the treasury'

2) I think the copy here and here both need clarifying to make it easier to understand
![Screenshot 2024-07-22 at 14 44 21](https://github.com/user-attachments/assets/c3e39b1b-ef73-497f-ba90-4b88c6f11616)
![Screenshot 2024-07-22 at 14 47 18](https://github.com/user-attachments/assets/945b3e72-cd9a-46a9-ae12-15835f619c7e)


**Now my take on choice**

**re; Vesting** - this should 100% be the 'Total Amount'. Very few people think about vested tokens in a bottom up way 

**re; Payroll -** this could be either way... but I lean to the bottom up way due to i) I assume multiplication is easier than division (don't have to worry about decimals) and ii) when contractors quote their pay, they quote how much $x every y month. HOWEVER, this path relies on the dynamic text above (i.e. they could get confused if getting an 'invalid' message due to the total being bigger than what is in the treasury)

Note - @mudrila - if it's easier to make both Total Amount bottom down as a start, we can make this a seperate PR

@nicolaus-sherrill what's your take?

2024-07-22 13:56 UTC, tomstuart123 commented
@mudrila just testing this and the payroll I created last time isn't appearing [here](https://deploy-preview-2165.app.dev.decentdao.org/treasury?dao=sep:0x6922024B936f1e5485326044097d69C6DF87E8AF). Saying that, not sure if its because the payroll is no longer running ( I can't remember when I made it for)

Let me create a new role with payroll and let you know

2024-07-22 14:09 UTC, tomstuart123 commented
I haven't been able to test further than seeing the payroll I'm afraid (I'm getting the 'proposal failed' and treasury not updating to what's in production again... moralis?)

Anyway, just catching Adam up. So will again try after that. usually it resolves itself

2024-07-22 15:07 UTC, DarksightKellar approved these changes
Code review done, but not yet manually tested

2024-07-22 15:31 UTC, tomstuart123 commented
So ye @mudrila I've hit a bit of a wall

**editing my old payroll (1 token over 1 week), led to the below** 
i) I think the 1 token is appearing in wei as 0.00000000000000001
ii) I can't get the 'invalid amount' to go away with any number in the amount

![Screenshot 2024-07-22 at 16 28 14](https://github.com/user-attachments/assets/289fba10-5962-40cf-b24e-6164edfca9f9)

**Then I tried creating a new payroll to then edit later**
i) however, I keep getting 'proposal failed' on proposal creation. The treasury/moralis is showing up okay, so I think its somehting else blocking me
![Screenshot 2024-07-22 at 16 31 32](https://github.com/user-attachments/assets/9b60fde0-9005-49c2-a2db-4f9f7756a830)


I can try creating a payroll on the old PR and then editing it here, but thought I'd leave this feedback so you can start on it

2024-07-22 17:56 UTC, tomstuart123 commented
sorry @mudrila but I mean that when I try and change the wearer, the CTA for 'Save' is greyed out

i.e. all I did was update the below
![Screenshot 2024-07-22 at 18 54 46](https://github.com/user-attachments/assets/01716744-f85f-4671-b67a-b08e07bcf9c0)

to this below 
![Screenshot 2024-07-22 at 18 52 47](https://github.com/user-attachments/assets/6da6ce6e-04ee-4770-b42c-8c9c2ad037c6)

maybe I'm missing something?

2024-07-23 18:14 UTC, nicolaus-sherrill commented
Created a new issue [Tab navigation breaks proposal preview. #2170](https://github.com/decentdao/decent-interface/issues/2170) in GitHub

2024-07-23 18:35 UTC, nicolaus-sherrill commented
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY5ZmRlODQ2ZTc0ZDAwMDA4NDQ5ZWNjIiwiaWQiOiJhYWYzMGIwMy00OGNkLTQ0NmUtOGQ4MC04NGMxY2RkMzFiNzgifQ==)

I'm curious why it is not possible to select a date in the past to start payroll. We learned that streams can be backdated and backfilled accordingly. It's not exactly my first instinct to select a date in the past, but it _is_ possible.

<details><summary>Browser metadata</summary>





```
Path:      /roles/edit?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1680 x 904 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Froles%2Fedit%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1680x904&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles/edit?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=669ff7ebd54a9c1abc938247&resolution=resolved)

2024-07-23 18:48 UTC, nicolaus-sherrill commented
![image](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY5ZmRlODQ2ZTc0ZDAwMDA4NDQ5ZWNjIiwiaWQiOiJjOTA2ZGFlYi0zMTg5LTQzN2QtYmRiYy02OGFmMTRjNDBlMDEifQ==)
<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/details?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD&hatId=0x8f14e62d27de72d05967837bc1ef351734c57db8f877db60f6913ff74373a5ae
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1680 x 904 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Froles%2Fedit%2Fdetails%3Fdao%3Dsep%3A0xe20221A8939F9373C091262CBEF9493aca196acD%26hatId%3D0x8f14e62d27de72d05967837bc1ef351734c57db8f877db60f6913ff74373a5ae&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1680x904&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles/edit/details?dao=sep:0xe20221A8939F9373C091262CBEF9493aca196acD&hatId=0x8f14e62d27de72d05967837bc1ef351734c57db8f877db60f6913ff74373a5ae) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=669ffb00ce3bfd273ef0d0d6&resolution=resolved)

2024-07-23 18:49 UTC, nicolaus-sherrill commented
<img width="266" alt="Screenshot 2024-07-23 at 1 49 12 PM" src="https://github.com/user-attachments/assets/8dda4b82-1d73-42fe-8e9b-68f731614ce6">

z-index issue with tooltip and `Select Asset` dropdown

2024-07-23 19:03 UTC, nicolaus-sherrill commented
https://github.com/user-attachments/assets/2a9d8628-539f-40cd-9a52-00565cf05c2c

Two things here:
1. Dropdown is expanding from the right hand corner. Looks really odd. Let's have that drop directly down below. A slide down effect.

2. Dropdown selector styling looks off. It should have the same raised dimensional effect, but looks recessed instead.

2024-07-23 19:05 UTC, nicolaus-sherrill commented
<img width="166" alt="Screenshot 2024-07-23 at 2 05 37 PM" src="https://github.com/user-attachments/assets/b9bebd4d-be9d-4aa3-998e-a5cb8c34d67b">

Abbreviation for "week" is "wk"

2024-07-23 19:09 UTC, nicolaus-sherrill commented
<img width="1675" alt="Screenshot 2024-07-23 at 2 08 13 PM" src="https://github.com/user-attachments/assets/b8b5174d-41c7-4456-9c1b-a951c9bf482b">

Desktop side drawer should be using same overlay as other drawers.

Styling on drop shadow should only be 1px spread with no blur. Needs dimensional styling.

2024-07-23 19:12 UTC, nicolaus-sherrill commented
<img width="751" alt="Screenshot 2024-07-23 at 2 10 41 PM" src="https://github.com/user-attachments/assets/f645f784-c98a-4e6e-8649-bb4e0da8be2b">

Alignment of property labels and text input fields is off. Can we center up this proposal editor?

Extra padding on the card container for the affected roles.

2024-07-23 19:41 UTC, xraystyle1980 commented
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY5ZmRlODQ2ZTc0ZDAwMDA4NDQ5ZWNjIiwiaWQiOiIyZTkxZWRlYS1kOGYzLTQ5YjMtYTMxNi0yOGJjMjc2MGIzOTcifQ==)

I created a these 2 roles at the same time/same proposal however none of the payment + vesting was applied. (the admin role should have payroll + vesting and the designer role should have payroll)


<details><summary>Browser metadata</summary>





```
Path:      /roles?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Froles%3Fdao%3Dsep%3A0x316ce0Bd801bC39A19E531d55762847BCad1201c&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a0077ed54a9c2b2d9383a5&resolution=resolved)

2024-07-23 19:46 UTC, xraystyle1980 commented
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY5ZmRlODQ2ZTc0ZDAwMDA4NDQ5ZWNjIiwiaWQiOiI5ZmU3ZTcxMC1jNDMwLTRkNzMtOGZmZS01ZDMxNDFiM2E0YjYifQ==)

When I enter edit mode, the table columns shift to the left. I assume this is to make room for the status badge. But I wonder if we could handle this change a little more elegantly? i.e., less of a dramatic shift

<details><summary>Browser metadata</summary>





```
Path:      /roles/edit?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1465 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Froles%2Fedit%3Fdao%3Dsep%3A0x316ce0Bd801bC39A19E531d55762847BCad1201c&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1465x1027&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles/edit?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a00883036db235850a725b&resolution=resolved)

2024-07-23 19:49 UTC, xraystyle1980 commented
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY5ZmRlODQ2ZTc0ZDAwMDA4NDQ5ZWNjIiwiaWQiOiIwMzI3NjgzNC0yYzk4LTQyMDMtODNkNS0xZGI4YThkNWUyNzcifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/details?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c&hatId=0x0000019400010001000000000000000000000000000000000000000000000000
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Froles%2Fedit%2Fdetails%3Fdao%3Dsep%3A0x316ce0Bd801bC39A19E531d55762847BCad1201c%26hatId%3D0x0000019400010001000000000000000000000000000000000000000000000000&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles/edit/details?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c&hatId=0x0000019400010001000000000000000000000000000000000000000000000000) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a0094e5b0d382e35d21ae0&resolution=resolved)

2024-07-23 20:02 UTC, nicolaus-sherrill commented
<img width="717" alt="Screenshot 2024-07-23 at 3 01 48 PM" src="https://github.com/user-attachments/assets/8da31309-59eb-480e-9868-b44ce22d8f23">
Assets showing completely blank on Sepolia Safe.

Treasury holds Safe voting token, Sepolia ETH, Sepolia USDC

2024-07-23 20:03 UTC, nicolaus-sherrill commented
> ![screenshot](https://camo.githubusercontent.com/b5e082879a1dae941c7e11dc78dee8604c04d8c956315fad5652d0a535470929/68747470733a2f2f6e65746c6966792d636f636f6f6e2e6e65746c6966792e6170702f2e6e65746c6966792f66756e6374696f6e732f66657463683f636f64653d33303726706174683d65794a7a6158526c58326c6b496a6f6959324e685a44466d5a6d55745a4455345a5330304d6a4d344c574a695932457459324d774f544d784e5467314e574e6d496977695a4756776247393558326c6b496a6f694e6a59355a6d526c4f4451325a5463305a4441774d4441344e4451355a574e6a49697769615751694f6949795a546b785a57526c5953316b4f47597a4c545135596a4d7459544d784e6930794f474a6a4d6a63324d47497a4f54636966513d3d)
> 
> I created a these 2 roles at the same time/same proposal however none of the payment + vesting was applied. (the admin role should have payroll + vesting and the designer role should have payroll)
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a0077ed54a9c2b2d9383a5&resolution=resolved)

I experienced this same issue.

2024-07-23 20:12 UTC, nicolaus-sherrill commented
> @mudrila - great question. I don't think enough thought has been put into this.
> 
> **Before I choose,**
> 
> 1. I think regardless of the option, both options should have more user feedback during creation to make sure its clear.
> 
> I.e. if we want the user to input '1000 tokens' + '10 months', we should dynamically generate some copy saying 'That'll be 100 per month'. OR if we go the other path, if we want the user to input '100 tokens' over '10 months', we should generate some copy saying 'That'll remove 1000 tokens from the treasury'
> 
> 2. I think the copy here and here both need clarifying to make it easier to understand
>    ![Screenshot 2024-07-22 at 14 44 21](https://private-user-images.githubusercontent.com/31554133/350987293-c3e39b1b-ef73-497f-ba90-4b88c6f11616.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NjU1MjUsIm5iZiI6MTcyMTc2NTIyNSwicGF0aCI6Ii8zMTU1NDEzMy8zNTA5ODcyOTMtYzNlMzliMWItZWY3My00OTdmLWJhOTAtNGI4OGM2ZjExNjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDIwMDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZTE0ZjMyY2QyMjM1YTQ2YmM2MDllNjhjNTRlNzRjZDM5ODE0OTg5ZDk3NDVkZGU2NGQyMjEzNWViY2Y3ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1lq7ha3BVcrIpEM9QBZaqlKCpR5V98JnojSgnYDilz8)
>    ![Screenshot 2024-07-22 at 14 47 18](https://private-user-images.githubusercontent.com/31554133/350988262-945b3e72-cd9a-46a9-ae12-15835f619c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NjU1MjUsIm5iZiI6MTcyMTc2NTIyNSwicGF0aCI6Ii8zMTU1NDEzMy8zNTA5ODgyNjItOTQ1YjNlNzItY2Q5YS00NmE5LWFlMTItMTU4MzVmNjE5YzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDIwMDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYmI5MzQyYzJjNTAyNGQyMTJlNzZmZWI3NDg5NzZhM2ZiODcwNzdmZGFjZTExODFkYzA1ZGY2MTdmZWU3NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hkbjKaTRsc1_s8UzKnvQT_UZKxLFTsoOXrbmmsxk-pA)
> 
> **Now my take on choice**
> 
> **re; Vesting** - this should 100% be the 'Total Amount'. Very few people think about vested tokens in a bottom up way
> 
> **re; Payroll -** this could be either way... but I lean to the bottom up way due to i) I assume multiplication is easier than division (don't have to worry about decimals) and ii) when contractors quote their pay, they quote how much $x every y month. HOWEVER, this path relies on the dynamic text above (i.e. they could get confused if getting an 'invalid' message due to the total being bigger than what is in the treasury)
> 
> Note - @mudrila - if it's easier to make both Total Amount bottom down as a start, we can make this a seperate PR
> 
> @nicolaus-sherrill what's your take?

Getting around to this now.

I like what you said about contractors thinking of their payments in terms of `$x every y`. I was thinking the same. With that said, I'm leaning toward the logic supporting not the _total_ amount of pay over the course of the stream, but rather the amount per streaming increment.

So encouraging the user to input $5,000 /mo for 6 months. Maybe "Total Amount" label gets changed to simply "Amount", and somewhere in the UI there is an indication of the actual _total_ amount over the life of the stream.

2024-07-23 20:13 UTC, nicolaus-sherrill requested changes
A lot of visual issues to be polished up, and I could not get a payroll to be created.
Buuuut other than that, the new UI is looking great y'all, and it's very helpful to see these flows in action to get a better feel for them for UX.

2024-07-23 20:26 UTC, xraystyle1980 commented
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY5ZmRlODQ2ZTc0ZDAwMDA4NDQ5ZWNjIiwiaWQiOiJlMTQ2OWQwZS1jYjU3LTRkMTQtODJmMS1iNWU0ZDk0N2EyYTYifQ==)


Please add footer component below submit proposal button
<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/summary?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1465 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Froles%2Fedit%2Fsummary%3Fdao%3Dsep%3A0x316ce0Bd801bC39A19E531d55762847BCad1201c&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1465x1027&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles/edit/summary?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a0120b209146382d4b6d9b&resolution=resolved)

2024-07-23 20:32 UTC, xraystyle1980 commented
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY5ZmRlODQ2ZTc0ZDAwMDA4NDQ5ZWNjIiwiaWQiOiI0MGE0ZjBhNy0wOGQyLTQzM2ItYWJmYy0yNDkyZjljMzg1MzUifQ==)

Getting Toast message with "Unable to encode proposal data" (see recording)

<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/summary?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Froles%2Fedit%2Fsummary%3Fdao%3Dsep%3A0x316ce0Bd801bC39A19E531d55762847BCad1201c&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles/edit/summary?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a01352ad6e393870041784&resolution=resolved)

2024-07-23 21:09 UTC, xraystyle1980 commented
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY5ZmRlODQ2ZTc0ZDAwMDA4NDQ5ZWNjIiwiaWQiOiIzNDlkNWU5Zi1mYzY1LTRmNmQtYWU2NS00ZmQwYzJiMzU5YzEifQ==)

At the end of the recording, after the "Vote successful" toast goes away, the voting controls will briefly flash. Is the intended behavior to disappear completely?
<details><summary>Browser metadata</summary>





```
Path:      /proposals/2?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c
Browser:   Chrome 126.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2165.app.dev.decentdao.org%2Fproposals%2F2%3Fdao%3Dsep%3A0x316ce0Bd801bC39A19E531d55762847BCad1201c&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=126.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/proposals/2?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a01c0e4c78b342bd2dfed2&resolution=resolved)

2024-07-24 15:47 UTC, adamgall commented
> ![recording](https://camo.githubusercontent.com/e9d426f65c4f779f3a7272fa75ef0ac04730ae436487e827bdfa88ad004689ed/68747470733a2f2f6e65746c6966792d636f636f6f6e2e6e65746c6966792e6170702f2e6e65746c6966792f66756e6374696f6e732f66657463683f636f64653d33303726706174683d65794a7a6158526c58326c6b496a6f6959324e685a44466d5a6d55745a4455345a5330304d6a4d344c574a695932457459324d774f544d784e5467314e574e6d496977695a4756776247393558326c6b496a6f694e6a59355a6d526c4f4451325a5463305a4441774d4441344e4451355a574e6a49697769615751694f6949304d4745305a6a42684e7930774f4751794c54517a4d32497459574a6d597930794e446b795a6a6c6a4d7a67314d7a556966513d3d)
> 
> Getting Toast message with "Unable to encode proposal data" (see recording)
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-2165.app.dev.decentdao.org/roles/edit/summary?dao=sep:0x316ce0Bd801bC39A19E531d55762847BCad1201c) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=669fde846e74d00008449ecc&commentID=66a01352ad6e393870041784&resolution=resolved)

@xraystyle1980 is this an Azorius DAO, and did you delegate tokens to yourself before attempting to create that proposal?

2024-07-24 19:23 UTC, Da-Colon commented
> @tomstuart123 @nicolaus-sherrill @adamgall
> 
> One caveat on displaying payroll that I noticed - on the code level I'm using `Total Amount` that user provides as a whole amount of the stream. Which means if you were putting `12000` there and set frequency to "12 months" - this will display `1000 / mo`. I've raised this before on Figma, and just wanted to confirm - this is how we wanna this to be displayed. Currently it creates misleading UI/UX during payroll creation, since it will display `12000 / mo` while in fact that will be `1000 / mo`.
> 
> My question here :
> 
> * Should we adjust the logic so that amount that users puts is then properly divided per number of payroll tranches, aka user puts 12000, we dividing that to figure out monthly/bi-weekly/weekly tranche amount, and then displaying `1000 / mo`
> * Or should we use that "Total Amount" field as "tranche amount" and on the code level "reverse logic" - figure out total amount to be streamed based on "tranche amount" multiplied by number of pay cycles

I think what you are saying is the current expectation. Just design transfer the same number instead of 5000/12. @nicolaus-sherrill. Can you confirm this. I was also thinking that @Delmslaugh could take a look at this workflow and see if it makes sense from a admin prospective.

I guess the question is..
- Is the `Total Amount` field the Total Amount that will be divided by the `frequency` option the user chooses. 
or
- Should it be `amount` that will be claimable at each period. 

I guess this UX might change up a little per today's discussion, just wanted to note my thoughts on current setup adn comment

2024-07-25 14:48 UTC, Da-Colon commented on src/hooks/DAO/loaders/useHatsTree.ts
> +                  BigInt(stream.withdrawnAmount) !== BigInt(stream.intactAmount),
I think this is correct. I read this as

`in active period` or `there is money to be claimed`

2024-07-25 14:48 UTC, Da-Colon commented on src/hooks/streams/useSablierStream.ts
> +      throw new Error('Can not flush stream without streamId or contract address');
yessir

2024-07-25 14:57 UTC, Da-Colon commented
> sorry @mudrila but I mean that when I try and change the wearer, the CTA for 'Save' is greyed out
> 
> i.e. all I did was update the below ![Screenshot 2024-07-22 at 18 54 46](https://private-user-images.githubusercontent.com/31554133/351064058-01716744-f85f-4671-b67a-b08e07bcf9c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODA5MDgsIm5iZiI6MTcyMTg4MDYwOCwicGF0aCI6Ii8zMTU1NDEzMy8zNTEwNjQwNTgtMDE3MTY3NDQtZjg1Zi00NjcxLWI2N2EtYjA4ZTA3YmNmOWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA0MTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMjhmNDY1NjhkOTVlODRhNmI4MGQ4Mjk2ZjZjMTFmMDI4NmU4ZjUyMDJkYmEwMTJiYmJjMmZiMWZkMWM1NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8XYPb0YdLuyxUdBZbyAQaR2SrrGLH9Yjuts2WXvoggk)
> 
> to this below ![Screenshot 2024-07-22 at 18 52 47](https://private-user-images.githubusercontent.com/31554133/351064119-6da6ce6e-04ee-4770-b42c-8c9c2ad037c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODA5MDgsIm5iZiI6MTcyMTg4MDYwOCwicGF0aCI6Ii8zMTU1NDEzMy8zNTEwNjQxMTktNmRhNmNlNmUtMDRlZS00NzcwLWI0MmMtOGM5YzJhZDAzN2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA0MTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiY2ZlNDMwOTVmNDdkNzQyY2U2ZjVjZTlkZjQwN2Q2OGQ1NjRiNDFkN2E1MWIzZDRkOTRmZGE1MDRjOGJmMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pdIPY-udQl8cF4pkx6A6PO9ifuVuMt0RXxplt36yRsU)
> 
> maybe I'm missing something?

Ah I'm able to reproduce. It does have something to do with edit side of things. this will probably change after today's discussion

2024-07-25 16:26 UTC, merged