`[roles-0.2.0]` Claim hat stream
decentdao/decent-interface pull request #2201
Opened 2024-08-02 14:40 UTC by mudrila

This PR implements basic UI and logic for withdrawing payment to the hat wearer.
It also fixes filtering of added/edited payments as previously added payment was also considered as edited.

Closes #2186 

Testing steps:

1. Create payment for any given role, where you're a wearer. Make total length of the payment short enough so that you could easily withdraw sufficient amount of tokens (1 hour for 1000 tokens should be good).
2. Vote and execute proposal for creating payment to the role
3. Go to the role details - payment info should appear there
4. Notice "Withdraw" section appearing in the payment details
5. Enter amount to withdraw (do not put maximum amount just yet) and hit "Withdraw" - this will prompt to sign transaction
6. Make sure proper amount of tokens were sent to your wallet
7. Now, hit "max" button and hit "Withdraw" and sign transaction
8. Make sure proper amount of all available for withdrawing tokens were sent to your wallet

Basic design was grabbed from https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=4087-18066&m=dev but not implemented 1-1, since that design should change (afaik)
<img width="1172" alt="Screenshot 2024-08-02 at 16 33 30" src="https://github.com/user-attachments/assets/fc38054c-af8c-4260-9b95-580fd3c0de90">

2024-08-02 16:00 UTC, tomstuart123 commented
Nice @mudrila - I played with this [at this link](https://deploy-preview-2201.app.dev.decentdao.org/roles?dao=sep:0x7bABf83D1836DFB0eEAADF697cAb8A7ebDc2cE5E) on the COO role - 

Testing steps:

- - Create payment for any given role, where you're a wearer. ✅
- Make total length of the payment short enough so that you could easily withdraw sufficient amount of tokens (1 hour for 1000 tokens should be good).✅
- Vote and execute proposal for creating payment to the role✅
- Go to the role details - payment info should appear there✅
- Notice "Withdraw" section appearing in the payment details✅
[- NOTE cool here was instantly I saw withdraw but no CTA. Then when token became avaiable after 1 min, it appeared. NICE] ✅
- Enter amount to withdraw (do not put maximum amount just yet) and hit "Withdraw" - this will prompt to sign transaction ✅
- Make sure proper amount of tokens were sent to your wallet ❌
- Now, hit "max" button and hit "Withdraw" and sign transaction ❌ 
- Make sure proper amount of all available for withdrawing tokens were sent to your wallet ❌

So it was all going soooo smooth. But then it seems the withdraw button isn't working right.

A few things:
--> 'MAX' doesn't seem to be giving the max tokens. It shows me one instead of the correct 4 ([video link here](https://decentdao.slack.com/archives/C06QZTUTKRC/p1722614033710269?thread_ts=1722614017.545249&cid=C06QZTUTKRC))
--> Also my wallet didn't receive the correct amount and the claim amount isn't going down. Finally, when I try and sign on metamask it also seems that no token transfer is made (see screenshot below)
<img width="176" alt="Screenshot 2024-08-02 at 16 55 42" src="https://github.com/user-attachments/assets/9ff1cb79-39be-48a1-b40c-1f800b1e8bd1">

2024-08-04 17:56 UTC, Da-Colon commented on src/pages/daos/[daoAddress]/roles/details/PaymentDetails.tsx
> +        }
Does these transactions actually need to come from the Smart Account's? Might be why @tomstuart123 sees no transfer? (surprised it doesn't just revert?)

2024-08-05 14:46 UTC, tomstuart123 commented
@mudrila - cheers for tweaking the 'Max' button. This works well now

Re: the withdraw itself, sadly still doesn't work (i.e. no tokens added to my wallet and no tokens removed from claimable amount ). 

To debug - The address I'm logged in with (and receipient) is 0xC8375cC2C5fA34eba6aC386fECCaBaE1E51158c8. The Tx hash for the transaction is [here](https://sepolia.etherscan.io/tx/0x8d908340a79e2b46a8fc96364578244ff1787bfc20d6193f279b04e672393313). In etherscan it clearly is called by my address and interacts with this address (https://sepolia.etherscan.io/address/0xc12f542d81b66e02ffaf1008a680eaa3a90e30a8). 

I'll try again now with a new role, stream and address and report below. See if it works from scratch

2024-08-05 15:04 UTC, tomstuart123 commented
hey, @mudrila for some reason its now working. Not sure what is up with that current role.

but ye for the last two roles in the list [here](https://deploy-preview-2201.app.dev.decentdao.org/roles/details?dao=sep:0x7bABf83D1836DFB0eEAADF697cAb8A7ebDc2cE5E&hatId=0x000001a600010005000000000000000000000000000000000000000000000000) my address here 0xf26d75b2Fc048F1F6C793aE9F939Fa0946a0E104 has been able to claim

Feedback on gaps:
1) 'Remaining' amount isn't updating as I claim. In the below screenshot, I have claimed once from this already and yet the total amount (60) is showing with nothing removed. Note though 'withdrawable ' is working fine 
![Screenshot 2024-08-05 at 16 02 29](https://github.com/user-attachments/assets/52214d03-a49a-406f-8e9b-6d8a9a4cc1af)

2) A small copy error. It should be 'hang tight' not 'hand tight'
![Screenshot 2024-08-05 at 16 03 42](https://github.com/user-attachments/assets/2e815105-2ee0-49e7-b968-09fbc357496d)

2024-08-05 18:29 UTC, tomstuart123 commented
Hey @mudrila . These two both look good

Last thing: if you 1) click withdraw 2) then cancel it via the wallet 3) the toaster for 'hang tight' doesn't ever go away. You have to refresh page. 

Is there a way to exit if the Tx is cancelled?

2024-08-05 23:38 UTC, adamgall requested changes

2024-08-05 23:38 UTC, adamgall commented on src/components/pages/Roles/RolesDetailsDrawer.tsx
> +    smartAddress: Address;
Doesn't look like this is used?

2024-08-05 23:38 UTC, adamgall commented on src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
> +    smartAddress: Address;
Doesn't look like this is used?

2024-08-05 23:38 UTC, adamgall commented on src/pages/daos/[daoAddress]/roles/details/PaymentDetails.tsx
> +        const withdrawToast = toast('Withdrawing your payment, hang tight', {
Let's add this string, and the others below in this file, into the locales.

2024-08-06 15:14 UTC, adamgall commented on src/pages/daos/[daoAddress]/roles/details/PaymentDetails.tsx
> +          toast('withdrawRevertedMessage'); // @todo - Add proper copy
Think these are missing the `t()` call.

Also, let's remove these `@todo`s and just get the proper copy into this PR.

2024-08-06 15:19 UTC, adamgall commented on src/pages/daos/[daoAddress]/roles/details/PaymentDetails.tsx
> +        if (typeof withdrawToast !== 'undefined') {
Also, why not just `if (withdrawToast !== undefined) {` ?

2024-08-06 15:21 UTC, adamgall approved these changes

2024-08-06 15:39 UTC, Da-Colon approved these changes
I'll throw in that I've tested and claim does indeed work.

2024-08-06 16:09 UTC, tomstuart123 approved these changes
@mudrila this works now. Thanks so much for dealing with all my back and forth feedback

2024-08-06 22:31 UTC, xraystyle1980 commented
@mudrila @adamgall @tomstuart123 I can't seem to create any roles with payments. My process is
- create role, save
- create proposal, execute
- add payment stream, nothing populates in dropdown

2024-08-06 22:38 UTC, nicolaus-sherrill commented on src/i18n/locales/en/roles.json
> +  "withdrawPendingMessage": "Withdrawing your payment, hang tight",
@mudrila this copy will be affected by these multi-stream UI updates, so I'm not too hung up on the specific verbiage for now. My only suggestion is changing the PendingMessage to "Your withdrawal is processing. Hang tight." Let's leave the rest as is.

In regards to the toast success/reverted/error messaging, probably best to leave out the emoticons. :-)

Success Message: "Congrats, you got paid! Your withdrawal was successful."
Reverted Message: "Your withdrawal has been reverted. Your funds are still available to claim."
Error Message: "Your withdrawal failed due to an error. Please try again."


I might be missing some technical nuance around the transactions here for copy guidance, so @tomstuart123 @xraystyle1980 please QA

2024-08-07 03:43 UTC, merged

2024-08-07 12:35 UTC, xraystyle1980 commented
> > @mudrila @adamgall @tomstuart123 I can't seem to create any roles with payments. My process is
> > 
> > * create role, save
> > * create proposal, execute
> > * add payment stream, nothing populates in dropdown
> 
> WDYM "nothing populates in dropdown"?

The Asset dropdown for setting up a payment is empty