Swap fonts from `TT Firs Neue` to `DM Sans`
decentdao/decent-interface pull request #2213
Opened 2024-08-05 15:10 UTC by mudrila

Closes #2202

2024-08-05 18:30 UTC, tomstuart123 commented
note - won't have time to review this today. So could @decentdao/design act as non-technical review on this so its not blocked?

2024-08-05 18:33 UTC, adamgall requested changes

2024-08-05 18:33 UTC, adamgall commented on public/fonts/DMSans-VariableFont_opsz,wght.ttf
dont need this file

2024-08-06 12:41 UTC, xanaramoss approved these changes

2024-08-06 13:35 UTC, adamgall approved these changes

2024-08-06 13:39 UTC, Da-Colon commented on public/fonts/DMSans-VariableFont_opsz,wght.ttf
Isn't ttf font file. used to support older browsers?

2024-08-06 13:44 UTC, merged

2024-08-06 13:52 UTC, adamgall commented on public/fonts/DMSans-VariableFont_opsz,wght.ttf
yeah but we haven't supported them in the past and i don't care about starting now.