`2218` BugFix: Queued Transactions not showing up
decentdao/decent-interface pull request #2223
Opened 2024-08-08 19:28 UTC by Da-Colon

Fixes #2218

This PR replaces the `getAllTransaction` API request with `getMultisigTransactions` request. Most of the properties are the same except for the `transfers` property.

There are two spots where this is changes somethings.

Dashboard:
Will no longer show Treasury activities. These would be either a Card itself or added text to the bottom of the description that would display any transfer information.

Treasury:
~In Progress: But this also used `getAllTransactions`. will be need to be updated to `getIncomingTransactions`, but we lose the easily asseible `tokenInfo` in the transfer data.

~Update: Was able to use a combination of `getIncomingTransactions` and `getToken` from Safe's `api-kit` to retrieve the same data and put Treasury back together.

2024-08-09 00:20 UTC, Da-Colon commented on src/components/pages/DAOTreasury/hooks/useFormatTransfers.tsx
> +  const transfersFromTransactions = transfers ?? [];
I think either would work. I kinda prefer `??` as its only for `null` or 'undefined` specifically.

2024-08-09 00:21 UTC, Da-Colon commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +        // @note When would there be a transfer with no token address? Should this just throw an error?
Yeah figured this out while talking to adam earlier. native tokens will pass through here. so Ill be making updating to this file.

2024-08-09 17:23 UTC, adamgall requested changes

2024-08-09 17:23 UTC, adamgall commented on src/types/fractal.ts
> +  transfersLoaded?: boolean;
Could you utilize the `type | null | undefined` pattern for `transfers: TransferDisplayData[] | null | undefined`, to take the place of `transfersLoading` and `transfersLoaded`

- `undefined` means error
- `null` means loading
- `TransferDisplayData[].length = 0` means loaded and empty

nbd if not tbh

2024-08-09 17:23 UTC, adamgall commented on src/hooks/utils/useSafeTransactions.ts
> +            const multiSigTransaction = activity.transaction;
@Da-Colon i just removed this line locally and cleaned up the references and all seems good. is there a reason you don't want to do this? j/w

2024-08-09 17:23 UTC, adamgall commented on src/providers/App/hooks/useSafeAPI.ts
> +  }
Question:

Does this implementation behave well over time with this function is commented out?

Meaning more specifically: this function should exist _purely_ as as optimization, _not_ as a requirement for correct behavior. Is that the case in this PR?

2024-08-09 17:23 UTC, adamgall commented on src/providers/App/treasury/action.ts
> +    }
To go along with my above suggestion about overriding the type of TransferDisplayData[], these actions would change.

2024-08-09 17:23 UTC, adamgall commented on src/providers/App/treasury/reducer.ts
> +      return { ...state, transfersLoaded: true };
And the reducer of course

2024-08-09 17:23 UTC, adamgall commented on src/hooks/utils/useSafeTransactions.ts
> +          const eventDate = new Date(transaction.submissionDate);
The old code for this line was:

```ts
// @note for ethereum transactions event these are the execution date
const eventDate = new Date(
  multiSigTransaction.submissionDate || ethereumTransaction.executionDate,
)
```

Was it intentional to change that?

2024-08-09 17:23 UTC, adamgall commented on src/hooks/utils/useSafeTransactions.ts
> +          const eventType = ActivityEventType.Governance;
We know this isn't an `ActivityEventType.Treasury` type? Is that because of the API endpoints changing their return data... 

the input data to this function just never contains treasury data any longer??

2024-08-09 17:23 UTC, adamgall commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +  );
Is it safe to assume this function is the same function as the deleted function in that other file?

2024-08-09 17:23 UTC, adamgall commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +
So in here, I have some more suggestions. Maybe these aren't essential for this PR.

Instead of jumping straight into the `map` on 97, then making a `safeAPI.getToken()` call for each transfer (which, yes, goes through a caching layer),

perhaps a different approach would be to reduce down the `transfers.results` to only a unique list of token contract addresses,

then processing that array as you're doing now.

That way, we wouldn't need to _rely_ on the caching layer to prevent our codebase from making multiple identical API requests (which isn't the point of the caching layer).

2024-08-09 18:07 UTC, tomstuart123 commented
@Da-Colon - see test results below

Ensure that Multisig queued Proposals show up ✅ 
Ensure Transactions (Transfers) show up on Treasury Page (any safe) - ❌ 

**Detail** --> Ensure that Multisig queued Proposals show up ✅ 
- Proposals seems to be appearing that are pending. I tested x2 types
- Link [here](app.dev.decentdao.org/home?dao=sep:0xD954B0110aF1e4282a8cd682586e734Dc406e823) - 
<img width="1401" alt="Screenshot 2024-08-09 at 19 04 45" src="https://github.com/user-attachments/assets/81777ef0-22dd-4da5-bde0-2c892b4d0563">


**Detail** --> Ensure Transactions (Transfers) show up on Treasury Page (any safe) - ❌ 
- @Da-Colon here's the issue as seem to be missing some txs
- link - [here](https://deploy-preview-2223.app.dev.decentdao.org/treasury?dao=eth:0x36bD3044ab68f600f6d3e081056F34f2a58432c4)
- For app.dev I get this
<img width="1304" alt="Screenshot 2024-08-09 at 19 02 40" src="https://github.com/user-attachments/assets/ba59827c-47db-44bb-9657-e834ad5968a9">

- For this PR I get this
<img width="1316" alt="Screenshot 2024-08-09 at 19 02 35" src="https://github.com/user-attachments/assets/75fc44ea-92ca-4baf-a8c7-d158cb95b41a">

2024-08-09 19:42 UTC, Da-Colon commented on src/components/pages/DAOTreasury/components/Transactions.tsx
> +      {(transfersLoading || !transfersLoaded) && <Box>{/* @todo add Wave Loader */}</Box>}
I don't have the wave loader....

2024-08-09 19:45 UTC, adamgall commented on src/components/pages/DAOTreasury/components/Transactions.tsx
> +      {(transfersLoading || !transfersLoaded) && <Box>{/* @todo add Wave Loader */}</Box>}
what do you mean

2024-08-09 20:02 UTC, Da-Colon commented on src/hooks/utils/useSafeTransactions.ts
> +          const eventDate = new Date(transaction.submissionDate);
yes? no longer dealing with ``ethereumTransactions` here

2024-08-09 20:08 UTC, Da-Colon commented on src/hooks/utils/useSafeTransactions.ts
> +          const eventType = ActivityEventType.Governance;
deleted

2024-08-09 20:08 UTC, Da-Colon commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +  );
yep

2024-08-09 20:10 UTC, adamgall commented on src/components/pages/DAOTreasury/components/Transactions.tsx
> +      {(transfersLoading || !transfersLoaded) && <Box>{/* @todo add Wave Loader */}</Box>}
Ah, I get it now lol

2024-08-09 20:15 UTC, Da-Colon commented
> @Da-Colon - see test results below
> 
> Ensure that Multisig queued Proposals show up ✅ Ensure Transactions (Transfers) show up on Treasury Page (any safe) - ❌
> 
> **Detail** --> Ensure that Multisig queued Proposals show up ✅
> 
> * Proposals seems to be appearing that are pending. I tested x2 types
> * Link [here](app.dev.decentdao.org/home?dao=sep:0xD954B0110aF1e4282a8cd682586e734Dc406e823) -
> 
> <img alt="Screenshot 2024-08-09 at 19 04 45" width="1401" src="https://private-user-images.githubusercontent.com/31554133/356705994-81777ef0-22dd-4da5-bde0-2c892b4d0563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzQ3MzIsIm5iZiI6MTcyMzIzNDQzMiwicGF0aCI6Ii8zMTU1NDEzMy8zNTY3MDU5OTQtODE3NzdlZjAtMjJkZC00ZGE1LWJkZTAtMmM4OTJiNGQwNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDIwMTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2Mjg4MzBjZTMyMjI2ZWQwMGViNWRiOTM4MDRlMTdjZjU1NGE4ZjZkZWNkN2ZhOTI1YjYwZTdkNjAzYjJhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EplV1ToF6IzP1XTD3A_1j87i5xjxBxZnq_BE9bykdkg">
> **Detail** --> Ensure Transactions (Transfers) show up on Treasury Page (any safe) - ❌
> 
> * @Da-Colon here's the issue as seem to be missing some txs
> * link - [here](https://deploy-preview-2223.app.dev.decentdao.org/treasury?dao=eth:0x36bD3044ab68f600f6d3e081056F34f2a58432c4)
> * For app.dev I get this
> 
> <img alt="Screenshot 2024-08-09 at 19 02 40" width="1304" src="https://private-user-images.githubusercontent.com/31554133/356705386-ba59827c-47db-44bb-9657-e834ad5968a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzQ3MzIsIm5iZiI6MTcyMzIzNDQzMiwicGF0aCI6Ii8zMTU1NDEzMy8zNTY3MDUzODYtYmE1OTgyN2MtNDdkYi00NGJiLTk2NTctZTgzNGFkNTk2OGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDIwMTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZTg5OTYxYjRiZDcwYzAwMDI2OTlkM2U3ZGEyNjYzZTYzOGRiYTRjY2QwN2YwOGVkMDUzYmMyM2UyNmZlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7EnFt35nwQ-X69epFTh8kx-ktuk_JykjQYywFLNKpLs">
> * For this PR I get this
> 
> <img alt="Screenshot 2024-08-09 at 19 02 35" width="1316" src="https://private-user-images.githubusercontent.com/31554133/356705316-75fc44ea-92ca-4baf-a8c7-d158cb95b41a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzQ3MzIsIm5iZiI6MTcyMzIzNDQzMiwicGF0aCI6Ii8zMTU1NDEzMy8zNTY3MDUzMTYtNzVmYzQ0ZWEtOTJjYS00YmFmLWE4YzctZDE1OGNiOTViNDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDIwMTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1OTBjNjMyNTI0Zjg0OTViOGRiZTJlMGI2YTJlNjFmMDQ3ZDMwZjU5OGU5MWU3OWFmMDZjNzQwMzgxODY2ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tHTAOr9ytBpal32gC15rbYJ7hUKsbWpmkb_i5oJ00DA">

Yeah works on both the Prod and dev preview links for me?
![image](https://github.com/user-attachments/assets/b2aa0bf4-ed4b-45c2-98fa-ec4674d35cbd)

2024-08-09 20:15 UTC, adamgall commented on src/hooks/utils/useSafeTransactions.ts
> +          const eventType = ActivityEventType.Governance;
Oh snap I didn't realize it was gonna be like that! So hmm, you're saying there are no more "Treasury" Activity Event Types. What are the implications of that? Is that why Tom is leaving the feedback he's leaving about some items being missing?

2024-08-09 20:15 UTC, adamgall commented on src/hooks/utils/useSafeTransactions.ts
> +            const multiSigTransaction = activity.transaction;
This has been deleted, thanks @Da-Colon

2024-08-09 20:16 UTC, adamgall commented on src/types/daoTreasury.ts
> -export interface TreasuryActivity extends ActivityBase {
@Da-Colon can you comment on the intended functionality here?

2024-08-09 20:16 UTC, adamgall commented on src/types/fractal.ts
> +export type ActivityTransactionType = SafeMultisigTransactionResponse;
@Da-Colon do you agree or disagree with this suggestion?

2024-08-09 20:52 UTC, Da-Colon commented on src/types/daoTreasury.ts
> -export interface TreasuryActivity extends ActivityBase {
The latter, I haven't seen them in a while, Not sure if there was a bug, change in the response or what.

2024-08-09 20:52 UTC, adamgall commented
@Da-Colon look closer at Tom's screenshot for "on app.dev i get this"

it includes a transaction at the top for incoming 425 USDC from 4 days ago. that TX is not on this PR's deploy preview (according to Tom)

2024-08-09 20:52 UTC, Da-Colon commented on src/types/fractal.ts
> +export type ActivityTransactionType = SafeMultisigTransactionResponse;
Removed it

2024-08-09 20:53 UTC, Da-Colon commented on src/hooks/utils/useSafeTransactions.ts
> +          const eventType = ActivityEventType.Governance;
unrelated, haven't been able to replicate the bug he is seeing

2024-08-09 20:55 UTC, adamgall commented on src/hooks/utils/useSafeTransactions.ts
> +          const eventType = ActivityEventType.Governance;
OHHH i see what the (a) problem is. The transactions on the Treasury page aren't sorted properly!

2024-08-09 20:57 UTC, Da-Colon commented on src/hooks/utils/useSafeTransactions.ts
> +          const eventType = ActivityEventType.Governance;
ah good catch. I didn't even noticed the wonky dates. I see. gotcha.

2024-08-09 21:34 UTC, Da-Colon commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +
Coolio Done.

2024-08-09 21:35 UTC, Da-Colon commented
> @Da-Colon look closer at Tom's screenshot for "on app.dev i get this"
> 
> it includes a transaction at the top for incoming 425 USDC from 4 days ago. that TX is not on this PR's deploy preview (according to Tom)

I see it now. Sorted and Fixed

2024-08-12 13:41 UTC, Da-Colon commented on src/providers/App/hooks/useSafeAPI.ts
> +  }
Ah man I didn't send my comment here and it got erased. 

The answer is yes and no. For newer DAOs shouldn't be an issue. For first time visit to large DAOs. This caching would be needed for now as it would hit the rate limit.

I did add a single retry to help manage it.

2024-08-12 14:16 UTC, adamgall commented on src/providers/App/hooks/useSafeAPI.ts
> +  }
This PR needs to "work" without any caching built in, and ideally without any network-based retries in order to "catch" rate limit issues.

2024-08-13 12:52 UTC, Da-Colon commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +      // @note the build fails if not explicitly defined as a variable
I agree it doesn't.
![image](https://github.com/user-attachments/assets/6d56baf8-203e-409b-a24f-c0f5af7ce814)

This happens in IDE with the first change for both uses. I've tried all sorts of things. If I can get pass the IDE showing the error or the build will catch it.  This was the only thing I found that would work.

2024-08-13 13:09 UTC, Da-Colon commented on src/hooks/utils/useSafeTransactions.ts
> +            // ! @todo This is why we are showing the two different hashes
I'm not following? Why do we need the SafeTxHash?

2024-08-13 13:27 UTC, Da-Colon commented on src/hooks/utils/useSafeTransactions.ts
> +            // ! @todo This is why we are showing the two different hashes
Ah yeah that's why i removed it so that it would only show the transactionHash. In the details screen right after you execute. There would be a clickable transaction hash that shows to the user and takes them to etherscan. But the safeTxHash comes back first so for a while that is what is used in the navigation (which shows nothing on etherscan)

2024-08-13 18:40 UTC, adamgall approved these changes

2024-08-13 18:40 UTC, adamgall commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
> +              {t('created')} {format(proposal.eventDate, DEFAULT_DATE_FORMAT)}
What's happening here? Why do we no longer care about those `t('received')` and `t('sent')` translations?

2024-08-13 18:40 UTC, adamgall commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +          }, 300);
Does this just set single retry, for 300 ms later? and if that one fails, then too bad?

2024-08-13 18:40 UTC, adamgall commented on src/hooks/utils/useSafeTransactions.ts
> +            // ! @todo This is why we are showing the two different hashes
The Safe TX Hash is _all that we have_ when a proposal is "pending" (not executed onchain yet). For Azorius this is never a problem because proposals are onchain, but for Multisig proposals are _not_ onchain so we don't have a transaction to link them to.

@Da-Colon does this track?

@mudrila is the behavior you want to see here currently implemented correctly on prod? dev?

2024-08-13 18:40 UTC, adamgall commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +      // @note the build fails if not explicitly defined as a variable
I think I fixed this by rewriting the code a bit

2024-08-13 18:40 UTC, adamgall commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +          return await safeAPI.getToken(addr);
I still want to see a proper batching implemented here... I'll give the implementation a go myself

2024-08-13 18:41 UTC, adamgall commented
@Da-Colon just gave my approval, however i would like to see all open conversations in this PR resolved before you merge. thank you!

2024-08-13 18:42 UTC, adamgall commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +          return await safeAPI.getToken(addr);
No need to wait on me for this though!

2024-08-13 21:15 UTC, adamgall commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +          return await safeAPI.getToken(addr);
I have something implemented, it's not my fav tho because of... reasons. Would like to screen share with you about it @Da-Colon

2024-08-13 21:46 UTC, Da-Colon commented on src/hooks/utils/useSafeTransactions.ts
> +            // ! @todo This is why we are showing the two different hashes
O we are using it somewhere to track the state of things?

2024-08-13 21:47 UTC, Da-Colon commented on src/components/Proposals/ProposalCard/ProposalCard.tsx
> +              {t('created')} {format(proposal.eventDate, DEFAULT_DATE_FORMAT)}
Those were part of the `transfers` workflow and UI. we no longer need that

2024-08-13 22:17 UTC, Da-Colon commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +          }, 300);
We actually have a hook for this. (if it still in the codebase) `useAsyncRetry`. But to answer your question yes. Only once. This seem to cover most cases and and Decent and Shutter's transfer history loaded quickly with no problems (from a cleared cache).

2024-08-13 22:23 UTC, Da-Colon commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +      // @note the build fails if not explicitly defined as a variable
curious on how you did so

2024-08-13 23:26 UTC, adamgall commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +      // @note the build fails if not explicitly defined as a variable
@Da-Colon check the last commit or two that I pushed!

2024-08-14 02:11 UTC, adamgall commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +          }, 300);
ok, thank you!

2024-08-14 02:14 UTC, adamgall commented on src/hooks/utils/useSafeTransactions.ts
> +            // ! @todo This is why we are showing the two different hashes
well idk if we're using it to track the state of things. I'm just saying that it's the best _identifier_ we _have_ for multisig transactions which haven't executed onchain yet. and there are places in the UI where @mudrila thinks some behavior or information has possibly unexpectedly changed.

2024-08-14 17:15 UTC, merged