Root/state overhaul
decentdao/decent-interface pull request #2242
Opened 2024-08-14 14:31 UTC by adamgall

2024-09-25 21:45 UTC, adamgall commented
@DarksightKellar let's work on this merge conflict tomorrow

2024-11-04 00:14 UTC, adamgall commented
@DarksightKellar in the spirit of killing these long running "root" branches, and in favor of just getting code into `develop` because _why not_, any reason to not merge this?

2024-11-05 15:09 UTC, adamgall commented on src/types/daoTreasury.ts
> -  blockNumber: number; // TODO: PROBABLY not being used. Remove?
Why stop here? Looks like there is _a lot_ of stuff in this file that's not used. Can probably simplify this whole file to:

```ts
export enum TokenEventType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
}

export type TokenBalance = {
  tokenAddress: string;
  symbol: string;
  name: string;
  logo?: string;
  thumbnail?: string;
  decimals: number;
  balance: string;
  possibleSpam?: string | boolean; // Empty string means false lol, but still that's a string
  verifiedContract: boolean;
  balanceFormatted: string; // Balance formatted to decimals
  usdPrice?: number;
  usdValue?: number;
  nativeToken: boolean;
  portfolioPercentage: number;
};

// All these props are coming from *all available DeFi protocols*
interface DefiPositionDetails {
  feeTier?: number;
  rangeTnd?: number;
  reserves?: string[];
  currentPrice?: number;
  isInRange?: boolean;
  priceUpper?: number;
  priceLower?: number;
  priceLabel?: string;
  liquidity?: number;
  rangeStart?: number;
  poolAddress?: string;
  positionKey?: string;
  assetStandard?: string;
  apy?: number;
  isDebt?: boolean;
  isVariableDebt?: boolean;
  isStableDebt?: boolean;
  shares?: string;
  reserve0?: string;
  reserve1?: string;
  factory?: string;
  pair?: string;
  shareOfPool?: number;
  noPriceAvailable?: boolean;
  sharesInStrategy?: string;
  strategyAddress?: string;
  baseType?: string;
  healthFactor?: number;
}

export type DefiPositionTokenBalance = {
  contractAddress?: string;
  tokenType: 'supplied' | 'defi-token';
} & TokenBalance;

type DefiPosition = {
  label: string;
  tokens: DefiPositionTokenBalance[];
  address?: string;
  balanceUsd: number;
  totalUnclaimedUsdValue: number;
  positionDetails?: DefiPositionDetails;
};

export type DefiBalance = {
  protocolName?: string;
  protocolId?: string;
  protocolUrl?: string;
  protocolLogo?: string;
  position?: DefiPosition;
};

type NftMediaItem = {
  height: number;
  width: number;
  url: string;
};

export type NFTBalance = {
  tokenAddress: string;
  media:
    | {
        originalMediaUrl?: string | undefined;
        mediaCollection?:
          | {
              low: NftMediaItem;
              medium: NftMediaItem;
              high: NftMediaItem;
            }
          | undefined;
      }
    | undefined;
  metadata?: {
    backgroundImage?: string;
    image?: string;
    imageUrl?: string;
  };
  tokenId: string | number;
  tokenUri?: string | undefined;
  name?: string | undefined;
  symbol?: string | undefined;
  amount?: number | undefined;
  possibleSpam: boolean;
};

export enum TransferType {
  ETHER_TRANSFER = 'ETHER_TRANSFER',
  ERC20_TRANSFER = 'ERC20_TRANSFER',
  ERC721_TRANSFER = 'ERC721_TRANSFER',
}

```

2024-11-05 15:10 UTC, DarksightKellar commented on src/types/daoTreasury.ts
I've just gotten rid of some seemingly unused code in this file. Plz verify

2024-11-05 15:10 UTC, DarksightKellar commented on src/components/ui/page/Layout/index.tsx
idk what I want to do with the changes in this file lol. I'm inclined toward reverting, since again they're not fixing some glaring bug on prod. Whatever bug fix this works on, I expect to be fixed in the upcoming housekeeping work we're pushing for.

2024-11-05 15:11 UTC, DarksightKellar commented on src/types/daoTreasury.ts
> -  blockNumber: number; // TODO: PROBABLY not being used. Remove?
Do we match? See: https://github.com/decentdao/decent-interface/pull/2242#discussion_r1829524307

2024-11-05 15:12 UTC, adamgall commented on src/hooks/DAO/loaders/useHatsTree.ts
> +
Sure thing, undo it.

2024-11-05 15:17 UTC, adamgall commented on src/components/pages/DaoHierarchy/DaoHierarchyNode.tsx
>    }, []);
Is this function used anywhere? Doesn't look like it.

2024-11-05 15:21 UTC, adamgall commented on src/components/pages/DaoHierarchy/DaoHierarchyNode.tsx
>    }, []);
Have you confirmed that DAO Hierarchies still load correctly?

2024-11-05 15:26 UTC, DarksightKellar commented on src/components/pages/DaoHierarchy/DaoHierarchyNode.tsx
>    }, []);
Ah nice. Removed.

2024-11-05 15:27 UTC, adamgall commented on src/hooks/DAO/loaders/useLoadDAONode.ts
> -          // even if `daoAddress` passes the isAddress check above
I don't know if reverting this is ok.

Follow up the chain. The `daoAddress` could be coming from the subgraph-loaded data, which AFAIKT might not have been checksummed before it got to this point.

2024-11-05 15:36 UTC, adamgall commented on src/components/pages/DaoSettings/components/Signers/modals/AddSignerModal.tsx
> +      }
Yeah move errors up to as high as they can be

2024-11-05 18:34 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useFractalNode.ts
> -    (result: { data?: DAOQueryQuery }, _daoAddress: Address) => {
My original comment was actually slightly incorrect. `safeAddress` comes from the argument to the containing `useFractalNode` hook, which itself is used only in `useDAOController`. The `safeAddress` in there comes from the url.

Originally `formatDAOQuery` was called and its `_daoAddress` param was simply the `useFractalNode.daoAddress` argument, something like this:

`const graphNodeInfo = formatDAOQuery({ data }, daoAddress);`

2024-11-05 18:50 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useLoadDAONode.ts
> -          // even if `daoAddress` passes the isAddress check above
Okay so I followed the call chain up to `mapChildNodes`. See this commit: https://github.com/decentdao/decent-interface/pull/2242/commits/67782d9e361bc00669061d42b97712fdc3719118

Doesn't seem like there's anywhere else that needs patching up

2024-11-05 18:51 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useLoadDAONode.ts
> +  // @todo There's a near duplicate of this function in useFractalNode.ts. DRY?
Flagging this for clarity and hoping we can DRY it up

2024-11-05 18:51 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useFractalNode.ts
> +  // @todo: There's a near duplicate of this function in useLoadDAONode.ts. DRY?
Flagging this for clarity and hoping we can DRY it up

2024-11-06 17:26 UTC, adamgall commented on src/hooks/DAO/loaders/useLoadDAONode.ts
> -          // even if `daoAddress` passes the isAddress check above
Sounds good to me

2024-11-06 17:27 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> -    (result: { data?: DAOQueryQuery }, _daoAddress: Address) => {
Sounds good to me

2024-11-07 17:01 UTC, mudrila approved these changes

2024-11-11 18:25 UTC, DarksightKellar commented
@adamgall @Da-Colon Feel good about getting this merged in?

2024-11-11 19:05 UTC, adamgall commented on package.json
> +    "@fractal-framework/fractal-contracts": "^1.2.17",
@DarksightKellar no i do not feel comfortable about merging this in lol

2024-11-11 19:54 UTC, DarksightKellar commented on package.json
> +    "@fractal-framework/fractal-contracts": "^1.2.17",
Botched merge huh

2024-11-12 01:09 UTC, adamgall commented on package-lock.json
@DarksightKellar if there are no changes to `package.json` there should be no changes in this lock file either.

2024-11-12 08:01 UTC, Da-Colon requested changes
Looks good. One comment about the todo

As far as `useFractalNode`. Nothing concerning stands out with the changes in there. With those changes, would need to stress test switching to different DAOs. 

Switching DAOs via search and favorites seems to be working fine.

But when directly change the address in the URL and I mistype (like leave off a letter in address) I am created with a white out screen until I get 'This page is unresponsive' popup. On Dev, I get ErrorBoundary

2024-11-12 16:05 UTC, DarksightKellar commented on src/components/ui/links/EtherscanLink.tsx
> +  value: string | null; // TODO: prefer `value?: Hex | bigint`
I don't even remember the original reasoning here, it's been months lol. 

...

Ah yes, if type is `block`, then value would be a block number. `address`, `token` and `tx` would be `Hex`. Didn't want to stick with `string` type and then `toString()`-ing everything because that'd be too broad. Enforce a `Hex` or `bigint` and do the string conversion here instead.

I should actually do that in this PR ig

2024-11-12 20:10 UTC, adamgall commented on src/hooks/DAO/useDAOController.ts
> +
Why this @Da-Colon @DarksightKellar ?

I don't think we ahve the appropriate error boundaries set up to catch this, and and "invalid query" in this context just means that the user might have mistyped the `dao` url query param. Do we really want to throw an error here?

2024-11-12 20:12 UTC, Da-Colon approved these changes

2024-11-12 20:24 UTC, merged