Normalise `daoSnapshotENS` to lower case
decentdao/decent-interface pull request #2247
Opened 2024-08-14 17:37 UTC by mudrila

Closes #2234

2024-08-14 20:27 UTC, adamgall requested changes
Didn't go through the whole PR yet, but saw enough to stop.

Please see my comments! Thank you sir

2024-08-14 20:27 UTC, adamgall commented on src/components/Proposals/ProposalInfo.tsx
> +              snapshotENS={`${daoSnapshotENS?.toLowerCase()}/proposal/${proposal.proposalId}`}
Hmm, I think we shouldn't touch this one. Let's assume that the data onchain is accurate for now.

2024-08-14 20:27 UTC, adamgall commented on src/components/DaoCreator/formComponents/EstablishEssentials.tsx
> +        setFieldValue('essentials.snapshotENS', daoSnapshotENS?.toLowerCase() || '', false);
Again here, I think we should leave this alone.

2024-08-14 20:27 UTC, adamgall commented on src/components/pages/DaoSettings/components/MetadataContainer.tsx
> +      setSnapshotENS(daoSnapshotENS.toLowerCase());
This is another spot where we're reading `daoSnapshotENS` from state, which came from what was onchain. Let's leave this alone, and assume that whatever was onchain and now is in state, is valid and accurate.

I want this PR to only touch the places where users are actively entering an ENS name. Only on that input action should we be normalizing into lowercase.

2024-08-14 20:57 UTC, adamgall commented on src/components/DaoCreator/formComponents/EstablishEssentials.tsx
> +        setFieldValue('essentials.snapshotENS', daoSnapshotENS?.toLowerCase() || '', false);
But my point is that if someone is putting something non-normalized onchain, they're doing that _outside_ of our UI, and therefore who are we to assume it's wrong?

2024-08-14 21:02 UTC, adamgall commented on src/components/pages/DaoSettings/components/MetadataContainer.tsx
> +      setSnapshotENS(daoSnapshotENS.toLowerCase());
Hm i think we just inherently disagree on this one.

The root of my position is that the reach of our responsibility should include only what people actually do within our app.

A `WiErD.eth` address is technically valid in ENS. ENS tooling convention is to direct users towards all-lowercase when entering/creating ENS names. But what's on-chain is on-chain, and it's NOT WRONG if it's non-normalized.

Just because the ENS name has capital letters in it doesn't immediately mean our app will become buggy.

I'd like other's take on this @Da-Colon @DarksightKellar

2024-08-15 14:38 UTC, Da-Colon commented on src/components/pages/DaoSettings/components/MetadataContainer.tsx
> +      setSnapshotENS(daoSnapshotENS.toLowerCase());
hmmm We are not currently creating ENS name in the app, and in IMO, seems like we shouldn't try to mess with what is coming from onchain (to Adam's point). 

As far as ENSSnapshot, I don't think have a big opinion but I always lead to standards. Since this is something that is saved to our stuff. might be a good idea to just add a quick change to the one input to prevent uppercase letters from the git go and call it a day.

2024-08-15 15:05 UTC, DarksightKellar commented on src/components/pages/DaoSettings/components/MetadataContainer.tsx
> +      setSnapshotENS(daoSnapshotENS.toLowerCase());
Yeahh I'm on the same page as the others -- don't touch what's already onchain. If some user somewhere _intentionally_ set a `wEiRdEnS.eth` outside of conventional/standard UI, they probably want to see it everywhere.

I don't see any issue at all with showing such mixed casing in-app -- that's not our responsibility, no will it cause any bug. At the same time there's still merit in keeping with established standards when the input comes _from_ Decent.

2024-08-15 15:14 UTC, DarksightKellar requested changes
In the same theme of the ongoing discussion on this PR, I'd much rather the "lower-casing" happens only when it is input from the user via the Decent app.

Thus, as long as the ENS string came from Decent, it should be _guaranteed_ to be lower case, so we should not need to lower case them anywhere else in-app. If it _happens_ to be mixed case, it is most certainly not originally from Decent (at least after this PR goes live), and I don't think we have any business insisting that is MUST be lowercase for whoever decided (or whatever) they'd like their name non-standardised.

2024-08-15 20:00 UTC, adamgall commented on src/components/DaoCreator/formComponents/EstablishEssentials.tsx
> +        setFieldValue('essentials.snapshotENS', daoSnapshotENS?.toLowerCase() || '', false);
Sorry ser you're outnumbered 3 to 1

2024-08-15 20:01 UTC, adamgall commented on src/components/Proposals/ProposalInfo.tsx
> +              snapshotENS={`${daoSnapshotENS?.toLowerCase()}/proposal/${proposal.proposalId}`}
Sorry ser you're outnumbered 3 to 1

2024-08-15 20:08 UTC, adamgall requested changes

2024-08-15 20:08 UTC, adamgall commented on src/components/ui/cards/DAOInfoCard.tsx
> +        {node.daoSnapshotENS && <SnapshotButton snapshotENS={node.daoSnapshotENS.toLowerCase()} />}
Remove this `.toLowerCase()`

2024-08-15 20:08 UTC, adamgall commented on src/components/ui/cards/DAONodeInfoCard.tsx
> +              <SnapshotButton snapshotENS={node.daoSnapshotENS.toLowerCase()} />
Remove this `.toLowerCase()`

2024-08-15 20:08 UTC, adamgall commented on src/hooks/DAO/loaders/snapshot/useSnapshotSpaceName.ts
> +  return daoSnapshotENS?.toLowerCase();
Remove this `.toLowerCase()`

2024-08-15 20:08 UTC, adamgall commented on src/hooks/DAO/loaders/useFractalNode.ts
> +          daoSnapshotENS: snapshotENS?.toLowerCase() as string,
Remove this `.toLowerCase()`

2024-08-15 20:08 UTC, adamgall commented on src/hooks/DAO/loaders/useLoadDAONode.ts
> +          daoSnapshotENS: snapshotENS?.toLowerCase() as string,
Remove this `.toLowerCase()`

2024-08-15 20:08 UTC, adamgall commented on src/hooks/utils/useAvatar.ts
> +    name: name?.toLowerCase(),
Remove this `.toLowerCase()`

2024-08-15 20:08 UTC, adamgall commented on src/models/DaoTxBuilder.ts
> +      [['snapshotENS'], [this.daoData.snapshotENS.toLowerCase()]],
Remove this `.toLowerCase()`.

I want the `.toLowerCase()` to happen much closer to the actual input component.

2024-08-16 12:12 UTC, DarksightKellar commented on src/hooks/DAO/loaders/snapshot/useSnapshotProposal.ts
> +        Object.keys(choices).forEach((_choice: string, choiceIndex) => {
The beers ma dude

2024-08-16 13:01 UTC, DarksightKellar requested changes
I might be missing something, but is the snapshot input field in this screenshot covered by this PR (or is something else entirely lowercasing that value)?
<img width="900" alt="Screenshot 2024-08-16 at 14 00 50" src="https://github.com/user-attachments/assets/1af45643-b9ee-4cbc-af07-0ff8c595d97f">

2024-08-16 16:12 UTC, adamgall commented
@DarksightKellar i would expect that these two inputs are the two places that this PR should touch. What change are you requesting?

2024-08-16 16:15 UTC, adamgall requested changes
@mudrila maybe this is why @DarksightKellar requested changes... does this PR do anything anymore? It doesn't seem like any of the changes here do the thing I was looking for: lowercasing text typed into those two input fields Kelvin screenshotted

2024-08-17 01:35 UTC, adamgall approved these changes

2024-08-17 01:35 UTC, merged