`2230` handoff role details
decentdao/decent-interface pull request #2250
Opened 2024-08-15 06:06 UTC by Da-Colon

Branched off: #2235 
Closes #2230 

Adds New Payments UI

## Screenshots
![localhost_8888_roles_details_dao=sep_0xd6Cb633E3A9cDEbA8a7A5CA4F30436F10FEbd418 hatId=0x0000016300010005000000000000000000000000000000000000000000000000(Desktop)](https://github.com/user-attachments/assets/ed8170c1-ea6e-4d30-9176-85069b6528c7)

![localhost_8888_roles_details_dao=sep_0xd6Cb633E3A9cDEbA8a7A5CA4F30436F10FEbd418 hatId=0x0000016300010005000000000000000000000000000000000000000000000000(Mobile)](https://github.com/user-attachments/assets/23730262-85a4-43f3-8aa5-10b798c0ab5d)

![localhost_8888_roles_details_dao=sep_0xd6Cb633E3A9cDEbA8a7A5CA4F30436F10FEbd418 hatId=0x0000016300010005000000000000000000000000000000000000000000000000(Desktop) (1)](https://github.com/user-attachments/assets/3b3ac5d8-2c0f-48a9-8d66-d6c68d84bad9)

2024-08-15 16:39 UTC, adamgall requested changes

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormTabs.tsx
> +  const tabIndex = searchParams.get('tab') ? parseInt(searchParams.get('tab') as string) : 0;
Instead of a query string parameter (which is a key value pair), could you use "fragments"?

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +          });
Could this be a "fragment" instead of search param?

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +            });
Could this be a "fragment" instead of search param?

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +          if (!values?.roleEditing?.payments || !hatsTree) return;
Can we make it so the button is disabled if these same conditions are true?

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +          const foundRole = hatsTree.roleHats.find(role => role.id === values?.roleEditing?.id);
There's a function in the `useRolesStore()` object called `getHat` which does this.

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +            );
Might be nice to create a function in the store to help with this, too

Signature might be: `getPayment(hatId, streamId)`

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +  }, [payment.amount, payment.scheduleFixedDate, isStreamActive]);
I have two things to say about this code:

1. I'd prefer a slightly different method for calculating "amount per weeK".
  1. Calculate total number of seconds (total_sec = end - start)
  1. Calculate amount per second (amt_per_sec = total_amt / total_sec)
  1. Multiply by seconds in a week to alculate amount per week (amt_per_week = amt_per_sec * 60 * 24 * 7)
2. Calling out that if there is a cliff, or if the "payment curve" is anything but a straight line, displaying an "amount per week" might not have enough context to be accurate or make sense (cc: @nicolaus-sherrill @tomstuart123)

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +    return Number(totalAmount) * foundAsset.usdPrice;
At first glance it doesn't seem safe to just cast `totalAmount` as a `Number`.

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +                ? Intl.NumberFormat(undefined).format(Number(payment.amount.value))
Nit: you can just do `Intl.NumberFormat().format(...)` right?

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +                {`${amountPerWeek} ${payment.asset.symbol} / week`}
This "week" needs to go into translations file

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +  payment: SablierPayment;
This `SablierPayment` type doesn't seem appropriate for displaying Stream data... What happens in the component when the stream was created via "duration"?

What I'm getting at is, why do we have any object types for Sablier streams (beyond the input form itself), which "separate" the type of schedule for an _existing stream_?

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +      ]);
Are we sure that the full identifier of a stream (for when looking up the withdrawable amount of the stream) is only that last section of the "streamId"? Seems weird...

Also this async call doesn't need to be in a Promise.all

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +      payment.scheduleFixedDate.endDate.getTime() < new Date().getTime()
What if `scheduleFixedDate` is undefined? How will we know if the stream is active?

Also, doesn't Sablier tell us if a stream is active when we fetch that data from their subgraph? We should be using that, not recalculating this ourselves.

2024-08-15 16:39 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +    const numberOfWeeks = Math.ceil((endDate - startDate) / (1000 * 60 * 60 * 24 * 7));
What if `scheduleFixedDate` is undefined?

2024-08-15 18:02 UTC, xraystyle1980 commented
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjZiZTNhYjQwMTZjODYwMDA4M2M3ZGI4IiwiaWQiOiJmMGUxZmM0YS0zODA0LTQ0M2YtOTY3Zi04M2Q3M2FlYWI5MjAifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/details?dao=sep:0x4981782CD8667216a2D51178E6a82Dc8169982a2&hatId=0x000001c600010001000000000000000000000000000000000000000000000000
Browser:   Chrome 127.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2250.app.dev.decentdao.org%2Froles%2Fedit%2Fdetails%3Fdao%3Dsep%3A0x4981782CD8667216a2D51178E6a82Dc8169982a2%26hatId%3D0x000001c600010001000000000000000000000000000000000000000000000000&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=127.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2250.app.dev.decentdao.org/roles/edit/details?dao=sep:0x4981782CD8667216a2D51178E6a82Dc8169982a2&hatId=0x000001c600010001000000000000000000000000000000000000000000000000) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=66be3ab4016c8600083c7db8&commentID=66be42c5832d570fb4f48adc&resolution=resolved)

2024-08-15 18:10 UTC, xraystyle1980 commented
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjZiZTNhYjQwMTZjODYwMDA4M2M3ZGI4IiwiaWQiOiJkOGE1ODkwMC0wYjJmLTRiMjgtYTg1Ni1iMWE3MmE4NTVhNDUifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/details?dao=sep:0x4981782CD8667216a2D51178E6a82Dc8169982a2&hatId=0x000001c600010001000000000000000000000000000000000000000000000000
Browser:   Chrome 127.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2250.app.dev.decentdao.org%2Froles%2Fedit%2Fdetails%3Fdao%3Dsep%3A0x4981782CD8667216a2D51178E6a82Dc8169982a2%26hatId%3D0x000001c600010001000000000000000000000000000000000000000000000000&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=127.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2250.app.dev.decentdao.org/roles/edit/details?dao=sep:0x4981782CD8667216a2D51178E6a82Dc8169982a2&hatId=0x000001c600010001000000000000000000000000000000000000000000000000) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=66be3ab4016c8600083c7db8&commentID=66be4484f0169f140f266064&resolution=resolved)

2024-08-15 18:42 UTC, Da-Colon commented on src/components/pages/Roles/forms/RoleFormTabs.tsx
> +  const tabIndex = searchParams.get('tab') ? parseInt(searchParams.get('tab') as string) : 0;
check latest commit, that what you are looking for?

2024-08-15 19:00 UTC, Da-Colon commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +      ]);
@mudrila I only edited, can you answer this one?

@adamgall yeah opps left the `Promise.all`

2024-08-15 19:04 UTC, Da-Colon commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +  payment: SablierPayment;
yeah this and your other comment about scheduleFixedRate. 

Currently been thinking about this. for existing payments I have some functions that takes scheduleFixedDates (How we first receive from subgraph) and figure out duration (so the form looks correct). 

So currently the UI in design only has 'fixed' dates start and end times and cliff. We can add some functionality to do some converting to the other when one or the other is updated. But I can spin off this branch to do this work as I need to think through things

2024-08-15 19:04 UTC, Da-Colon commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +      payment.scheduleFixedDate.endDate.getTime() < new Date().getTime()
See above answer. https://github.com/decentdao/decent-interface/pull/2250#discussion_r1718868603

2024-08-15 19:04 UTC, Da-Colon commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +    const numberOfWeeks = Math.ceil((endDate - startDate) / (1000 * 60 * 60 * 24 * 7));
see https://github.com/decentdao/decent-interface/pull/2250#discussion_r1718868603

2024-08-15 19:54 UTC, Da-Colon commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +    return Number(totalAmount) * foundAsset.usdPrice;
What do you suggest?

2024-08-15 19:58 UTC, xraystyle1980 commented
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjZiZTU3OTYxOWVmY2IwMDA4ZjkyZTg3IiwiaWQiOiIxOGExMTA1NC0xZDRiLTRiMTctYmY5ZC02OTkwNjBlZmVjZmIifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /roles/edit/details?dao=sep:0x4981782CD8667216a2D51178E6a82Dc8169982a2&hatId=0x000001c600010001000000000000000000000000000000000000000000000000
Browser:   Chrome 127.0.0.0 on Mac OS 10.15.7
Viewport:  1708 x 1027 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2250.app.dev.decentdao.org%2Froles%2Fedit%2Fdetails%3Fdao%3Dsep%3A0x4981782CD8667216a2D51178E6a82Dc8169982a2%26hatId%3D0x000001c600010001000000000000000000000000000000000000000000000000&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=127.0&resolution=1708x1027&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2250.app.dev.decentdao.org/roles/edit/details?dao=sep:0x4981782CD8667216a2D51178E6a82Dc8169982a2&hatId=0x000001c600010001000000000000000000000000000000000000000000000000) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=66be579619efcb0008f92e87&commentID=66be5dd750dbc62cf81e1d94&resolution=resolved)

2024-08-15 20:19 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormTabs.tsx
> +  const tabIndex = searchParams.get('tab') ? parseInt(searchParams.get('tab') as string) : 0;
I mean, kinda? How exactly are these supposed to work?

2024-08-15 20:21 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +  payment: SablierPayment;
I would like to think through those things with you @Da-Colon , let me know when you want to jam on it

2024-08-15 20:21 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +      ]);
oke

2024-08-15 20:23 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +      payment.scheduleFixedDate.endDate.getTime() < new Date().getTime()
What about the other part of my question? Doing our own calculation to determine if a stream is active. I thought that we want to reduce the 5 states that Sablier gives us, down into a binary "active"/"inactive" states. I would expect that happens in our state/store layer, not in a component like this.

2024-08-15 20:27 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +    return Number(totalAmount) * foundAsset.usdPrice;
Since `totalAmount` can be bigger than a `Number` type, you can't just cast it as a `Number`. You'll have to do math in `bigint`s then convert to a string when you're finished.

2024-08-16 00:08 UTC, Da-Colon commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +      payment.scheduleFixedDate.endDate.getTime() < new Date().getTime()
I'll check and get this updated.

2024-08-16 13:45 UTC, Da-Colon commented
> ![recording](https://camo.githubusercontent.com/8bbb14c4caf90b1eae82dcf893c7f4c53d973b7c24c3895da51b0ce69ed00e08/68747470733a2f2f6e65746c6966792d636f636f6f6e2e6e65746c6966792e6170702f2e6e65746c6966792f66756e6374696f6e732f66657463683f636f64653d33303726706174683d65794a7a6158526c58326c6b496a6f6959324e685a44466d5a6d55745a4455345a5330304d6a4d344c574a695932457459324d774f544d784e5467314e574e6d496977695a4756776247393558326c6b496a6f694e6a5a695a5455334f5459784f57566d593249774d4441345a6a6b795a54673349697769615751694f6949784f4745784d5441314e4330785a4452694c5452694d546374596d59355a4330324f546b774e6a426c5a6d566a5a6d496966513d3d)
> 
> * Unable to save role with payment
> * I can see my TTT token but am unable to save any type of payment option setup (save stays grayed out)
> * Calendar z-index looks to be behind some of the drawer typography
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-2250.app.dev.decentdao.org/roles/edit/details?dao=sep:0x4981782CD8667216a2D51178E6a82Dc8169982a2&hatId=0x000001c600010001000000000000000000000000000000000000000000000000) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=66be579619efcb0008f92e87&commentID=66be5dd750dbc62cf81e1d94&resolution=resolved)

@xraystyle1980 coolio found a unrelated bug in the Fixed Date test. Should work now

2024-08-16 14:04 UTC, DarksightKellar approved these changes

2024-08-16 16:22 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +  payment: SablierPayment;
we're going to remove the "duration" tab entirely.

2024-08-16 16:23 UTC, adamgall commented on src/hooks/schemas/roles/useRolesSchema.ts
> +                                  if (!_scheduleDuration) return true;
Was this is a bug before?

2024-08-16 17:19 UTC, Da-Colon commented on src/hooks/schemas/roles/useRolesSchema.ts
> +                                  if (!_scheduleDuration) return true;
yeah won't matter now that its all getting deleted

2024-08-16 17:50 UTC, adamgall requested changes

2024-08-16 17:50 UTC, adamgall commented on src/hooks/DAO/loaders/useHatsTree.ts
> +                      new Date().getTime(),
For the purposes of displaying streams, conversations between product/design/engineering resulted in:
- streams would be "active" or "inactive"
- these two statuses would be a reduction of two (or three?) of the states defined here (but I forget which ones): https://docs.sablier.com/concepts/protocol/statuses

However, it appears that Sablier's subgraph doesn't expose a property called "status" (or something like that). So IDK where that comes from. We might have to figure it out ourselves?

see: https://github.com/sablier-labs/v2-subgraphs/blob/main/apps/protocol/schema.graphql

So, we need to _probably_ do a bit more logic here to figure out the proper states.

Also, I had previously said that we could dynamically show the green dot. Pseudocode:

```
if (stream.status == active ||
    (stream.status == over && stream.avail_to_claim > 0 && stream.recipient == current_user)) {
  green_dot.on = true
} else {
  green.dot.on = false
}

2024-08-16 17:50 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +  }
Will go look at how it's used next, but this seems kinda weird no?

2024-08-16 17:50 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +    const totalAmount = Number(payment.amount.value);
Can't do this 🙅

2024-08-16 17:50 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +    const roundedWeeks = Math.ceil(totalWeeks);
Why do you need this?

2024-08-16 17:50 UTC, adamgall commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +    return totalAmount * BigInt(foundAsset.usdPrice);
`foundAssets.usePrice` is a `number`. I _assume_ its a `number` representing US Dollars. So, if the token price is $0.83, `foundAsset.usdPrice` is `0.83`, which also probably doesn't cast very well into a `BigInt` (I'd bet the resulting value is either 0 or 1, if not outright throwing an error).

2024-08-16 17:50 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +          if (!values?.roleEditing?.payments || !hatsTree) return;
Plz ser

2024-08-16 17:50 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +          }
```ts
const isExistingPayment =
  values?.roleEditing?.payments?.[formIndex].streamId &&
  getPayment(
    values.roleEditing.id,
    getAddress(values.roleEditing.payments[formIndex].streamId),
  );
```

2024-08-16 17:50 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +            navigate(`${currentPath}#tab1`);
leftover?

2024-08-16 17:56 UTC, Da-Colon commented on src/components/pages/Roles/RolePaymentDetails.tsx
> +    const roundedWeeks = Math.ceil(totalWeeks);
else you get `6.999932344` for weeks and that doesn't show the correct value.

2024-08-16 18:02 UTC, Da-Colon commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +          if (!values?.roleEditing?.payments || !hatsTree) return;
?

2024-08-16 20:21 UTC, adamgall approved these changes

2024-08-16 20:22 UTC, merged