`state-overhaul` | Refactor resolve address logic
decentdao/decent-interface pull request #2251
Opened 2024-08-15 10:39 UTC by DarksightKellar

I found that the `validAddress`-obtaining logic was also needed in 2 places in `DelegateModal`. So I've refactored that so we can reuse, as `resolveAddress`.

2024-08-15 19:56 UTC, adamgall requested changes

2024-08-15 19:56 UTC, adamgall commented on src/components/ui/modals/DelegateModal.tsx
> +
I would say it doesn't make sense that the `values.address` `string` being passed in as input would be the ENS name. I understand that right now it _is_ like that, but that seems wasteful and inefficient.

The input is _already_ doing ENS name resolution on the input, so by the time the user clicks the button (which triggers this function), we've _already_ resolved the actual address. No reason to need to resolve it again here.

2024-08-15 19:58 UTC, adamgall commented on src/utils/address.ts
> +      throw new Error('Given ENS name does not resolve to an address.');
Eh, these errors will be caught up the stack eventually. They're not expected to happen in the normal execution flow, so I think it's fine to ignore it here and let some higher layer capture it.

2024-08-15 19:59 UTC, adamgall commented on src/utils/address.ts
> +    try {
Great question! we totally don't lol

2024-08-16 09:10 UTC, DarksightKellar commented on src/utils/address.ts
> +    try {
Yep lol

2024-08-16 11:42 UTC, DarksightKellar commented on src/components/ui/modals/DelegateModal.tsx
> +
I don't understand this. I don't see where in the code `values.address` would get updated to a valid address, so that it could not be an ENS by the time `submitLockedDelegation` is called

2024-08-16 12:09 UTC, DarksightKellar commented on src/utils/address.ts
> +      throw new Error('Given ENS name does not resolve to an address.');
I've updated this function to return null in this "does-not-resolve-to-address" case. It will continue throwing for the provider not found exception below. Its consumers now handle both cases, and show a toast to that effect.

2024-08-19 19:20 UTC, adamgall commented
@DarksightKellar what else needs to happen in this PR?

2024-08-20 13:16 UTC, DarksightKellar commented
> @DarksightKellar what else needs to happen in this PR?

@adamgall I think this is ready to go

2024-08-29 14:09 UTC, adamgall commented on src/components/ui/modals/DelegateModal.tsx
> +
Update: harder to implement than hoped. the input-level validation is happening through a Yup validation test, which only returns true/false. Can't pull more data out of that validation test.

2024-08-29 14:09 UTC, adamgall approved these changes

2024-08-29 14:10 UTC, merged