Add typing for form values for Payments
decentdao/decent-interface pull request #2263
Opened 2024-08-17 21:54 UTC by Da-Colon

While working on #2262 (Last commit). I noticed that values being properties into the components as `SablierPayment` but our typed different as each value in the form can be 'undefined'. I've added a new typing that extends `SablierPayment` with `Partial` then updated the other components accordingly.

2024-08-18 17:54 UTC, Da-Colon commented on src/hooks/utils/useCreateRoles.ts
> +  return {
This isn't for validating payment. this is for Taking the Form Type `SablierPaymentFormValue` and Converting it properly to `SablierPayment`.

2024-08-18 17:56 UTC, Da-Colon commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +              getAddress(values.roleEditing.payments[formIndex].streamId ?? ''),
right. but we don't have any other way to `string` -> `'0x${string}`` type. (Which all Hex is) and I didn't want to use `as`

2024-08-18 23:29 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +              getAddress(values.roleEditing.payments[formIndex].streamId ?? ''),
Why would you need to use `as`?  Kirill's point (I think) is that this is just a regular string which is not a hex string.

2024-08-19 00:31 UTC, Da-Colon commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +              getAddress(values.roleEditing.payments[formIndex].streamId ?? ''),
O We have hatId typed as `Hex` in the app

2024-08-19 00:33 UTC, Da-Colon commented on src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
> +              getAddress(values.roleEditing.payments[formIndex].streamId ?? ''),
I first responded we have streamId typed as Hex. But I typed it that way for `getPayment`. caught up. updating

2024-08-19 12:27 UTC, DarksightKellar requested changes

2024-08-19 12:27 UTC, DarksightKellar commented on src/components/pages/Roles/types.tsx
> +  payments?: (SablierPayment | SablierPaymentFormValues)[];
This might be overkill (or not actually) but wdyt about exporting and instead using something like a `const SablierPaymentWithPartials = SablierPayment | SablierPaymentFormValues`?

2024-08-19 12:27 UTC, DarksightKellar commented on src/hooks/utils/useCreateRoles.ts
> +          (role.payments ?? []).map(payment => normalizePaymentFormData(payment)),
Is the exception (line 48) from inline usages of `normalizePaymentFormData` here and above gracefully handled higher up elsewhere? If not we should be doing that. If we expect `payment` to logically have had all its properties be fully define by the time we're here, then `normalizePaymentFormData` should probably be used before this point. Thoughts?

2024-08-19 12:28 UTC, DarksightKellar requested changes
LGMT, I suggested a minor update and raised a question on error handling. Good to merge after resolved

2024-08-19 13:22 UTC, Da-Colon commented on src/components/pages/Roles/types.tsx
> +  payments?: (SablierPayment | SablierPaymentFormValues)[];
Idk. I thought about it for sure. 🤷 sure I'll do it.

2024-08-19 13:22 UTC, Da-Colon commented on src/hooks/utils/useCreateRoles.ts
> +          (role.payments ?? []).map(payment => normalizePaymentFormData(payment)),
hmm I'll look at it

2024-08-19 15:12 UTC, DarksightKellar commented on src/hooks/utils/useCreateRoles.ts
> +          (role.payments ?? []).map(payment => normalizePaymentFormData(payment)),
Gonna delve into this in a follow up

2024-08-19 15:13 UTC, DarksightKellar approved these changes

2024-08-19 15:13 UTC, adamgall approved these changes

2024-08-19 15:13 UTC, merged