Add send assets action to roles proposal
decentdao/decent-interface pull request #2351
Opened 2024-09-16 17:37 UTC by adamgall

WIP

2024-09-18 20:35 UTC, nicolaus-sherrill approved these changes
Lovely. Simply lovely.

2024-09-19 12:26 UTC, DarksightKellar requested changes

2024-09-19 12:26 UTC, DarksightKellar commented on src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
> +  const { isOpen: isOpenAssets, onOpen: onOpenAssets, onClose: onCloseAssets } = useDisclosure();
Duplicate of 191

2024-09-19 12:48 UTC, DarksightKellar commented
@adamgall  Just tested the UI, looks sweet. I noticed there's no "disabled" look for these action buttons:
<img width="607" alt="Screenshot 2024-09-19 at 13 47 22" src="https://github.com/user-attachments/assets/b0f584a0-2131-4bea-a7f2-a2a53010ea1f">

I had to look at the code before I realised I was trying to test on a safe without any balance on a fungible asset

2024-09-19 13:38 UTC, adamgall commented on src/components/pages/DAOTreasury/prepareSendAssetsProposalData.ts
Agreed

2024-09-19 13:47 UTC, adamgall commented on src/components/ui/modals/SendAssetsModal.tsx
> +  nonceInput: number | undefined; // this is only releveant when the caller action results in a proposal
Not going to do this, the other components in the app that this property is being passed into expect `nonceInput` to be undefined, not null. Just going to keep following these patterns.

2024-09-19 13:47 UTC, adamgall commented on src/components/ui/modals/ModalBase.tsx
> +  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl' | '6xl' | 'full';
agreed

2024-09-19 13:52 UTC, adamgall commented
> @adamgall Just tested the UI, looks sweet. I noticed there's no "disabled" look for these action buttons: <img alt="Screenshot 2024-09-19 at 13 47 22" width="607" src="https://private-user-images.githubusercontent.com/7101382/368993680-b0f584a0-2131-4bea-a7f2-a2a53010ea1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTMzNTksIm5iZiI6MTcyNjc1MzA1OSwicGF0aCI6Ii83MTAxMzgyLzM2ODk5MzY4MC1iMGY1ODRhMC0yMTMxLTRiZWEtYTdmMi1hMmE1MzAxMGVhMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMTMzNzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg4YmVmYWUyZmYwODg5YjI2YTI5Y2Q0ZTI0N2QxNTdiYTU1NWFlMTZhODZhZmE3YmY1ZmYxYWQwM2QxM2JmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TFtKjHpCepGsmFwu_QHU3IBMd8b1side7lvBcpAX5Ck">
> 
> I had to look at the code before I realised I was trying to test on a safe without any balance on a fungible asset

Good find, will fix

2024-09-19 14:11 UTC, DarksightKellar commented on src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
> +  const { isOpen: isOpenAssets, onOpen: onOpenAssets, onClose: onCloseAssets } = useDisclosure();
Oh lmaoo that's true

2024-09-19 15:13 UTC, adamgall commented on src/components/pages/Roles/RoleCard.tsx
> +    >
Give this thing a pointer finger because it's clickable. This honestly should be a `button` element but whatever.

2024-09-19 15:14 UTC, adamgall commented on src/components/pages/Roles/RoleCard.tsx
> +            color="lilac-0"
Just something else I noticed, unrelated to this PR. This icon had the wrong color.

2024-09-19 15:18 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
> +      ))}
Yeah like right here. I think it'd be cool if the `values.actions` array items included an instance of the actual component to render, so we didn't need to create instances of them right here. Let the modal/action create instances of the action UI that should be shown on the caller.

2024-09-19 16:15 UTC, DarksightKellar commented on src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
> +
Agreed

2024-09-19 16:17 UTC, DarksightKellar approved these changes
🔥

2024-09-20 08:07 UTC, Da-Colon approved these changes
Code approved, functionally tested

2024-09-20 12:04 UTC, merged