Freeze updates
decentdao/decent-interface pull request #2356
Opened 2024-09-18 14:55 UTC by DarksightKellar

Mostly bug fixes and some light refactoring from testing freeze and clawback functionality on the remove typechain branch

2024-09-18 14:59 UTC, adamgall commented on src/i18n/locales/en/common.json
> +  "errorMaximumValue": "This value can't be more than {{maxValue}}",
Nitpick: "more" -> "greater"

2024-09-18 20:32 UTC, adamgall requested changes

2024-09-18 20:32 UTC, adamgall commented on src/components/DaoCreator/formComponents/GuardDetails.tsx
> +      setFieldValue('multisig.customNonce', Number(nonce));
Can you explain this change?

I don't see anywhere in this PR where the type of any `customNonce` property has changed from `string` to `number`.

2024-09-18 20:32 UTC, adamgall commented on src/hooks/schemas/DAOCreate/useDAOCreateSchema.ts
> +  parentNumSigners?: number;
It's fine that this is `undefined` for Azorius safes, right?

2024-09-18 20:32 UTC, adamgall commented on src/components/DaoCreator/index.tsx
> +    parentNumSigners: safe?.owners.length,
This will be `undefined` for Azorius safes, right?

2024-09-18 20:32 UTC, adamgall commented on src/components/Proposals/ProposalActions/CastVote.tsx
> +  }, [loadSnapshotProposal]);
What was the scenario that required this to be added?

2024-09-18 20:32 UTC, adamgall commented on src/components/Proposals/SnapshotProposalDetails/SnapshotProposalVotes.tsx
>                  votesBreakdownChoice && votesBreakdownChoice?.total
This conditional is kind of ambiguous.

The type of `votesBreakdownChoice` is:
```ts
const votesBreakdownChoice: {
    total: number;
    votes: SnapshotVote[];
}
```

, so why checking for it's existence? It's an object which will never be falsey. (I know you didn't change this line, but since we're here...

2024-09-18 20:32 UTC, adamgall commented on src/components/Proposals/SnapshotProposalDetails/SnapshotProposalVotes.tsx
> +              const choicePercentageFromTotal = totalVotesCasted
This conditional is kind of ambiguous. `totalVotesCasted` is a `number`, so are you checking to see if it's equal to 0 here? I'd prefer to be explicit if that's the case: `totalVotesCasted !== 0 ? ...`

2024-09-18 20:32 UTC, adamgall commented on src/hooks/DAO/useClawBack.ts
> +              safeAddress: getAddress(parentAddress),
This `getAddress` seems unneeded.

2024-09-18 20:32 UTC, adamgall commented on src/hooks/schemas/DAOCreate/useDAOCreateSchema.ts
> +                .required(),
Ah I didn't realize you wrote this validator. Nice.

2024-09-18 20:32 UTC, adamgall commented on src/pages/daos/[daoAddress]/new/index.tsx
> +    );
Gah can you explain this change? Why so many places that the "custom nonce" could come from?

2024-09-18 20:32 UTC, adamgall commented on src/providers/App/hooks/useSafeAPI.ts
I believe I remember why these changes are here... the Safe API requires that addresses passed into it are fully checksummed, right?

However, my preference would be that rather than checksumming this address _right before it's required to do so_, the address was just plain ol _already_ checksummed.

Meaning, where did this address come from? Loaded in from some data provider (blockchain, moralis, subgraph, idk, etc) originally, probably. Can we get this address into its proper checksummed form as it comes into the app?

Which would render these changes unnecessary.

2024-09-19 13:32 UTC, DarksightKellar commented on src/components/DaoCreator/formComponents/GuardDetails.tsx
> +      setFieldValue('multisig.customNonce', Number(nonce));
Ah yes this is good. `SafeConfiguration.customNonce` in `createDAO.ts` is a `number`. Doing `setFieldValue('multisig.customNonce', nonceWhichIsAString)` skips that typing and _makes_ it a string, which is obvious when inspecting or logging `multisig.customNonce` after setting.

I don't remember if is was in this instance, but this led to a validation edge case bug during my tests, I think when comparing the set form value with another number. I don't remember exactly what, but it _was_ a problem.

Because of this callout I've realised there are plenty of `setFieldValue('multisig.customNonce', nonce)`s around the codebase. Gonna update them to set a number instead.

2024-09-19 13:40 UTC, DarksightKellar commented on src/components/Proposals/ProposalActions/CastVote.tsx
> +  }, [loadSnapshotProposal]);
`extendedSnapshotProposal` was undefined until this is called. While it's called in a parent component (`SnapshotProposalDetails`), the set value wasn't reflected here for some reason.

2024-09-19 13:43 UTC, DarksightKellar commented on src/components/Proposals/SnapshotProposalDetails/SnapshotProposalVotes.tsx
>                  votesBreakdownChoice && votesBreakdownChoice?.total
Yeahhh good catch here. The whole thing seems to be unnecessary, and we should be able to just do `const votesBreakdownChoiceTotal = votesBreakdownChoice.total`, or just `votesBreakdownChoice.total` directly

2024-09-19 13:47 UTC, DarksightKellar commented on src/components/Proposals/SnapshotProposalDetails/SnapshotProposalVotes.tsx
> +              const choicePercentageFromTotal = totalVotesCasted
Updated to `totalVotesCasted > 0` before I saw this comment. Which should we prefer?

2024-09-19 13:48 UTC, DarksightKellar commented on src/hooks/DAO/useClawBack.ts
> +              safeAddress: getAddress(parentAddress),
Alas, it is.

2024-09-19 13:51 UTC, DarksightKellar commented on src/pages/daos/[daoAddress]/new/index.tsx
> +    );
> Why so many places that the "custom nonce" could come from?
That is a good question, one which I did try to figure out but didn't get much clarity into.

But, for this change, it was needed for creating a subsafe on a multisig safe whose `nextNonce` hasn't yet updated. In that case, setting a custom nonce was not being reflected in the built tx.

2024-09-19 13:53 UTC, DarksightKellar commented on src/hooks/schemas/DAOCreate/useDAOCreateSchema.ts
> +  parentNumSigners?: number;
Sigh, dammit I forgot to test the Azorius path. that'll decide what I do with this arg. So I don't have an answer now unfortunately. Lemme circle back

2024-09-19 14:22 UTC, DarksightKellar commented on src/providers/App/hooks/useSafeAPI.ts
Hmm that's interesting because my line of reasoning was from the other end -- since these Safe API calls are the only things requiring a checksummed address, we co-locate that (seemingly redundant) transformation with the call that requires it, instead of hunting down the data sources. 

I do see the pros to your point though...

2024-09-19 17:22 UTC, adamgall commented on src/components/DaoCreator/index.tsx
> +    parentNumSigners: safe?.owners.length,
Same thing as previous comment, closing.

2024-09-20 14:01 UTC, adamgall commented on src/hooks/schemas/DAOCreate/useDAOCreateSchema.ts
> +  parentNumSigners?: number;
@DarksightKellar I see new commits. What's the update on this?

2024-09-20 14:01 UTC, adamgall commented on src/providers/App/hooks/useSafeAPI.ts
@DarksightKellar I see new commits. What's the update on this?

2024-09-20 16:15 UTC, merged