Use `fallbackTokenData`
decentdao/decent-interface pull request #2377
Opened 2024-09-27 14:02 UTC by DarksightKellar

This PR implements a fallback for transferred token data when safeAPI.getToken throws.

2024-09-27 20:44 UTC, mudrila reviewed
Some comments sir - but mostly code styling / "my user feedback" - so feel free to reason your vision and I'll approve :)

2024-09-27 20:44 UTC, mudrila commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +      tokenAddressesOfTransfers.map(async addr => {
Is there other `address` variable in the scope? Why just not naming it `address`?

2024-09-27 20:44 UTC, mudrila commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +            name: fallbackTokenData?.name,
Seems like this optional chaining is redundant - we already doing early return

2024-09-27 20:44 UTC, mudrila commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +              name: 'Unknown',
Wondering if that makes sense to also add some sort of tooltip in place where we're displaying to outline that we weren't able to load token metadata

2024-09-27 20:44 UTC, mudrila commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +              symbol: '???',
I'd suggest using `---` instead - but that's just "my personal user preference" - kinda makes more sense to me personally that `---` means we weren't able to fetch something in comparison to `???` which for me means "some unexpected shit is going on"

2024-09-30 12:58 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +      tokenAddressesOfTransfers.map(async addr => {
Because `address` on its own doesn't say anything about what and where these addresses came from

2024-09-30 13:02 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +            name: fallbackTokenData?.name,
True

2024-09-30 13:03 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +              symbol: '???',
Wholeheartedly agree

2024-09-30 13:04 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +              name: 'Unknown',
idk tbh. And I also don't know if this is worth pursuing if this issue is potentially a testnet only problem

2024-09-30 13:08 UTC, DarksightKellar commented
@decentdao/engineering Looking for feedback re:
> Also the `setTimeout` retry in case of rate limited error was removed because I'm not sure about the end result of this PR yet and didn't want to commit to a lengthy refactor at this point. If needed, this functionality can be restored in some form during review

See diff on `140`

2024-09-30 13:13 UTC, mudrila commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +      tokenAddressesOfTransfers.map(async addr => {
I'd say neither `addr` - that's why either suggesting not shortcutting or putting proper variable naming
But this one is super minor - I just personally don't line shortcut variable naming - feel free to ignore :)

2024-10-01 11:20 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +      tokenAddressesOfTransfers.map(async addr => {
oh lmaooo you meant the `addr` _in the callback_. That wasn't diff from this PR so didn't realise that's what you were referring to. Thought you meant `tokenAddressesOfTransfers` which is what I'd updated.

I mean, I don't mind it but sure I can update it too.

2024-10-01 12:50 UTC, adamgall requested changes

2024-10-01 12:50 UTC, adamgall commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +              name: 'Unknown',
Nitpicky but let's put this "Unknown" string into a localization file

2024-10-01 12:53 UTC, adamgall commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +              decimals: 18,
Also, we don't know that this unknown token is actually 18 decimal places, right?

I'm almost thinking that maybe we just straight up _ignore_ any transfer records where attempting to get the token data from Safe API fails, instead of attempting to backfill those records with dummy data.

2024-10-01 15:20 UTC, adamgall approved these changes

2024-10-01 15:27 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +              name: 'Unknown',
No longer an issue after [this commit](https://github.com/decentdao/decent-interface/pull/2377/commits/c74d5ce11cd8f4bec83fab412917886e6ecde2a9)

2024-10-01 15:28 UTC, DarksightKellar commented on src/hooks/DAO/loaders/useDecentTreasury.ts
> +              name: 'Unknown',
Resolved in [this commit](https://github.com/decentdao/decent-interface/pull/2377/commits/c74d5ce11cd8f4bec83fab412917886e6ecde2a9). And, whew.

2024-10-01 16:38 UTC, mudrila approved these changes
Lezzgooo

2024-10-01 16:38 UTC, merged