Cancel payment UI
decentdao/decent-interface pull request #2384
Opened 2024-09-30 16:53 UTC by mudrila

Closes #2354

2024-10-01 12:33 UTC, DarksightKellar reviewed
A question and a suggestion. I don't feel strongly about either, lemme know what ya think, then I can approve.

2024-10-01 12:33 UTC, DarksightKellar commented on src/components/ui/forms/InputBox.tsx
Good riddance.

2024-10-01 12:33 UTC, DarksightKellar commented on src/components/pages/Roles/forms/RoleFormPaymentStreams.tsx
> +              const canBeCancelled =
Normally I'd be fine with this, but on 2nd thought, since cancelling is a pretty significant feature, and for the sake of potential bug fixes in the future so that we would not have to remember to update the "is cancelled" logic in more than one place, I'd say yep, let's risk premature optimisation and DRY here.

2024-10-01 12:33 UTC, DarksightKellar commented on src/components/ui/modals/ModalBase.tsx
> +                  zIndex: zIndex + 1,
What's the point of this +1 here? Because I noticed you're already doing a plus 1 in `ModalProvider`

2024-10-01 13:38 UTC, mudrila commented on src/components/ui/modals/ModalBase.tsx
> +                  zIndex: zIndex + 1,
So in `ModalProvider` it is needed to make `Overlay` appear on top of side drawer (side drawer has same `zIndex` as modal).
And here it is needed to make actual modal content appear on top of overlay - when I was testing with the same `zIndex` - they appeared on the same level and effectively content wasn't visible 🤷🏼

2024-10-01 15:23 UTC, DarksightKellar commented on src/components/ui/modals/ModalBase.tsx
> +                  zIndex: zIndex + 1,
Ah, lool. Well. Gotta love `zIndex`.

2024-10-01 16:15 UTC, mudrila commented on src/components/pages/Roles/forms/RoleFormPaymentStreams.tsx
> +              const canBeCancelled =
Done sir - actually turned out to look lovely :)

2024-10-01 16:54 UTC, Da-Colon requested changes
Found a few issues in testing.

- [x] Could use some padding
![image](https://github.com/user-attachments/assets/aec9c234-e05c-49f3-a3f4-1ac4a790714d)
![image](https://github.com/user-attachments/assets/2de8680b-1a15-486a-a13b-5e1a620a9877)
---
- [x] When cancelling a payment, I'm unable to click `Cancel Payment` in drawer or modal
---
- [x] (might be unrelated to this PR): Unable to close drawer by clicking outside the drawer
---
- [ ] @decentdao/design For the mobile swipe. Its not really obvious that this field can be swiped. Is this okay for now?

2024-10-01 18:32 UTC, mudrila commented
> (might be unrelated to this PR): Unable to close drawer by clicking outside the drawer

Hmm, where exactly? I checked for cancelling confirmation and drawer is closed perfectly fine 🤔

2024-10-01 19:00 UTC, mudrila commented
> Found a few issues in testing.
> 
> * [x]  Could use some padding
>   ![image](https://private-user-images.githubusercontent.com/38386583/372565677-aec9c234-e05c-49f3-a3f4-1ac4a790714d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDk0OTAsIm5iZiI6MTcyNzgwOTE5MCwicGF0aCI6Ii8zODM4NjU4My8zNzI1NjU2NzctYWVjOWMyMzQtZTA1Yy00OWYzLWEzZjQtMWFjNGE3OTA3MTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE4NTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNTM5NWYyM2IyYTlhZjdkYzRkYjZhOTUyNzhhNTg3YTM0YzZmNTdjNGM2MjJkN2JjODMyNzRhYmE0MjY3ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7tugPa-c9wDmqN4NVQnoL37-oojx_Hm5zMiH-y6ZYvA)
>   ![image](https://private-user-images.githubusercontent.com/38386583/372566123-2de8680b-1a15-486a-a13b-5e1a620a9877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDk0OTAsIm5iZiI6MTcyNzgwOTE5MCwicGF0aCI6Ii8zODM4NjU4My8zNzI1NjYxMjMtMmRlODY4MGItMWExNS00ODZhLWExM2ItNWUxYTYyMGE5ODc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE4NTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZGI0OGQ3M2QwYTNkNGM2OGQ0ZjI5MWFiZmJjMjBlMGFmZTZmNWQ1ZTI2MzczMDM3ZDM4MzMzOTE2ZTllMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-jYmx_Sp-ZIPVjXJAZbmTzXny9LvNPG3fj-rppVkTVE)
> 
> * [x]  When cancelling a payment, I'm unable to click `Cancel Payment` in drawer or modal
> 
> * [x]  (might be unrelated to this PR): Unable to close drawer by clicking outside the drawer
> 
> * [ ]  @decentdao/design For the mobile swipe. Its not really obvious that this field can be swiped. Is this okay for now?

Okie, think it might be happening due to missing `DrawerOverlay` - also it was missing from the design implementation standpoint. Added that. Check dat out pls sir pls :)

2024-10-01 19:30 UTC, Da-Colon commented
> > (might be unrelated to this PR): Unable to close drawer by clicking outside the drawer
> 
> Hmm, where exactly? I checked for cancelling confirmation and drawer is closed perfectly fine 🤔

Its working now 🤷

2024-10-01 20:39 UTC, Da-Colon approved these changes
Code is looks good to me.

2024-10-02 10:48 UTC, DarksightKellar approved these changes

2024-10-02 13:59 UTC, adamgall commented on src/pages/DAOController.tsx
> +          await switchChainAsync({ chainId: getChainIdFromPrefix(urlAddressPrefix) });
This was kinda wild, glad you found the fix

2024-10-02 14:01 UTC, adamgall approved these changes
Look good thanks @mudrila !

2024-10-02 14:01 UTC, merged

2024-10-03 17:47 UTC, nicolaus-sherrill commented
![image](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjZmYzQ2NmViZjVkMzAwMDA4NjAxNWUxIiwiaWQiOiI0NzQ4MjUzZS03YjlkLTQ5NWYtYTkyZC1hODcwY2FjMTBjYTYifQ==)

This page design on mobile isn't quite right. It's somewhere between a full page and a drawer. I am expecting a full page to load in here.
<details><summary>Browser metadata</summary>





```
Path:      /home?dao=sep:0xfa1A70E88Ff76F6934322c41F84Da1c11b2bfb40
Browser:   Chrome 129.0.0.0 on Mac OS 10.15.7
Viewport:  1471 x 904 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2384.app.dev.decentdao.org%2Fhome%3Fdao%3Dsep%3A0xfa1A70E88Ff76F6934322c41F84Da1c11b2bfb40&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=129.0&resolution=1471x904&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2384.app.dev.decentdao.org/home?dao=sep:0xfa1A70E88Ff76F6934322c41F84Da1c11b2bfb40) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=66fc466ebf5d3000086015e1&commentID=66fed8ac537e8df806f92c36&resolution=resolved)