Bring Role / Payment editor closer to the design
decentdao/decent-interface pull request #2393
Opened 2024-10-03 21:20 UTC by mudrila

## Changes

- Update display of tabs buttons on mobile - they aren't taking full width anymore, as per design
- Update edit role / add payment / edit payment drawers - it is not overlapping original title / "Go Back Button" anymore but rather conditionally switching button behavior and content
- Remove subtitles from the add / edit payment form and move them into info tooltips
- Better position "Learn More" link in add / edit payment form
- Update width of date selector - each field is not taking full width anymore thus they're staying on the same row via shrinking / increasing responsively

## Addressed Issues

Closes #2392 

## Updated UI
<img width="768" alt="Screenshot 2024-10-03 at 23 13 26" src="https://github.com/user-attachments/assets/e2e3fd32-b256-47cc-805d-7819b9251943">
<img width="426" alt="Screenshot 2024-10-03 at 23 03 24" src="https://github.com/user-attachments/assets/7b4cd310-4a31-4a75-8fa2-42fbde3effe5">
<img width="426" alt="Screenshot 2024-10-03 at 23 03 29" src="https://github.com/user-attachments/assets/dc96e869-b3ac-4ba6-99ed-dee67b83db0a">
<img width="426" alt="Screenshot 2024-10-03 at 23 03 36" src="https://github.com/user-attachments/assets/b385c86e-814f-4602-8284-fb62a42e6d22">
<img width="426" alt="Screenshot 2024-10-03 at 23 03 42" src="https://github.com/user-attachments/assets/e03261ae-337f-4453-b0fe-270ad4f40607">
<img width="768" alt="Screenshot 2024-10-03 at 23 04 10" src="https://github.com/user-attachments/assets/ce707ff0-5b04-41c9-83e0-2e0a10512592">
<img width="768" alt="Screenshot 2024-10-03 at 23 04 15" src="https://github.com/user-attachments/assets/c7f64638-7871-48b0-a3a9-93f8137343a8">
<img width="768" alt="Screenshot 2024-10-03 at 23 12 48" src="https://github.com/user-attachments/assets/11bec86e-3d16-4c3a-bd3f-65130868fbd6">

2024-10-04 08:53 UTC, xanaramoss reviewed
<img width="113" alt="Screenshot 2024-10-04 at 10 29 27" src="https://github.com/user-attachments/assets/f7f0f877-09ba-4477-a80b-fa7a81cfabf4">
Can we make these icons the same as the designs? They don't have the number it's just the calendar and the color is Lilac/0.
For some reason, they look a bit bulky. Not sure why. 

Also the Heading "Starting, Cliff, Ending" neutral 7
Date number White/0


<img width="178" alt="Screenshot 2024-10-04 at 10 43 33" src="https://github.com/user-attachments/assets/36b2f9ca-65f4-481d-84ec-e84f84455676">
The info icon on the toast looks tiny. Can you confirm the size?

<img width="197" alt="Screenshot 2024-10-04 at 10 44 47" src="https://github.com/user-attachments/assets/f5de68a1-d456-456c-ac8c-91be9a1872bd">
Can you also confirm the padding between the icon + add payment? It should only be 4 px. 

Our designs have an inconsistency in the colors of the headings.
For example Mobile VS Desktop on Role Info. "Role name, description, member" has 2 different colors. Let me confirm this with @nicolaus-sherrill and I will get back to you.

2024-10-04 13:27 UTC, Da-Colon reviewed
Nothing to add to @xanaramoss Will look at it live again when updated.

2024-10-08 14:14 UTC, adamgall commented on src/pages/daos/[daoAddress]/roles/edit/details/index.tsx
> +  );
Oh here's that `button` (at least, the logic for its onclick)!

2024-10-08 14:14 UTC, adamgall commented on src/components/ui/page/Layout/index.tsx
> +          : `"header header"
So, why do we need a special layout just for Roles?

2024-10-08 15:10 UTC, mudrila commented on src/components/pages/Roles/RoleCard.tsx
> +    <Card onClick={handleRoleClick}>
Oh, that's definitely by accident

2024-10-08 15:10 UTC, mudrila commented on src/pages/daos/[daoAddress]/roles/edit/details/index.tsx
> +  );
Yessir - that's the one 😄

2024-10-08 15:11 UTC, mudrila commented on src/components/ui/page/Layout/index.tsx
> +          : `"header header"
In order to show "Powered by Hats / Vector / Sablier" special footer, and only on the roles list

2024-10-08 15:12 UTC, adamgall commented on src/components/ui/page/Layout/index.tsx
> +          : `"header header"
Why can't we just add that to the Roles index page, instead of messing with the larger Layout?

2024-10-08 15:13 UTC, adamgall commented on src/components/ui/page/Layout/index.tsx
> +          : `"header header"
@decentdao/design is this what yall want?

2024-10-08 15:18 UTC, mudrila commented on src/components/ui/page/Layout/index.tsx
> +          : `"header header"
In order to push it to the page's footer in the bottom of the screen - otherwise produced layout & styling to achieve this effect is complete nightmare :(
Probably - it will work just fine to have it right under the list (yes, that will break our design pattern - but visually it looks good, and I think it also makes sense to show that on desktop and other roles pages on this position - aka not in the page's footer but table / proposal summary footer )

2024-10-08 18:57 UTC, nicolaus-sherrill commented
<img width="903" alt="Screenshot 2024-10-08 at 1 00 29 PM" src="https://github.com/user-attachments/assets/69764d77-3b47-4bb7-ad79-25718874909f">

@mudrila seriously banger work here

Only things that I caught were on the mobile role details. Tiny styling discrepancies from our designs.

Otherwise everything else looks killer

2024-10-08 18:58 UTC, nicolaus-sherrill requested changes
Leaving review w/ change request for above comment (forgot to leave it through this workflow!)

2024-10-10 19:29 UTC, mudrila commented on src/components/ui/page/Layout/index.tsx
> +          : `"header header"
@nicolaus-sherrill Seems like there're multiple designs - @xanaramoss was pointing out that eventually you've created a version with pinning that "Powered By" endorsement to the page's footer
https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=5125-12343&node-type=frame&m=dev
But yeah, I eventually changed it to the version which is on your screenshots now.

2024-10-10 19:58 UTC, nicolaus-sherrill approved these changes

2024-10-10 20:27 UTC, adamgall approved these changes
Looking good sir, thank you!

2024-10-10 21:05 UTC, merged