Fix bug causing ENS input in role member edits to crash
decentdao/decent-interface pull request #2414
Opened 2024-10-16 15:25 UTC by DarksightKellar

Closes #2411

This PR is probably messy tbvh so looking for some callouts here.

To summarise: 

- The role form values are not actually processed until at or near proposal creation time
- Until then, whatever the user input, as long as it passes ENS validation, should be what the form value holds. This means we should only attempt to grab the address behind the ENS string _at the time_ when `getAddress` was previously being used and would've failed.
- Since all role edit objects are being processed in parallel in `useCreateRoles` before actual proposal preparation begins, there's one point at which we can transform all strings to `Address` types.
- In `RoleFormCreateProposal.tsx:100,101`, `roleHat.wearer` as a form value is both `undefined`-able and may hold an ENS string. `getAddress` removed.
- I've renamed some references to `wearerAddress` to `wearer` to make it more obvious that we're dealing with a string that is possiby _not_ an `Address`.

2024-10-16 19:55 UTC, adamgall requested changes

2024-10-16 19:55 UTC, adamgall commented on src/components/pages/Roles/RolesDetailsDrawer.tsx
> +  const { getDAOName } = useGetDAONameDeferred();
I know this is somewhat legacy code from before changes, but since you're here no need to continue using the wrong hook. This `useGetDaoName[Deferred]` hook is for getting DAO names, specifically, not really for simply resolving ENS names.

2024-10-16 19:55 UTC, adamgall commented on src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
> +
I'm surprised that this code isn't duplicated (or shared) with the non-mobile version of this component. I'd expect that the differences between `RolesDetailsDrawer` and `RolesDetailsDrawerMobile` are only visual. Should they behave differently too?

cc: @Da-Colon

2024-10-16 19:55 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormInfo.tsx
> +
Yeah I dig this

2024-10-16 19:55 UTC, adamgall commented on src/components/pages/Roles/forms/RoleFormInfo.tsx
> +                  setRoleWearerString(inputWearer);
Super nitpick but why create a `const` for `inputWearer` when just using it once?

2024-10-16 20:29 UTC, mudrila commented on src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
> +
Not from the validation point - that's certainly. Yet, there's somewhat good place to generally refactor / restructure how modals are done - it seems like we're shifting towards "modal on desktop, drawer on mobile" pattern, and the amount of modals we're having is kinda getting bigger - so our "global modal" component growing too much (I knew it will become a problem from the very beginning 🤷🏼‍♂️ ).

I'd like to get that refactored - but think we can keep it "as is" in this PR - I believe that's out of scope here

2024-10-16 20:39 UTC, mudrila requested changes
Bunch of comments sir

2024-10-16 20:39 UTC, mudrila commented on src/components/pages/Roles/RolesDetailsDrawer.tsx
> +      getDAOName({ address: roleHatWearer }).then(displayName =>
Ooof, that's definitely smells 🤣 
I know that under the hood `getDAOName` resolves ENS name.
Yet, using this hook specifically for that purpose makes code quite confusing.

I'd suggest either extracting that logic of ENS name / account display name showing (BTW - seems like we're usually showing truncated version, maybe same should apply here and link to the Etherscan? @nicolaus-sherrill @adamgall @Da-Colon @xanaramoss WDYT?)

2024-10-16 20:39 UTC, mudrila commented on src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
> +
Ooooh, so this logic was just added - sorry, haven't recognized that before actually going into the code. Yeah, I think it would rather be better to remove it here. I assume issues are popping up when going directly to role details page on mobile and while tree / role initially loaded - so the drawer is empty or some errors due to ENS resolving are thrown - then I think it is better to adjust resolving logic, not this component. Maybe we need loading state here 

cc @nicolaus-sherrill 

I'd assume our bar loader should work

2024-10-16 20:39 UTC, mudrila commented on src/components/pages/Roles/types.tsx
> +  // `resolvedWearer` is auto-populated from the resolved address of `wearer` in case it's an ENS name.
At least that's what I see through the code - so I think it's all good here

2024-10-16 20:39 UTC, mudrila commented on src/hooks/utils/useCreateRoles.ts
> +      ).filter(hat => hat !== null);
Hmm, doesn't `filter` first works here? Will be less mapping then
Nitpick though, feel free to ignore

2024-10-17 11:05 UTC, DarksightKellar commented on src/components/pages/Roles/forms/RoleFormInfo.tsx
> +                  setRoleWearerString(inputWearer);
It was meant to be used below as well in `setFieldValue`, whoops. Will update

2024-10-17 11:13 UTC, DarksightKellar commented on src/components/pages/Roles/types.tsx
> +  // `resolvedWearer` is auto-populated from the resolved address of `wearer` in case it's an ENS name.
Yep

2024-10-17 11:21 UTC, DarksightKellar commented on src/hooks/utils/useCreateRoles.ts
> +      ).filter(hat => hat !== null);
Nah I don't think it will

2024-10-17 14:53 UTC, DarksightKellar commented on src/components/pages/Roles/RolesDetailsDrawer.tsx
> +      getDAOName({ address: roleHatWearer }).then(displayName =>
I've done a good bit of refactoring here now. Just trying to track down a potential render loop (that's not crashing the app, just almost 150 `Status: 429` logs as soon as you open the safes drawer

2024-10-17 14:59 UTC, DarksightKellar commented on src/hooks/utils/useGetAccountName.ts
> +export const getSafeNameFallback = async (
Separated out safe-specific logic so that the newly named `getAccountName` can be used in other contexts

2024-10-17 17:05 UTC, DarksightKellar commented on src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
> +
Ok, so I've made a bunch of updates after these comments. Plz see recent changes.

2024-10-17 17:08 UTC, DarksightKellar commented on src/components/pages/Roles/types.tsx
> +export interface RoleDetailsDrawerProps {
Extracted this interface out since it was exactly the same as `RoleDetailsDrawerMobileProps`

2024-10-17 17:11 UTC, DarksightKellar commented on src/pages/daos/[daoAddress]/roles/edit/index.tsx
> +        resolvedWearer: hat.wearerAddress,
`initialValues` is a `RoleFormValues[]`, but `hats` is a `DecentRoleHat[]`. This makes roles that already existed won't have an empty `RoleFormValues.resolvedWearer`, which led to undefined states when switching to edit views.

2024-10-17 17:40 UTC, mudrila approved these changes
Couple questions / comments, but LGTM :shipit:

2024-10-17 17:40 UTC, mudrila commented on src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
> +  let roleHatWearer = 'wearer' in roleHat ? roleHat.wearer : roleHat.wearerAddress;
Why `let` though?
Also, is it a trick for simplifying type compatibility constraints? Aka why `roleHat.wearer ?? roleHat.wearerAddress` doesn't work?

2024-10-17 17:40 UTC, mudrila commented on src/hooks/utils/useCreateRoles.ts
> +      ).filter(hat => hat !== null);
Yeah I've meant 
```
const modifiedHats: RoleHatFormValueEdited[] = (
        await Promise.all(
          values.hats.filter(hat => !!hat.editedRole).map(async hat => ({
              ...hat,
              editedRole: hat.editedRole,
              wearer: hat.resolvedWearer,
            })
          ),
        )
      );
```
This way filtering out `hat` with existing `editedRole` would happen before doing `map` - thus less iterations during `map`
Also it feels like `Promise.all` and `async hat` are redundant here 🤔 

But yeah, don't worry about this one - rather micro-optimization

2024-10-17 17:53 UTC, DarksightKellar commented on src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
> +  let roleHatWearer = 'wearer' in roleHat ? roleHat.wearer : roleHat.wearerAddress;
Gahh `let` was not intentional. Nice catch.

And yes the line is a trick so I don't have to do `(roleHat as Type1WhoseNameIDontRemember).wearer ?? roleHat.wearerAddress`

2024-10-17 18:48 UTC, adamgall reviewed
I think this is a great start, but IMO the core of these changes in `useGetAccountName.ts` could still use some cleanup. I don't know quite how to vocalize it, other than "it's still too messy and confusing imo"

2024-10-17 18:48 UTC, adamgall commented on src/pages/home/SafeDisplayRow.tsx
>    });
Why is this "fallback" function needed here?

2024-10-17 18:48 UTC, adamgall commented on src/hooks/utils/useGetAccountName.ts
Idk, the functions in this still seem pretty redundant and convoluted. 

Three exported functions: `useGetAccountName`, `useGetAccountNameDeferred`, `getSafeNameFallback`. Not clear to me at all when one should be used over the other.

2024-10-17 19:58 UTC, adamgall commented on src/pages/home/SafeDisplayRow.tsx
>    });
Is this "fallback" so that if the DAO doesn't have an ENS name set, it will run this other function which grabs the DAO name from the FractalRegistry contract? Seems like that's what's going on here.

2024-10-17 20:12 UTC, adamgall requested changes
There are issues with loading dao names on networks which are not currently connected.

This bug exists on dev and prod right now, too.

<img width="1552" alt="Screenshot 2024-10-17 at 4 12 16 PM" src="https://github.com/user-attachments/assets/65fdda6f-3afa-4dde-a884-0ad780dda0bf">
<img width="1552" alt="Screenshot 2024-10-17 at 4 12 26 PM" src="https://github.com/user-attachments/assets/2a28250d-0d69-4f81-bcf3-115adf860ee8">

2024-10-17 20:12 UTC, adamgall commented on src/components/ui/menus/SafesMenu/SafeMenuItem.tsx
I think the changes in here aren't working correctly. Notice how in the Favorites menu the DAO names from the non-currently-connected network aren't loading correctly.

<img width="1552" alt="Screenshot 2024-10-17 at 4 08 32 PM" src="https://github.com/user-attachments/assets/ff83fbf5-3aca-4d3b-8a9b-2e134b15256c">

2024-10-17 20:12 UTC, adamgall commented on src/pages/home/SafeDisplayRow.tsx
Same bugs are happening in the Home component, too. DAO Names from daos on networks which are not currently connected, are not loading.

2024-10-17 21:29 UTC, adamgall approved these changes
Approving, as long as #2417 is merged shortly after this branch, or even directly into this branch.

2024-10-17 21:30 UTC, adamgall commented on src/components/ui/menus/SafesMenu/SafeMenuItem.tsx
I've fixed this in #2417

2024-10-17 21:30 UTC, adamgall commented on src/pages/home/SafeDisplayRow.tsx
>    });
I've cleaned this up in #2417

2024-10-17 22:08 UTC, adamgall requested changes
@DarksightKellar , it seems like the scope of this PR maybe grew a bit further than it needed to, but then not far enough.

Is it possible to "undo" the changes in the PR which are _not_ related to simply allowing users to _input_ ENS names into the various Role forms?

The PR #2417 I opened up finishes up the work that you attempted (but was still buggy) in this PR, which managed _displaying_ the proper text for addresses.

2024-10-18 11:58 UTC, DarksightKellar commented
> changes in the PR which are _not_ related to simply allowing users to _input_ ENS names into

@adamgall Isn't that what your PR is doing though? I don't see the point of "undoing" the extra stuff, when #2417 also builds on that extra stuff. #2417 itself is more of a revert of the most recent `useGetAccountName` implementation in favour of the existing `useDisplayName`. 

I'd think we just merge it into this, and go from there. Otherwise not sure what the ask is here.

2024-10-18 14:48 UTC, adamgall approved these changes

2024-10-18 14:50 UTC, merged