`[BUGFIX]` rename getStreamsWithFundsToClaimFromFromHat -> getStreamsWithFundsToClaimNotCancelling
decentdao/decent-interface pull request #2447
Opened 2024-11-02 20:10 UTC by Da-Colon

Closes #2446 

So looking into it. 

- `getStreamsWithFundsToClaimFromFromHat`: 
  - is used during `member change` action. 
  - filters for `withdrawableAmount` and `isCancelling` (which indicates the user has set this payment to be cancelled)

- `getStreamsWithFundsToClaimFromFormHat`:
  - is used during `role removed` action
  
  Looking into it. When the role is removed. all streams are cancelled and flushed. so the user can't add in additionally to cancel individual streams. In the case of `member change` we track that if a stream is marked for cancelling that it is ignored  when looking at what streams to flush during that section and handled in the `payments` section

2024-11-02 20:17 UTC, adamgall requested changes
Thanks for looking into this.

Can we make both names a bit more descriptive then? Maybe

- getRoleChangedStreamsWithFundsToClaim
- getRoleRemovedStreamsWithFundsToClaim

2024-11-02 20:29 UTC, Da-Colon commented
> Thanks for looking into this.
> 
> Can we make both names a bit more descriptive then? Maybe
> 
> * getRoleChangedStreamsWithFundsToClaim
> * getRoleRemovedStreamsWithFundsToClaim
OoO good call.

2024-11-02 20:34 UTC, adamgall approved these changes

2024-11-04 10:02 UTC, mudrila approved these changes

2024-11-04 13:03 UTC, DarksightKellar approved these changes

2024-11-04 13:03 UTC, merged