Update multisig config copy
decentdao/decent-interface pull request #2555
Opened 2024-11-20 18:40 UTC by DarksightKellar

2024-11-20 18:56 UTC, adamgall requested changes

2024-11-20 18:56 UTC, adamgall commented on src/i18n/locales/en/daoCreate.json
> +  "helperSigners": "The addresses of owners to initialize the multisig with.",
There is still code which limits the number to <= 99. I assume that should be removed if we're no longer talking about it.

2024-11-20 18:58 UTC, DarksightKellar commented on src/i18n/locales/en/daoCreate.json
> +  "helperSigners": "The addresses of owners to initialize the multisig with.",
Good call

2024-11-20 21:57 UTC, adamgall approved these changes

2024-11-20 22:58 UTC, parkermccurley commented on src/i18n/locales/en/daoCreate.json
> +  "helperSigners": "The addresses of owners to initialize the multisig with.",
Part of this PRD includes removing the text-entry for "Number of Owners" and instead making the process of adding / removing addresses manual. This means we really don't need the upper bound IMO.

2024-11-21 10:08 UTC, mudrila commented on src/i18n/locales/en/daoCreate.json
> +  "helperSigners": "The addresses of owners to initialize the multisig with.",
> practically infinite scrolling

Guess that's not our concern - yeah, our UI is not optimized for such a large number of signers, but welp - it can render that large amount of inputs and you (probably) can create safe with whatever number of `owners` you want

So I'm rather leaning towards removing this logic / copy - but not holding this opinion strong, don't wanna start a debate 🤣

2024-11-21 10:19 UTC, DarksightKellar commented on src/i18n/locales/en/daoCreate.json
> +  "helperSigners": "The addresses of owners to initialize the multisig with.",
> Part of this PRD includes removing the text-entry for "Number of Owners" and instead making the process of adding / removing addresses manual. This means we really don't need the upper bound IMO.

Gotcha. Since this UX is gonna go away anyway, gonna leave as is. 

Also, this will basically mean, "if you can manually add hundreds of owners, then be our guest" no? @parkermccurley

2024-11-21 13:01 UTC, merged

2024-11-27 01:00 UTC, parkermccurley commented
Hey @DarksightKellar - we need this to say "transactions" not "proposals". Multisigs don't have proposals :)