`[Type Update]` DAO Info Typing
decentdao/decent-interface pull request #2574
Opened 2024-11-26 15:35 UTC by Da-Colon

In planning on how I would make the changes for #2530. I realized that one option I had is to quickly add the `fractalModules` lookup to the children array function that recursively gathers data down the tree, which I think would kinda mess up how and what is cached, leaving in several redundant requests I noticed we were making in the `useDAOInfoStore` setup and `useFractalNode`

Or I could work on this. This PR may end up quite a bit of file changes in the end as I am update and renaming a-lot of the base DAO typing. But I believe by doing this.

We can be alot more confident in the structure of this code and well we were going to do the work anyway. 

Creating a DRAFT for visibility

2024-11-27 13:19 UTC, Da-Colon commented on src/types/fractal.ts
New typing for `useDaoInfoStore` this typing update moves a little closer to tidying up state loading by adding a type check before data is loaded into the store and only setting used property to the store.

2024-11-27 13:20 UTC, Da-Colon commented on src/types/fractal.ts
> +export interface IDAO {
For lack of better naming here....`DAO` type is exported up by subgraph and why I could still use it might be confusing.

2024-11-27 13:20 UTC, Da-Colon commented on src/types/fractal.ts
> +  // replaces DaoInfo
I left these comments in. I think the `bottom up refactor` will get rid of the use of this as needed and think I can leave instances in place for now

2024-11-27 13:21 UTC, Da-Colon commented on src/types/daoGeneral.ts
As I was fixing typing saw these were not being used anywhere

2024-11-27 13:21 UTC, Da-Colon commented on src/store/daoInfo/useDaoInfoStore.ts
> -type DAOInfoWithoutLoaders = Omit<DaoInfo, 'isModulesLoaded' | 'isHierarchyLoaded'>;
Got rid of loaders. Now `null` means not loaded.

2024-11-27 13:22 UTC, Da-Colon commented on src/store/daoInfo/useDaoInfoStore.ts
> +  setSafeInfo: (safe: SafeWithNextNonce) => {
Just kept it clean and pass the raw response from our `useSafeApi` and do the type clean up here

2024-11-27 13:23 UTC, Da-Colon commented on src/providers/App/hooks/useSafeAPI.ts
> -      guard: getAddress(safeInfoResponse.guard),
This is taken care of else where now

2024-11-27 13:27 UTC, Da-Colon commented on src/components/DaoHierarchy/DaoHierarchyNode.tsx
> +  );
ALL that typing work was so I can do this haha. This is now cleaned up, isn't coupled with the main loader and has its own type that makes caching and loading much more proper (check out screenshots, things now no longer wait to start loading)

2024-11-27 18:00 UTC, DarksightKellar requested changes
Honestly mostly variable name suggestions

2024-11-27 18:16 UTC, DarksightKellar commented on src/store/daoInfo/useDaoInfoStore.ts
> -type DAOInfoWithoutLoaders = Omit<DaoInfo, 'isModulesLoaded' | 'isHierarchyLoaded'>;
Ah yes, I had a question/concern about the usage of `null` vs `undefined` vs `null | undefined`. I noticed an added ` | null` to a number of types in this PR, wondering what the reasoning is on those. Just wanna make sure we're all aligned on the logic and business meaning of what those types are meant to represent, and be consistent with it everywhere

2024-11-27 19:13 UTC, Da-Colon commented on src/types/fractal.ts
> +export type NullUnionUndefined = null | undefined;
Well "technically" its not `or`

2024-11-27 19:14 UTC, Da-Colon commented on src/types/fractal.ts
> +  daoModules: FractalModuleData[] | null;
wanted to break off from using `fractal`. and just `modules` is the property that is held on safe which is just addresses. (I guess I COULD rename that to modulesAddresses), and then this modules

2024-11-27 19:16 UTC, Da-Colon commented on src/types/fractal.ts
> +export type SafeWithNextNonce = SafeInfoResponseWithGuard & { nextNonce: number };
This is response type from our  safeApi.`getSafeData` which extends `getSafeInfo` seperate from our Apps GnosisSafe type data

2024-11-27 19:17 UTC, Da-Colon commented on src/hooks/utils/useUpdateSafeData.ts
> +  const lookupModules = useDecentModules();
leftovers

2024-11-27 19:20 UTC, Da-Colon commented on src/pages/dao/settings/general/SafeGeneralSettingsPage.tsx
> +  const { subgraphInfo, safe } = useDaoInfoStore();
I was almost wanted to remove the `info` part and just do `subgraph` but felt a little too generic, but don't think I want to make this any longer by adding DAO? But If you push back again I'll do it, I don't really care that much

2024-11-27 22:43 UTC, DarksightKellar commented on src/types/fractal.ts
> +  daoModules: FractalModuleData[] | null;
Definitely `modulesAddresses` for the address list then lool

2024-11-27 22:44 UTC, DarksightKellar commented on src/pages/dao/settings/general/SafeGeneralSettingsPage.tsx
> +  const { subgraphInfo, safe } = useDaoInfoStore();
Ehh your call then. Don't feel too strongly on it either

2024-11-28 09:06 UTC, Da-Colon commented on src/store/daoInfo/useDaoInfoStore.ts
> -type DAOInfoWithoutLoaders = Omit<DaoInfo, 'isModulesLoaded' | 'isHierarchyLoaded'>;
any in particular you can call out? 

For me its all about intention. If we not sure what it might be at runtime -> `undefined`. Otherwise its intentionally being set so -> `null`

2024-11-28 09:06 UTC, Da-Colon commented on src/types/fractal.ts
> +  daoModules: FractalModuleData[] | null;
ugh. okay fine

2024-11-28 09:11 UTC, Da-Colon commented on src/types/fractal.ts
> +  daoModules: FractalModuleData[] | null;
Done.

2024-11-28 12:22 UTC, DarksightKellar commented on src/types/fractal.ts
> +export type NullUnionUndefined = null | undefined;
It's not?

2024-11-28 13:39 UTC, DarksightKellar reviewed
Added some extra comments for context

2024-11-28 13:39 UTC, DarksightKellar commented on src/store/daoInfo/useDaoInfoStore.ts
> -type DAOInfoWithoutLoaders = Omit<DaoInfo, 'isModulesLoaded' | 'isHierarchyLoaded'>;
Added comments everywhere I could find them. I know it's about intention, just wanna make sure all intentions are aligned.

Personally I'd like to keep any possibility of `undefined` strictly at the edge of data layers, as much as possible. So, a type can be `undefined` if:
- it has no value (thus possibly a bug)
- it's not yet loaded in

TBH in my ideal world, `undefined` would be reserved strictly for "bugs", and I'd rather combine `null` with `loading` flags to determine if a value is `unset-but-still-loading` or `unset-and-done-loading`.

In any case I don't think "the absence of a value" is enough to confidently determine if it's still being loaded or not (especially if the value can be set to `null` OR `undefined` by some side effect. The code _should_ be the one to explicitly make that call and tell consumers if they should continue waiting for the thing they're waiting for.

2024-11-28 16:25 UTC, Da-Colon commented
> Added comments everywhere I could find them. I know it's about intention, just wanna make sure all intentions are aligned.

Personally I'd like to keep any possibility of undefined strictly at the edge of data layers, as much as possible. So, a type can be undefined if:

it has no value (thus possibly a bug)
it's not yet loaded in
TBH in my ideal world, undefined would be reserved strictly for "bugs", and I'd rather combine null with loading flags to determine if a value is unset-but-still-loading or unset-and-done-loading.

In any case I don't think "the absence of a value" is enough to confidently determine if it's still being loaded or not (especially if the value can be set to null OR undefined by some side effect. The code should be the one to explicitly make that call and tell consumers if they should continue waiting for the thing they're waiting for.

O you are refering to the lower level components, yeah I didn't go in with the intention to try to retype every component and value all the way DAO, just to rework the top level components, and deal with these bottom up props later.

But yeah I guess I can try to rework the typing in these components, here.

2024-11-29 15:41 UTC, mudrila approved these changes
I think this is already pretty big chunk of work - I'd like to get it merged and rather review follow-up PR to avoid 100+ files PR

2024-11-29 15:52 UTC, Da-Colon reviewed
reverted the typing in the lower level files @DarksightKellar

2024-12-01 17:40 UTC, Da-Colon commented on src/types/fractal.ts
> +export type NullUnionUndefined = null | undefined;
yeah `|` is union not or lol. But I deleted this so all good

2024-12-02 11:19 UTC, DarksightKellar approved these changes

2024-12-02 17:19 UTC, merged