Some cleanup work to close up PRD offshoot issues
decentdao/decent-interface pull request #2578
Opened 2024-11-27 19:32 UTC by DarksightKellar

Closes #2573
Closes #2570

2024-11-29 15:39 UTC, mudrila approved these changes

2024-11-30 08:58 UTC, Da-Colon requested changes
I think there is some more Wrap token stuff to remove no?

2024-11-30 08:58 UTC, Da-Colon commented on src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
>          setFieldValue('erc20Token.tokenSymbol', 'W' + symbol, true);
Probably can remove the whole path to wrapping a token in the `Create a (Sub)DAO` workflows

2024-11-30 08:58 UTC, Da-Colon commented on src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
> +  }
I'm going to want to clean this up during the `Formik` refactor/update and move all validation to Yup/Zod schemas. more localize the formik context and validation.

2024-12-04 16:06 UTC, DarksightKellar commented on src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
>          setFieldValue('erc20Token.tokenSymbol', 'W' + symbol, true);
updated, check it out @Da-Colon

2024-12-04 16:56 UTC, Da-Colon approved these changes
👍

2024-12-04 17:59 UTC, merged