Update withdraw modal UI
decentdao/decent-interface pull request #2581
Opened 2024-11-28 16:54 UTC by DarksightKellar

Closes #2527 
<img width="684" alt="Screenshot 2024-11-28 at 16 53 59" src="https://github.com/user-attachments/assets/54385993-48b3-4f44-9438-1658d364dbb8">

<img width="479" alt="Screenshot 2024-11-28 at 16 54 19" src="https://github.com/user-attachments/assets/c13332fa-ea50-44d2-bc70-47fe94621cb5">

2024-11-29 15:36 UTC, mudrila approved these changes

2024-11-30 09:12 UTC, Da-Colon requested changes
![image](https://github.com/user-attachments/assets/0b868570-c03b-4cf1-8e84-f7f1eb07425c)

Looks like the top line is slightly off-centered

2024-11-30 09:12 UTC, Da-Colon commented on src/components/ui/modals/DelegateModal.tsx
> +              marginTop="3rem"
random :D

2024-12-03 21:14 UTC, nicolaus-sherrill commented
Hey @DarksightKellar I have a few design callouts to what I am seeing in your screenshot:

- Text needs to be aligned to baseline.
- Every token/network/avatar circle should be 24px
- Button spacing needs to be reduced
- Apply card dimension effects
<img width="739" alt="Screenshot 2024-12-03 at 3 10 20 PM" src="https://github.com/user-attachments/assets/9b88bf42-ea27-4fee-bad0-10ac78edbafa">

2024-12-03 21:15 UTC, nicolaus-sherrill commented
@decentdao/engineering is it appropriate to truncate the wallet address in this modal or is it vital to see the entire address?

2024-12-04 16:00 UTC, DarksightKellar commented
> Hey @DarksightKellar I have a few design callouts to what I am seeing in your screenshot:
> 
> * Text needs to be aligned to baseline.
> * Every token/network/avatar circle should be 24px
> * Button spacing needs to be reduced
> * Apply card dimension effects
> 
> <img alt="Screenshot 2024-12-03 at 3 10 20 PM" width="739" src="https://private-user-images.githubusercontent.com/62394931/392139818-9b88bf42-ea27-4fee-bad0-10ac78edbafa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjcxODgsIm5iZiI6MTczMzMyNjg4OCwicGF0aCI6Ii82MjM5NDkzMS8zOTIxMzk4MTgtOWI4OGJmNDItZWEyNy00ZmVlLWJhZDAtMTBhYzc4ZWRiYWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE1NDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4OGI5OTAzNzgyZjc5NzZlMzdhMzMzMDQ0NzMxMzI4MmUzNzYwYzA4MzZhYzMzMGQ5NTczMmZiOTg3M2VjYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gQJFbSTxvggxA9aIpfHn5Q5h7kbiFfNbddk6_CCqTQ4">

@nicolaus-sherrill See if the latest update matches expectation

2024-12-04 16:21 UTC, nicolaus-sherrill commented
@DarksightKellar looks good sir

2024-12-04 16:36 UTC, parkermccurley commented
Looks great! Approved

2024-12-04 17:00 UTC, Da-Colon approved these changes

2024-12-04 18:00 UTC, merged