`[Issue #2545]` add more socials
decentdao/decent-interface pull request #2584
Opened 2024-11-30 11:42 UTC by Da-Colon

Closes #2545 

- removes warcast icon from sidebar
- add social links to footer
- adjust spaces in footer
- `BugFix` ExternalLink green pill's hover state

![localhost_8888_(Desktop)](https://github.com/user-attachments/assets/bfee35d9-1b7d-428b-b21c-13b07b2eb5af)

2024-11-30 11:45 UTC, Da-Colon commented on src/components/ui/links/ExternalLink.tsx
> -    <Flex>
Don't need to wrap in a `Flex`

2024-11-30 11:45 UTC, Da-Colon commented on src/components/ui/links/ExternalLink.tsx
> -          mx="-0.75rem"
Not really sure why this was here? The hover state's padding was being squeezed by this.

2024-11-30 11:45 UTC, Da-Colon commented on src/constants/url.ts
> +export const URL_DISCORD = 'https://discord.gg/'; // @todo - Add Discord handle;
@nicolaus-sherrill Can I get the official links to use?

2024-12-02 18:01 UTC, mudrila requested changes
Looks good despite missing actual links

2024-12-02 19:11 UTC, nicolaus-sherrill commented
@Da-Colon 
Twitter: https://twitter.com/decentdao
Discord: https://discord.gg/Zh2emKspVF

Like Kirill said, TG is closed so we need an admin to provide a link.

2024-12-02 20:36 UTC, parkermccurley commented
Approved - thanks @Da-Colon

2024-12-02 20:40 UTC, parkermccurley commented
Approved

2024-12-03 04:07 UTC, mudrila approved these changes

2024-12-03 11:52 UTC, DarksightKellar approved these changes

2024-12-03 11:52 UTC, merged