Use same components between proposal builder and sablier stream proposal builder
decentdao/decent-interface pull request #2646
Opened 2024-12-20 21:02 UTC by mudrila

2025-01-07 14:23 UTC, adamgall commented
Thanks for the additional context @mudrila!

The UI on `/proposals/new/sablier/metadata` doesn't look identical to `/proposals/new/metadata`, there are a handful of differences. Maybe some or all of these are expected?

|difference|`/proposals/new/metadata`|`/proposal/new/sablier/metadata`|
|----------|-------------------------|--------------------------------|
|Page title|"Create Proposal"|"Create Proposal Template"|
|Title subtext|"A short title for this proposal"|"A short title for this proposal template"|
|Description subtext|"Add a brief description, markdown supported"|"Markdown syntax supported"|
|Preview card/section|Includes general proposal information|Includes Sablier-specific information|

## Nitpick on Naming

Not a change that was introduced in this PR, but I think calling the Sablier page "Create Proposal Template" isn't correct.

We're not _creating_ a template here, we're _using_ an existing template to create a proposal.

So maybe rename the new Sablier proposal workflow/page just "Create Proposal.

This would change the full breadcrumb from:
- "Your DAO / Proposal Templates / Create Proposal Template", to
- "Your DAO / Proposal Templates / Create Proposal"

which IMO is in line with the breadcrumb and page title for the original Create Proposal flow (at `/proposals/new/metadata`): "Your DAO / All Proposals / Create Proposal".

2025-01-07 14:24 UTC, adamgall reviewed
Thanks for the additional context @mudrila!

The UI on `/proposals/new/sablier/metadata` doesn't look identical to `/proposals/new/metadata`, there are a handful of differences. Maybe some or all of these are expected?

|difference|`/proposals/new/metadata`|`/proposal/new/sablier/metadata`|
|----------|-------------------------|--------------------------------|
|Page title|"Create Proposal"|"Create Proposal Template"|
|Title subtext|"A short title for this proposal"|"A short title for this proposal template"|
|Description subtext|"Add a brief description, markdown supported"|"Markdown syntax supported"|
|Preview card/section|Includes general proposal information|Includes Sablier-specific information|

## Nitpick on Naming

Not a change that was introduced in this PR, but I think calling the Sablier page "Create Proposal Template" isn't correct.

We're not _creating_ a template here, we're _using_ an existing template to create a proposal.

So maybe rename the new Sablier proposal workflow/page just "Create Proposal.

This would change the full breadcrumb from:
- "Your DAO / Proposal Templates / Create Proposal Template", to
- "Your DAO / Proposal Templates / Create Proposal"

which IMO is in line with the breadcrumb and page title for the original Create Proposal flow (at `/proposals/new/metadata`): "Your DAO / All Proposals / Create Proposal".

2025-01-10 14:24 UTC, mudrila commented
> > @mudrila gm, are we waiting on an update from you here?
> 
> Yessir - didn't get a chance to fix stuff from comments as was looking into different issue. Will get this stuff done today

@adamgall All should be fixed now - pls check

2025-01-11 09:24 UTC, DarksightKellar approved these changes
lgtm

2025-01-13 20:55 UTC, adamgall requested changes
In the new files (ProposalStream[s].tsx), I'd like to see more component composition.

```ts
enum FooEnum {
  HELLO = 'hello',
  GOODBYE = 'goodbye',
}

function Hello() {
  return <div>Hello</div>;
}

function Goodbye() {
  return <div>Goodbye</div>;
}

function Foo({ mode }: { mode: FooEnum }) {
  return (
    <div id="dynamic">
      {mode === FooEnum.HELLO && <Hello />}
      {mode === FooEnum.GOODBYE && <Goodbye />}
    </div>
  );
}

function Bar({ dynamic }: { dynamic: React.ReactNode }) {
  return <div id="dynamic">{dynamic}</div>;
}

function Caller() {
  return (
    <div>
      <div>Callr</div>
      <div>
        {/* Instead of doing code like this: */}
        <Foo mode={FooEnum.HELLO} />

        {/* Do code like this: */}
        <Bar dynamic={<Hello />} />
      </div>
    </div>
  );
}
```

2025-01-13 20:55 UTC, adamgall commented on src/types/proposalBuilder.ts
> +  PROPOSAL_FROM_TEMPLATE = 'PROPOSAL_FROM_TEMPLATE',
Is this being used?

2025-01-20 22:49 UTC, mudrila commented on src/types/proposalBuilder.ts
> +  PROPOSAL_FROM_TEMPLATE = 'PROPOSAL_FROM_TEMPLATE',
Not yet - so yeah, removing for now

2025-01-20 22:57 UTC, mudrila commented
> In the new files (ProposalStream[s].tsx), I'd like to see more component composition.
> 
> ```tsx
> enum FooEnum {
>   HELLO = 'hello',
>   GOODBYE = 'goodbye',
> }
> 
> function Hello() {
>   return <div>Hello</div>;
> }
> 
> function Goodbye() {
>   return <div>Goodbye</div>;
> }
> 
> function Foo({ mode }: { mode: FooEnum }) {
>   return (
>     <div id="dynamic">
>       {mode === FooEnum.HELLO && <Hello />}
>       {mode === FooEnum.GOODBYE && <Goodbye />}
>     </div>
>   );
> }
> 
> function Bar({ dynamic }: { dynamic: React.ReactNode }) {
>   return <div id="dynamic">{dynamic}</div>;
> }
> 
> function Caller() {
>   return (
>     <div>
>       <div>Callr</div>
>       <div>
>         {/* Instead of doing code like this: */}
>         <Foo mode={FooEnum.HELLO} />
> 
>         {/* Do code like this: */}
>         <Bar dynamic={<Hello />} />
>       </div>
>     </div>
>   );
> }
> ```

@adamgall Not quite sure which part of the mentioned components you'd like to decompose. 
Specifically in `ProposalStream(s).tsx` - there's no `mode` usage nor dynamic type rendering based on stream type, as currently only tranched streams are supported there. Are you talking rather about `ProposalBuilder` and how it renders `ProposalTransactions` / `ProposalStreams` based on the mode?

That part could be extracted to separate component, but honestly - amount of props drilling makes me uncomfortable doing that. Also, I feel like suggested improvements aren't decomposing stuff differently - they just moving conditional rendering handling one level above which then kills the point to another layer of decomposition.

I feel like I'm not getting your idea and desired result here, but also I feel like this additional refactoring should be done in a scope of separate issue - the goal / scope of this PR is to bring consistency between Sablier Proposal Builder and our "general" Proposal Builder. There's plenty of space for refactoring (like we ideally don't need `ProposalStream(s)` components and it could be joined with `ProposalTransaction(s)` as they both share quite identical logic in terms of array items management and UI controls) - but I'd rather push back that to further improvement issue. WDYT?

2025-01-22 01:43 UTC, adamgall commented
> > In the new files (ProposalStream[s].tsx), I'd like to see more component composition.
> > ```tsx
> > // code
> > ```
> 
> @adamgall Not quite sure which part of the mentioned components you'd like to decompose. Specifically in `ProposalStream(s).tsx` - there's no `mode` usage nor dynamic type rendering based on stream type, as currently only tranched streams are supported there. Are you talking rather about `ProposalBuilder` and how it renders `ProposalTransactions` / `ProposalStreams` based on the mode?
> 
> That part could be extracted to separate component, but honestly - amount of props drilling makes me uncomfortable doing that. Also, I feel like suggested improvements aren't decomposing stuff differently - they just moving conditional rendering handling one level above which then kills the point to another layer of decomposition.
> 
> I feel like I'm not getting your idea and desired result here, but also I feel like this additional refactoring should be done in a scope of separate issue - the goal / scope of this PR is to bring consistency between Sablier Proposal Builder and our "general" Proposal Builder. There's plenty of space for refactoring (like we ideally don't need `ProposalStream(s)` components and it could be joined with `ProposalTransaction(s)` as they both share quite identical logic in terms of array items management and UI controls) - but I'd rather push back that to further improvement issue. WDYT?

You're right, that pseudocode i made wasn't relevant to `ProposalStream[s].tsx`. There are some other files that IMO benefit from that pattern though.

I opened a PR to see if I could implement what I was suggesting: https://github.com/decentdao/decent-interface/pull/2683

2025-01-22 22:49 UTC, adamgall requested changes
Mostly all good! Nice work. Just a couple of change requests.

2025-01-22 22:49 UTC, adamgall commented on src/i18n/locales/en/modals.json
> +  "recipientsSublabel": "Enter the Ethereum wallet address of the recipient",
I'd remove "Ethereum". Just say "Enter the recipient's wallet address"

2025-01-22 22:49 UTC, adamgall commented on src/providers/NetworkConfig/web3-modal.config.ts
> +  accumulator[network.chain.id] = http(network.rpcEndpoint, { batch: true });
are we sure we want to do this here in this PR?

2025-01-22 22:49 UTC, adamgall commented on src/types/proposalBuilder.ts
> +  STREAMS = 'streams',
I think we spoke about getting rid of this new "streams" step, and just use "transactions" for the sablier stream form page.

2025-01-22 22:49 UTC, adamgall commented on src/hooks/utils/useResolveENSName.ts
> +      transport: http(mainnet.rpcEndpoint, { batch: true }),
Are we sure we wanna do this here in this PR?

2025-01-22 22:49 UTC, adamgall commented on src/hooks/utils/useGetSafeName.ts
> +    transport: http(mainnet.rpcEndpoint, { batch: true }),
Are we sure we wanna do this here in this PR?

2025-01-22 22:49 UTC, adamgall commented on src/components/ProposalBuilder/ProposalActionCard.tsx
I don't really love the big if/else conditional in the `ProposalActionCard` component. Why are these here? Is it because "send" and "airdrop" need to be displayed differently than the "add/edit/delete" actions?

Is there a different way we can achieve that which doesn't rely on a big conditional switch?

2025-01-23 11:01 UTC, mudrila commented on src/components/ProposalBuilder/ProposalActionCard.tsx
Yes - moving that logic into dedicated components
I was trying to keep them "stupid" for presentation purposes, but that's probably bad idea as it leads to overcomplicated `ProposalActionCard` and most unnecessary re-renders. Refactored that sir, check it out

2025-01-23 11:01 UTC, mudrila commented on src/hooks/utils/useGetSafeName.ts
> +    transport: http(mainnet.rpcEndpoint, { batch: true }),
Yeah at first place I was like "why not" - but now I feel little nervous putting so many big changes into this PR - so removed it.

2025-01-23 11:01 UTC, mudrila commented on src/hooks/utils/useResolveENSName.ts
> +      transport: http(mainnet.rpcEndpoint, { batch: true }),
Removed

2025-01-23 11:02 UTC, mudrila commented on src/types/proposalBuilder.ts
> +  STREAMS = 'streams',
Yessir - removed

2025-01-23 11:02 UTC, mudrila commented on src/providers/NetworkConfig/web3-modal.config.ts
> +  accumulator[network.chain.id] = http(network.rpcEndpoint, { batch: true });
Removed

2025-01-23 11:02 UTC, mudrila commented on src/i18n/locales/en/modals.json
> +  "recipientsSublabel": "Enter the Ethereum wallet address of the recipient",
Fixed

2025-01-23 20:50 UTC, adamgall approved these changes

2025-01-24 04:37 UTC, Da-Colon approved these changes
Alot of  moving parts. but looks like @adamgall is working closely, agreed with the comments and so far so good with the updates made so far. Plenty more to do. see yall in the next PR.

2025-01-24 04:37 UTC, Da-Colon commented on src/components/ProposalBuilder/ProposalActionCard.tsx
> +  );
how pressing is this? should an issue be created?

2025-01-24 04:37 UTC, Da-Colon commented on src/pages/dao/proposals/actions/new/SafeProposalWithActionsCreatePage.tsx
>      <ProposalBuilder
This ProposalBuilder's props are crazy...

2025-01-24 04:37 UTC, Da-Colon commented on src/providers/NetworkConfig/networks/polygon.ts
> +    disperse: '0xD152f549545093347A162Dce210e7293f1452150',
wasn't this already here or am I tripping?

2025-01-24 04:37 UTC, Da-Colon commented on src/providers/NetworkConfig/web3-modal.config.ts
> -  },
Yeah reading more, just putting `true` here there is a 0 second delay in the batching. This becomes obsolete in my PRs as we no longer are using this setup for reading the blockchain.

Was it causing issue for why you cut it?

2025-01-24 15:10 UTC, mudrila commented on src/providers/NetworkConfig/networks/polygon.ts
> +    disperse: '0xD152f549545093347A162Dce210e7293f1452150',
It was in other PR 😄

2025-01-24 15:14 UTC, mudrila commented
@adamgall @DarksightKellar @Da-Colon I went through testing paths and everything looks legit to me. Anyway, I'd like to have additional layer of testing when we'll be doing release - so I'm merging it into `develop` and then will be testing next release on the proposal builder side pretty heavily. Thank you for reviews!

2025-01-24 15:14 UTC, mudrila commented on src/pages/dao/proposals/actions/new/SafeProposalWithActionsCreatePage.tsx
>      <ProposalBuilder
Yeah man, it will change though.
However, it makes `ProposalBuilder` way more encapsulated and I generally love the direction it's moving towards

2025-01-24 15:18 UTC, mudrila commented on src/components/ProposalBuilder/ProposalActionCard.tsx
> +  );
Don't think that's pressing issue, but yeah - I'll create Linear ticket for this

2025-01-24 15:18 UTC, merged