Create example templates for transfer and Sablier stream
decentdao/decent-interface pull request #2647
Opened 2024-12-20 21:31 UTC by mudrila

<img width="1728" alt="Screenshot 2024-12-20 at 22 30 26" src="https://github.com/user-attachments/assets/5ee3f6b1-70f6-46a8-a780-9382c052e98c" />

2024-12-21 01:41 UTC, parkermccurley commented
Looking good! The Airdrop functionality isn't working for me, the "Submit" button activates inconsistently and when I do press it, nothing happens. Looking good, though

2024-12-21 05:56 UTC, mudrila commented
> Looking good! The Airdrop functionality isn't working for me, the "Submit" button activates inconsistently and when I do press it, nothing happens. Looking good, though

@parkermccurley Finally figured out what was wrong - can you check once more pls?

2025-01-07 14:33 UTC, adamgall requested changes
After filling in the "airdrop" proposal template modal form, I'm presented with what looks like the the New Proposal metadata page (url confirms this), but the Preview card on the side is all filled out. On this /proposals/new/metadata page I still need to fill out at least the title. However, even with the title input field empty, the "Create" button at the bottom of the screen is enabled. When clicking it however, nothing user-facing happens. So thats probably a bug this button should be disabled until a title is entered.

I also have bigger comments regarding UX flow and URL structures but we'll get to that soon.

2025-01-07 15:13 UTC, Da-Colon requested changes

2025-01-07 15:13 UTC, Da-Colon commented on src/providers/NetworkConfig/networks/mainnet.ts
> +    disperse: '0xD152f549545093347A162Dce210e7293f1452150',
Whats this new contract address?

2025-01-08 09:47 UTC, Da-Colon commented on src/providers/NetworkConfig/networks/mainnet.ts
> +    disperse: '0xD152f549545093347A162Dce210e7293f1452150',
Ah I see it now, did a search for it and didn't see it being used. got it.

2025-01-08 09:55 UTC, Da-Colon submitted a review, later dismissed
Approved, pending other comments

2025-01-08 10:34 UTC, Da-Colon commented
Maybe related to the work here if not, I can spin into a new linear issue. but when I fill out `transfer` action form and go the the proposal create page view.

![image](https://github.com/user-attachments/assets/4b410703-4555-4b21-b9a0-a41418f7d68c)

The submit button is highlighted to begin with but once I add a title or description it becomes disabled.

2025-01-10 13:51 UTC, mudrila commented
> Maybe related to the work here if not, I can spin into a new linear issue. but when I fill out `transfer` action form and go the the proposal create page view.
> 
> ![image](https://private-user-images.githubusercontent.com/38386583/401110259-4b410703-4555-4b21-b9a0-a41418f7d68c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MTczMDcsIm5iZiI6MTczNjUxNzAwNywicGF0aCI6Ii8zODM4NjU4My80MDExMTAyNTktNGI0MTA3MDMtNDU1NS00YjIxLWI5YTAtYTQxNDE4ZjdkNjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDEzNTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MWMyZmU4MmZlN2JmN2MzMzJlOTk4MzZiNTVkZGJkMzExNjFhNzNjMzM4MTM1MmE5NjA4YTM2Mzg5OGMzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aNxWuUh15SOeE480nJHEH_EBdwo9pX04-LyHOkk-0E8)
> 
> The submit button is highlighted to begin with but once I add a title or description it becomes disabled.

Also I see transfer action is not displayed in the list of actions which is wrong

2025-01-10 14:54 UTC, mudrila commented
@adamgall @Da-Colon All the issues should be resolved - kindly asking for re-review

2025-01-10 19:12 UTC, Da-Colon approved these changes
Reported bug fixed, thanks @mudrila

2025-01-11 09:44 UTC, DarksightKellar commented on src/components/ProposalBuilder/StepButtons.tsx
> +                  !proposalMetadata.title ||
Not sure what  the context is codewise, but shouldn't proposalMetadata.errors be defined if .title is not set, removing the need for this additional check?

2025-01-11 09:44 UTC, DarksightKellar commented on src/components/ProposalTemplates/ExampleTemplateCard.tsx
> +  // const { canUserCreateProposal } = useCanUserCreateProposal();
commented out code still here

2025-01-11 09:44 UTC, DarksightKellar commented
Lookin' good codewise. Still gotta test manually

2025-01-11 12:21 UTC, mudrila commented on src/components/ProposalBuilder/StepButtons.tsx
> +                  !proposalMetadata.title ||
`proposalMetadata.errors` is empty until you enter something in title / description - so if there's no title / description - there's no error 🤷🏼

2025-01-11 12:23 UTC, mudrila commented on src/components/ProposalTemplates/ExampleTemplateCard.tsx
> +  // const { canUserCreateProposal } = useCanUserCreateProposal();
Oopsie x2 - removed 🤣

2025-01-15 16:29 UTC, DarksightKellar commented
Unset translation strings:
<img width="239" alt="Screenshot 2025-01-15 at 16 23 22" src="https://github.com/user-attachments/assets/cd76b5d3-9845-497d-bfe4-7db3377e93df" />

I dont see any way to continue from this step when creating a streams proposal
<img width="1313" alt="Screenshot 2025-01-15 at 16 25 35" src="https://github.com/user-attachments/assets/59e965d1-cc05-47a1-8595-95e0e4bf34cf" />

2025-01-21 14:06 UTC, DarksightKellar requested changes
Sorry, another thought here:

<img width="822" alt="Screenshot 2025-01-21 at 14 02 44" src="https://github.com/user-attachments/assets/5e9ff6a9-74b6-45f0-b6b1-b793a4176edf" />

I don't really understand the limitations necessitating the messaging in the shot above, but if it's a universal requirement, why not hardcode them? What happens if the user doesn't read/or listen to the suggestions?

2025-01-21 14:07 UTC, DarksightKellar commented
Also clicking on submit proposal doesn't do anything on my end:
<img width="888" alt="Screenshot 2025-01-21 at 14 07 06" src="https://github.com/user-attachments/assets/4dc1560d-7451-4470-aaac-b0ae47b6732f" />

Not sure what I'm missing

2025-01-22 21:02 UTC, mudrila commented
@DarksightKellar @Da-Colon @johnqh FYI - I'm merging this PR into target branch since all these changes are inter-connected and it will be most reasonable to review and test them all together

2025-01-22 21:02 UTC, merged