ENG-36 Feature flag pattern. See README.md for usage
decentdao/decent-interface pull request #2648
Opened 2024-12-20 21:57 UTC by johnqh

See README.md for more details.

It uses an Injection, so if/when we use remote feature flags, we can change the injection in main.tsx without changing any downstream code.

2025-01-06 17:39 UTC, adamgall reviewed
@johnqh please see the file `src/constants/common.ts`, there is some additional "feature flag" code implemented there. I *think* can we probably safely remove all of those, they're probably all on by default at this point. Gotta double check though.

2025-01-07 10:23 UTC, DarksightKellar requested changes
This is nice. I got a couple or so change requests

2025-01-07 10:23 UTC, DarksightKellar commented on src/helpers/featureFlags.ts
> +    return this.urlFlags[key] ?? import.meta.env[key];
I'd like this to instead be `return import.meta.env[key] ?? this.urlFlags[key];` so that we can disable a feature on the environment level and not worry about someone setting a url param to get around it, even if it's a very unlikely scenario

2025-01-07 10:23 UTC, DarksightKellar commented on src/main.tsx
> +import { RouterProvider, useSearchParams } from 'react-router-dom';
unused import `useSearchParams`

2025-01-07 10:23 UTC, DarksightKellar commented on src/constants/common.ts
> +  return FeatureFlags.instance?.get(`VITE_APP_FLAG_${feature}`) === 'ON';
Since we're bridging these two feature flag implementations, can we go all the way? I'm thinking:
- Move all feature-flag code from here to `helpers/featureFlags.ts` (including, IMO, `isDevMode` on `70`)
- In `EnvironmentFeatureFlags`, use the `FeatureFlag` type so we're not depending on strings
- Update readme to reflect that adding/removing a feature flag should also happen in `const features` on `58`
- Might as well move `isFeatureEnabled` into `EnvironmentFeatureFlags`. I dunno.

2025-01-07 10:26 UTC, mudrila requested changes
Love dependency injection - though I think current implementation brings mixing conceptually different approaches - and I feel like we should streamline it to either leverage existing reactivity / observability patterns with Zustand & React Router - or we should keep it "vanilla-only" and remove usage of `useSearchParams`, moving logic of initializing feature flags  from query parameters into constructor of `EnvironmentFeatureFlags`

2025-01-07 10:26 UTC, mudrila commented on src/main.tsx
> +import { RouterProvider, useSearchParams } from 'react-router-dom';
Seems like `useSearchParams` is not used in this file?

2025-01-07 10:26 UTC, mudrila commented on src/constants/common.ts
> +  return FeatureFlags.instance?.get(`VITE_APP_FLAG_${feature}`) === 'ON';
Seems like this `=== 'ON'` conflicts with documentation - since in the docs we're referring to the value as boolean, while here we still rely on `ON`.
I'd like to stick to `ON` value - just aesthetic matter, so loosely held preference. But yeah - we need to align implementation

2025-01-07 10:26 UTC, mudrila commented on src/pages/home/HomePage.tsx
> +  searchParams.forEach((value, key) => {
We probably should wrap this `forEach` into `useEffect` to prevent re-running this loop during every re-rendering. I'm quite sure we wanna run this loop only when `searchParams` gets changed

2025-01-07 10:26 UTC, mudrila commented on src/helpers/featureFlags.ts
> +export class EnvironmentFeatureFlags implements IFeatureFlags {
I'm wondering if we wanna run this with class implementation in comparison to other patterns we have in the app. I'd prefer using React context or Zustand store to gain better observability and streamline UI update when search parameters are getting changed. 

Current `isFeatureEnabled` does not correlate with the observability and reactivity that we're gaining through `useSearchParams` - so we either should move logic with search params right into this class, obtaining query parameters using vanilla browser API, or refactor class into Zustand store - to keep reactivity consistent.

2025-01-09 19:45 UTC, adamgall reviewed
John could you also implement a small "other side" implementation, so this PR goes end to end? Something small, like an emoji in the footer or something. But importantly, this should utilize your new feature flag system. I'm just curious about seeing how this works in practice.

2025-01-09 19:45 UTC, adamgall commented on src/helpers/featureFlags.ts
> +    return this.urlFlags[key] ?? import.meta.env[key];
I personally think it would be good to allow both scenarios:
- feature disabled at environment level, enableable at query flag level
- feature enabled at environment level, disableable at query flag level

2025-01-09 19:45 UTC, adamgall commented on src/pages/home/HomePage.tsx
> +  searchParams.forEach((value, key) => {
I'm confused about why this code lives on the HomePage. What if a user loads a DAO directly? Then I think no feature flags are going to be set

2025-01-14 21:36 UTC, adamgall requested changes
When using the flag on any url which isn't the HomePage component results in the flag not being set

![image](https://github.com/user-attachments/assets/cb1bcb29-daee-4725-a1dc-b17e16bf73ac)

Would recommend you check out the code in src/components/ui/page/Global/index.tsx

2025-01-14 22:54 UTC, adamgall commented on src/constants/common.ts
> +import { FeatureFlags } from '../helpers/featureFlags';
Is this unused? (I'm on mobile, hard to tell...)

2025-01-14 22:54 UTC, adamgall commented on src/helpers/featureFlags.ts
> +  get(key: FeatureFlag): any;
Any reason we have these values typed as `any` instead of like `boolean`

2025-01-14 22:54 UTC, adamgall commented on src/helpers/featureFlags.ts
> +  configDemo = 'VITE_APP_FLAG_CONFIG_DEMO',
Since these are no longer environment variables (ah, reminder, delete them from the `.env` reference file please), and are controlled via query params, no real reason to keep this verbose syntax imo.

Edit: never mind, if the intention is to allow for query flags to override build time env bars, I guess they will need to match. Or... you can imply/strip the `VITE_APP_` prefix in the query params.

2025-01-14 22:54 UTC, adamgall commented on src/main.tsx
> +
Seeing a singleton get created outside of React like this makes me nervous! Seems like an antipattern to do this is a React codebase.

2025-01-15 15:27 UTC, adamgall commented on README.md
> +```
My suggestion is that we delete this pattern and just have callers utilize `isFeatureEnabled(FeatureFlag.feature)`

2025-01-15 15:49 UTC, DarksightKellar commented on src/hooks/utils/useCanUserSubmitProposal.ts
> +import { isDemoMode } from '../../helpers/featureFlags';
Linter error here, Just the order of imports

2025-01-15 15:49 UTC, DarksightKellar commented on src/main.tsx
> +
Eh I'm not too concerned in this instance because the code has nothing to do with React.

2025-01-15 15:52 UTC, DarksightKellar commented on src/helpers/featureFlags.ts
> +    return this.urlFlags[key] ?? import.meta.env[key];
I suppose the current `this.urlFlags[key] ?? import.meta.env[key]` fulfils that need then no? Can I resolve this conversation? @adamgall @johnqh

2025-01-15 16:30 UTC, adamgall commented on src/helpers/featureFlags.ts
> +    return this.urlFlags[key] ?? import.meta.env[key];
Yeah ur right this does work. It's a little strange to override an ON env var with an OFF query param, because technically every single string which is not `"ON"` acts as "off" in the query param flags.

2025-01-15 17:12 UTC, adamgall commented on src/helpers/featureFlags.ts
> +  get(key: FeatureFlag): any;
@johnqh but if they're coming from Environment Variables or Query Parameters they are strings, right?

2025-01-15 17:15 UTC, adamgall commented on src/main.tsx
> +
Oh no need to move the EnvironmentFeatureFlags class implementation to another file, I get what's going on here.

I think my concern was more around the fact that by creating this outside of React (outside of a hook, more specifically), we can't tap into `react-router-dom`'s `useLocation()` hook, which gives us access to query params. Importantly, it'll give us access to query params _all the time, whenever they change, regardless of how they change_. In the current implementation, we get access to the query params at page load and that's it. If there's other code in the codebase that, for example, sets a query param to turn on a feature flag, our current implementation here won't pick it up.

2025-01-15 17:15 UTC, adamgall commented on README.md
> +```
Yeah I hear you. It's no big deal either way i guess.

2025-01-15 17:44 UTC, adamgall commented on src/helpers/featureFlags.ts
> +  configDemo = 'VITE_APP_FLAG_CONFIG_DEMO',
I was talking about something slightly different than what you responded to, I think... 
I was actually talking about how you can declare one set of strings (like the full `VITE_APP_ENV_VAR`s), and then programmatically transform them into a "friendlier" string which could be used for the Query Params. I only say that because those big environment variables in the URL look ugly. See https://github.com/decentdao/decent-interface/pull/2673/files#diff-6eeb99f68ddd47adea0a1295d32ea04b3be72f8c13fc698d268950227e41d603R25-R28

---

but, for more context to your response:

Currently none of these flags are set on deployed instances.

Let me take that back.

To be clear, `VITE_APP_FLAG_DEMO_MODE=ON` is set on the `app.demo.decentdao.org` Netlify site. But when we switch over to Cloudflare, we won't have a standalone separate instance of a "demo site url" like we do with Netlify. I do not intend to set the `VITE_APP_FLAG_DEMO_MODE=ON` environment variable on the "Preview" deployments coming from Cloudflare (every branch except the "Production" branch: `main`)

2025-01-15 19:33 UTC, adamgall commented on src/main.tsx
> +
Ok, that is fair. My next question follows the first then. Will consumer components of this object's `get` function automatically re-render when the underlying value is changed from somewhere else?

2025-01-15 19:53 UTC, adamgall commented on src/helpers/featureFlags.ts
> +  get(key: FeatureFlag): any;
I am under the impression that from the point of view of all of these cloud provider build platforms, the "environment variables" that i'm setting at the Netlify / Cloudflare dashboard level are all treated as strings.

2025-01-15 21:06 UTC, adamgall approved these changes

2025-01-15 21:09 UTC, adamgall approved these changes
Looks good to me thank you John!

2025-01-16 00:02 UTC, merged